### ISSUE TITLE
highcharts-chart.component.ts is not part of the compilation

### ISSUE THREAD

**Issue by meixuexiang** [highcharts/highcharts-angular#1]
> ERROR in ./node_modules/highcharts-angular/src/app/highcharts-chart.component.ts
Module build failed: Error: /Volumes/repo/test/ng4-highsoft/node_modules/highcharts-angular/src/app/highcharts-chart.component.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Volumes/repo/test/ng4-highsoft/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:619:23)
    at plugin.done.then (/Volumes/repo/test/ng4-highsoft/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./node_modules/highcharts-angular/index.js 1:17-67
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.

**Comment by KacperMadej** [comment]
Hi, thank you for reporting.

Please add steps required to recreate the problem.

**Comment by KacperMadej** [comment]
Closing for now due to inactivity.

Will reopen in case it's possible to recreate the problem or when more info will be provided.

**Comment by schitzN** [comment]
+1

node v8.1.0
npm v5.0.3
angular-cli v1.5.0
angular5

Importing HighchartsChartComponent not into app.module.ts but in a submodule results in the same error.

`ERROR in ./node_modules/highcharts-angular/src/app/highcharts-chart.component.ts
Module build failed: Error: D:\Source\Repos\m***s\node_modules\highcharts-angular\src\app\highcharts-chart.component.ts is not part of the compilation output. Please check the other error me
ssages for details.
    at AngularCompilerPlugin.getCompiledFile (D:\Source\Repos\m****s\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (D:\Source\Repos\m***s\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 @ ./node_modules/highcharts-angular/index.js 1:17-67
 @ ./src/app/t***s/t***s.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`

**Comment by schitzN** [comment]
I just tried to import it in app.module.ts as described in the dokumentation and get the same error.

**Comment by narsaym** [comment]
+1

node v6.11.0
npm v4.6.1
angular-cli v1.5.5
Angular v5.0.0

Same issue here when importing ``HighchartsChartComponent`` in ``app.module.ts``

``Module build failed: Error: C:\Users\....\node_modules\highcharts-angular\src\app\highcharts-chart.component.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property......``

**Comment by KacperMadej** [comment]
Hi,

Could you provide steps required to recreate the problem?
Are you using the wrapper from NPM in your project?

You can add the file through the `include` in `tsconfig.json`.

**Comment by narsaym** [comment]
To reproduce this issue simply start a fresh angular project using angular-cli (v1.5.5) and Angular (v5.0.0) and install highcharts and highcharts-angular using ``` npm i highcharts-angular --save``` and ``npm install highcharts --save``, then import using the steps described in the docs:
```
...
import { HighchartsChartComponent } from 'highcharts-angular';

@NgModule({
  declarations: [
    HighchartsChartComponent,
    ...

```

**Comment by KacperMadej** [comment]
This looks like connected to or caused by the Angular 5 issue: https://github.com/angular/angular-cli/issues/8284

As a workaround using `include` in `tsconfig.json` like:

```
{
  ...
  "compilerOptions": {
    ...
  },
  "include": [
      "src/**/*",
      "node_modules/highcharts-angular/src/app/*"
  ]
}
```

**Comment by narsaym** [comment]
@KacperMadej while the workaround builds without errors, it generates the following warning:

```
WARNING in ./node_modules/highcharts-angular/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\....\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\....\node_modules\webpack\lib\Compilation.js:703:24)    at Compilation.finish (C:\Users\....\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\....\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\Users\....\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\....\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\....\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/highcharts-angular/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/highcharts-angular/src/app/highcharts-chart.component.ts
 @ ./node_modules/highcharts-angular/index.js
 @ ./src/app/main/myApp/myApp.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/highcharts-angular/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\....\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\....\node_modules\webpack\lib\Compilation.js:703:24)    at Compilation.finish (C:\Users\....\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\....\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\Users\....\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\....\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\....\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/highcharts-angular/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/highcharts-angular/src/app/highcharts-chart.component.ts
 @ ./node_modules/highcharts-angular/index.js
 @ ./src/app/main/myApp/myApp.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by danielsmeyer** [comment]
This workaround does not work for me, failed build.
I am lazy loading the module.

**Comment by KacperMadej** [comment]
@danielsmeyer You could copy the component into yours component folder and load from there as a any other component. If you have errors please share and if it's possible for you to provide steps required to recreate the problem - please do. You could check the demo to see if this helps in any way with getting through with the wrapper - the repository itself is a demo. More info in docs: https://github.com/highcharts/highcharts-angular#demo-app

**Comment by tleveque23** [comment]
I was finally able to make it work with the latest Angular / Angular Cli (5.2.9 / 1.7.3) without the need to copy the component in my own source.
The missing link is:
```
{
  ...
  "compilerOptions": {
    ...
  },
  "files":[
      "node_modules/highcharts-angular/src/app/highcharts-chart.component.ts"
  ],
  "include": [
      "src/**/*",
      "node_modules/highcharts-angular/src/app/*"
  ]
}
```
Look at the "files" property. This is what is missing from the documentation.
This SHOULD be added in the readme file.

But, I still think this module should be repackage to be a real Angular module. We should not have the need to include external typescript files to compile in our tsconfig file. This is a bad practice.
If this is really an official module from Highcharts, it should be a better quality.
Try to activate the strict mode in the compilerOptions to see. It will fail hard on this module.....

**Comment by KacperMadej** [comment]
@tleveque23 Thank you for the help and the information. I'll look into this.

**Comment by CollinGraf314** [comment]
I'm getting a failed build due to a file not found error on `node_modules/highcharts-angular/src/app/highcharts-chart.component.ts` even with the addition of the following to my tsconfig.json:
```
{
 ...
"files":[
      "node_modules/highcharts-angular/src/app/highcharts-chart.component.ts"
  ],
  "include": [
      "src/**/*",
      "node_modules/highcharts-angular/src/app/*"
  ] 
...
}```

I had `run npm install --save highcharts-angular` and I can navigate to the file via file explorer to see that it does exist.

**Comment by KacperMadej** [comment]
Please try with standard install (as in the docs - https://github.com/highcharts/highcharts-angular#installing) and then after first error (or right after installing the `highcharts-angular` NPM package) change in `node_modules` folder the content of `highcharts-angular` to the content of the branch: https://github.com/highcharts/highcharts-angular/tree/v5-dev 

If this will work then the branch will become new master. As for now it was tested on few machines and the problem was resolved, but it would be better to run more tests. In the meantime you can try the `v5-dev` branch solution.

**Comment by plfriedman** [comment]
This issue, combined with the Angular 6 related issue (https://github.com/highcharts/highcharts-angular/issues/29), there is no way to use this with a project that has been upgraded to Angular 6.x (currently 6.0.2).  It looks like both issues are related to the packaging of the module.  Is there any update as to when a new version that is packaged correctly will become available?

**Comment by KacperMadej** [comment]
Is the code on branch v5-dev working correctly for you?

**Comment by jonathan-bird** [comment]
@KacperMadej I couldn't get v5-dev working for Angular 6 (admittedly I know it's for v5). Error is:

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/highcharts-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/highcharts-angular/src/app/app.component.ts(7,31): error TS2497: Module '"/Users/jonathanbird/Projects/rumbles/rumbles-angular/node_modules/@types/highcharts/modules/exporting"' resolves to a non-module entity and cannot be imported using this construct.
node_modules/highcharts-angular/src/app/app.component.ts(10,1): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/jonathanbird/Projects/rumbles/rumbles-angular/node_modules/@types/highcharts/modul...' has no compatible call signatures.
```

**Comment by KacperMadej** [comment]
Hi @jonathan-bird 

I'm not sure why do you even have a path like `node_modules/highcharts-angular/node_modules/` - this shouldn't be a part of this repository and related node module (it's [ignored in this script](https://github.com/highcharts/highcharts-angular/blob/master/.gitignore#L9))

Is the problem caused by the exporting module? Have you tried loading Highcharts modules using `import` or `require`?

**Comment by ivanpetkovic** [comment]
Hi @KacperMadej ,

I'm also getting this error after upgrading my project to Angular 6. I've fixed this problem before using the solution provided above. But now, when I insert into tsconfig:

```
  "files": [
    "node_modules/highcharts-angular/src/app/highcharts-chart.component.ts"
  ]
```

I get the following error: 

```
ERROR in No NgModule metadata found for 'AppModule'.
i ｢wdm｣: Failed to compile.
```

I'm using official wrapper, 'highcharts-angular'. Can you please help and elaborate why we still need to change tsconfig?

**Comment by KacperMadej** [comment]
Hi @ivanpetkovic 

Looks like a general issue with Angular 6 please check:
- https://github.com/angular/angular-cli/issues/10516
- https://github.com/angular/angular/issues/24123
- https://stackoverflow.com/questions/39685179/angular-2-no-ngmodule-metadata-found

**Comment by nagarajbiradar18** [comment]
Hi Team,

I have tried many ways but still I am getting errors in the app.module.js file

**Comment by nagarajbiradar18** [comment]
Hi Team,

I have tried many ways but still I am getting errors in the app.module.js file

1. If 'highcharts-chart' is an Angular component and it has 'runOutsideAngular' input, then verify that it is part of this module.
2. If 'highcharts-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by karolkolodziej** [comment]
@nagarajbiradar18 can you please tell me more about your environment?
You've added comment to a pretty old thread
