### ISSUE TITLE
Loading highcharts modules seems to crash unit tests with Karma + Jasmine

### ISSUE THREAD

**Issue by TitaneBoy** [highcharts/highcharts-angular#101]
Hello everyone... Since I'm trying to use your great Highcharts package, I'm facing on issue when unit testing the component that use Highcharts.

Here is my context:

I have a component (the only one) that use Highcharts. In the Web client, everything is working fine. But When I run unit test on this component, I got an error

![image](https://user-images.githubusercontent.com/15614466/50171716-343f0600-02c1-11e9-86f4-528bbd7c60b3.png)

But it doesn't point on any of my web client components. But When I'm disabling (aka renaming the .spec.ts file) of my component that contains Highcharts), everything works. But as I said, when I'm running all my tests, it doesn't tell that 1 component test failed.

My tests always are launched with Chrome browser. When the tests are launched and fails, when I open the Chrome Dev tools, I can see on Chrome Console the following message:

![image](https://user-images.githubusercontent.com/15614466/50171925-d0690d00-02c1-11e9-84db-597252193926.png)

And When I'm going to the source error, I can see this:

![image](https://user-images.githubusercontent.com/15614466/50171965-ed054500-02c1-11e9-9382-5ec0c9567cc6.png)
And this:
![image](https://user-images.githubusercontent.com/15614466/50171980-f7bfda00-02c1-11e9-89ef-d11a15103713.png)

The code you can see on previous pictures are the Javascript transpilled code. Here is my original typescript file:

![image](https://user-images.githubusercontent.com/15614466/50172162-62711580-02c2-11e9-8d88-1527b1a8d11b.png)

And I what I discovered and understood about this, it's if I disable (or comment) the loading of HighStock and Exporting modules and If I run again the unit tests, everything is passing well: No errors

Here is what I'm doing to make the unit tests works again
![image](https://user-images.githubusercontent.com/15614466/50172405-ffcc4980-02c2-11e9-8f34-13c177c26710.png)

Here is the results:
![image](https://user-images.githubusercontent.com/15614466/50172470-2ee2bb00-02c3-11e9-817f-f4c4586efe3a.png)

If I'm using `StockModule(Highcharts);` and `HC_exporting(Highcharts);`, here is the unit test result
![image](https://user-images.githubusercontent.com/15614466/50172584-66516780-02c3-11e9-95bc-235453c70595.png)

As you can see, 0 failures and unit tests still fail.

As described before, the fail seems to come from loading a module (in my case, I was loading Highstock and exporting modules)

![image](https://user-images.githubusercontent.com/15614466/50172755-bcbea600-02c3-11e9-9e7f-886cb3f49006.png)

Can you help me please to resolve this issue ? 

Here is my package.json dependencies:
```
"dependencies": {
    "@angular/animations": "7.1.3",
    "@angular/cdk": "7.1.1",
    "@angular/common": "7.1.3",
    "@angular/compiler": "7.1.3",
    "@angular/core": "7.1.3",
    "@angular/flex-layout": "7.0.0-beta.19",
    "@angular/forms": "7.1.3",
    "@angular/http": "7.1.3",
    "@angular/material": "7.1.1",
    "@angular/platform-browser": "7.1.3",
    "@angular/platform-browser-dynamic": "7.1.3",
    "@angular/router": "7.1.3",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "bootstrap": "4.1.3",
    "chart.js": "2.7.3",
    "chartjs-plugin-zoom": "0.6.6",
    "core-js": "2.6.0",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "highcharts": "7.0.0",
    "highcharts-angular": "2.3.1",
    "material-design-icons": "3.0.1",
    "ng-event-source": "1.0.14",
    "rxjs": "6.3.3",
    "typescript": "3.1.6",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.11.3",
    "@angular/cli": "7.1.3",
    "@angular/compiler-cli": "7.1.3",
    "@angular/language-service": "7.1.3",
    "@types/chart.js": "2.7.41",
    "@types/jasmine": "3.3.1",
    "@types/jasminewd2": "2.0.6",
    "@types/node": "10.12.15",
    "codelyzer": "4.5.0",
    "jasmine-core": "3.3.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "3.1.3",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "2.0.0",
    "karma-coverage": "1.1.2",
    "karma-coverage-istanbul-reporter": "2.0.4",
    "karma-firefox-launcher": "1.1.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.0",
    "karma-json-reporter": "1.2.1",
    "karma-junit-reporter": "1.2.0",
    "ngx-i18nsupport": "0.17.1",
    "protractor": "5.4.1",
    "ts-node": "7.0.1",
    "tslint": "5.11.0",
    "typedoc": "0.13.0"
  }
```

Thank you in advance for your help.

**Comment by KacperMadej** [comment]
@TitaneBoy 
Thank you for reporting about the problem.
Please try with current Highcharts - 7.0.1.
I wonder - if `stock_1.default` is not a function, then is it `undefined`? or what could it be - could you check?

This is a Highcharts issue and problems about Highcharts should be reported on [Highcharts repo](https://github.com/highcharts/highcharts/issues) - just so we could close reported issues through commits on that repo, and keep all issues related directly to Highcharts in one place. Just an info for the future.

@bre1470
This a general Highcharts issue with TS as far as I know.
Maybe in described situation something is not loaded right?

**Comment by TitaneBoy** [comment]
@KacperMadej I'm sorry about opening this issue not in the right repo. I wasn't sure if it was an highcharts-angular or an highcharts issue since I had this problem in an angular project. If you need to close and/or move this issue in the right repo, feel free to do it.. I will try to be more carefull next time..

Also, about the "stock_1.default" is not a function, I would like to be able to check what it could be but I don't have the javascript transpilled code. It seems to be generated on the go when I run unit tests. I will try to put some breakpoints in chrome devtools to see if I can break before it crashs.. I will give you some news in few hours...

Thanks again for your answer..

**Comment by bre1470** [comment]
Well, it really looks like something is not loading. It might be a problem in the UMD system of the Highcharts modules or in the declarations.
```
(function (factory) {
	if (typeof module === 'object' && module.exports) {
		module.exports = factory;
	} else if (typeof define === 'function' && define.amd) {
		define(function () {
			return factory;
		});
	} else {
		factory(typeof Highcharts !== 'undefined' ? Highcharts : undefined);
	}
}(function (Highcharts) {
```
For me the code above returns clearly a factory function (commonjs & amd) and as a fallback applies modules directly on the Highcharts namespace in the global scope. But I am not sure about the first one, to be ES6 compliant it should have to be `module.exports.default = factory;` I believe.
@jon-a-nygaard 
Do you think, we could do this?
```
factory.default = factory;
module.exports = factory;
```

**Comment by bre1470** [comment]
@TitaneBoy
You could try this:
```
import * as Highcharts from 'highcharts';
import * as StockModule from 'highcharts/modules/stock';
import * as ExportingModule from 'highcharts/modules/exporting';
StockModule(Highcharts);
ExportingModule(Highcharts);
```
Maybe this will not produce errors in the tests. If the tests succeeded, the code probably runs as ES6 in the tests and as ES5 in the browser.

**Comment by TitaneBoy** [comment]
@bre1470 
I've tried your suggestion ...

![image](https://user-images.githubusercontent.com/15614466/50288988-87d26080-0435-11e9-8968-72fb04306a97.png)

but I can't execute tests because it generates these errors:

![image](https://user-images.githubusercontent.com/15614466/50289008-96b91300-0435-11e9-96e3-8de274cdc7a6.png)

![image](https://user-images.githubusercontent.com/15614466/50289037-aa647980-0435-11e9-9c60-7626283e115b.png)

Theses errors seems to be same as described in my other issue #94

**Comment by TitaneBoy** [comment]
@KacperMadej @bre1470 
I was able to break on the line where we load stock module (when starting unit tests) and this is what I got:

![image](https://user-images.githubusercontent.com/15614466/50290890-05e53600-043b-11e9-87ff-d1dc6307c6ed.png)

![image](https://user-images.githubusercontent.com/15614466/50290904-0da4da80-043b-11e9-97fc-eae4621cd2d4.png)

When clicking on the stock.js:9 link, it brings me to this:

`{"object"===typeof module&&module.exports?module.exports=H:"function"===typeof define&&define.amd?define(function(){return H}):H("undefined"!==typeof Highcharts?Highcharts:void 0)}`

![image](https://user-images.githubusercontent.com/15614466/50291122-aa677800-043b-11e9-81a3-e703573eceef.png)


Here is what I have in my watchers:

![image](https://user-images.githubusercontent.com/15614466/50291578-fa930a00-043c-11e9-82fc-168dd21f4112.png)

I hope this will help you to figure out what is happening..

**Comment by TitaneBoy** [comment]
Hello there.. Is there any news/development about this issue ?
Thank you in advance for your answer...

**Comment by TitaneBoy** [comment]
PS: By doing some research, I've discovered that using highcharts@6.2.0, unit tests are not crashing. But when using highcharts@7.0.*, it begins to crash

**Comment by bre1470** [comment]
Hello TitaneBoy,
Thank you for your help! We are preparing a fix for the next Highcharts update. Right now the UMD code is not fitting with the TypeScript declarations. Therefor we will set a default property like seen in your `stock.js:9`.

**Comment by rambabu14** [comment]
@bre1470 ,  I am also getting same issue while loading highstock 7.0.2 version and i didn't find any issue with 6.0.2 version below is my development evnironement
1) karma.config.js
 files: [    ...   {pattern: 'uicoverage/vendor/highstock/7.0.1/highstock.js', included: true},]
2) package,json
{
  "name": "pivotui-test-config",
  "version": "1.0.0",
  "description": "karma + jasmine for unit testing JS code",
  "main": "karma.conf.js",
  "dependencies": {
    "jasmine": "2.5.3",
    "karma": "1.7.1",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.1.0",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-chrome-launcher": "2.0.0",
    "karma-junit-reporter": "1.2.0",
    "karma-htmlfile-reporter": "0.3",
    "requirejs": "2.1.0",
  },
  "devDependencies": {
    "karma-requirejs": "1.1.0"
  },
  "scripts": {
    "JSUnitTests": "karma start config/karma.conf.js"
  },
  "author": "",
  "license": ""
}
Below error getting while running js tests:
runJSTests:
install required node_modules
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN highcharts-angular@2.3.1 requires a peer of @angular/common@^2.0.0-rc.0 || >=2.0.0 but none was installed.
npm WARN highcharts-angular@2.3.1 requires a peer of @angular/core@^2.0.0-rc.0 || >=2.0.0 but none was installed.
npm WARN pivotui-test-config@1.0.0 No repository field.
npm WARN pivotui-test-config@1.0.0 No license field.
delete the existing coverage, ut report folder
Deleting directory C:\GIT\code\Tip\PivotMDAP\uicoverage\reports
running unit tests

> pivotui-test-config@1.0.0 JSUnitTests C:\GIT\code\Tip\PivotMDAP\uicoverage
> karma start config/karma.conf.js

[32m22 01 2019 15:19:20.159:INFO [karma]: [39mKarma v1.7.1 server started at http://0.0.0.0:9876/
[32m22 01 2019 15:19:20.159:INFO [launcher]: [39mLaunching browser PhantomJS with unlimited concurrency
[32m22 01 2019 15:19:20.175:INFO [launcher]: [39mStarting browser PhantomJS
[32m22 01 2019 15:19:21.909:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: [39mConnected on socket _gKnbBazefOPMPeRAAAA with id 67384935
PhantomJS 2.1.1 (Windows 8.0.0) LOG: [36m'JQMIGRATE: Migrate is installed, version 3.0.0'[39m
PhantomJS 2.1.1 (Windows 8.0.0) LOG: [36m'JQMIGRATE: Migrate is installed, version 3.0.0'[39m

[31mPhantomJS 2.1.1 (Windows 8.0.0) ERROR[39m
  Error: Mismatched anonymous define() module: function () {return H(P);}
  http://requirejs.org/docs/errors.html#mismatch
  at uicoverage/node_modules/requirejs/require.js:1733
[31mPhantomJS 2.1.1 (Windows 8.0.0) ERROR[39m
  Error: Mismatched anonymous define() module: function () {return H(P);}
  http://requirejs.org/docs/errors.html#mismatch
  at uicoverage/node_modules/requirejs/require.js:1733

PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0[31m ERROR[39m (1.984 secs / 0 secs)

Do you have any suggestion to fix this issue and what is the version you are planning to fix this issue.

Thanks in advance, 
Thanks,
Rambabu.

**Comment by bre1470** [comment]
We introduced with v7.0.2 the `default` property in the UMD system, see https://github.com/highcharts/highcharts/pull/9846.

This should cover both import variants `import * as MyImport from 'my-import'` and `import MyImport from 'my-import'` for ES6/CommonJS. But it depends on your module system and TypeScript configuration, if you actually can use both syntax.

@rambabu14 
Your problem is different from that, because you use with RequireJS the AMD part and not the ES6/CommonJS part. We did not changed the AMD part in any way.

It looks like a configuration error. Make sure that you load RequireJS as the first script. Search the Internet for `Mismatched anonymous define() module` to get details about the problem.

**Comment by rambabu14** [comment]
Hi @bre1470 ,
Thank you for replying, it works fine when I just revert to version 6.0.2, if it is configuration issue then it should break with 6.0.2 version alos right ?

And i tried to load highstock lazy loading also like below and passed directly when loading spec scripts, but still no luck
{pattern: 'uicoverage/vendor/highstock/7.0.1/highstock.js', **included: false**},
 .

Thanks,
Rambabu.

**Comment by bre1470** [comment]
@rambabu14 
Highcharts v6.0.2 does not have support for AMD, so you are probably using it in the classic way over the global Highcharts object. AMD support was added in v6.1.2.

**Comment by KacperMadej** [comment]
Closed due to inactivity.
