### ISSUE TITLE
Solid Gauge - data labels update on value change but the graphical part is being lost

### ISSUE THREAD

**Issue by DedalusOsX** [highcharts/highcharts-angular#102]
So I've create a <app-gauge> component which receives as input change of value. The component.ts file looks like this.

```
import { Component, OnChanges, Input } from '@angular/core';
import * as Highcharts from 'highcharts';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-gauge',
  templateUrl: './gauge.component.html',
  styleUrls: ['./gauge.component.scss']
})
export class GaugeComponent implements OnChanges, AfterViewInit {
  Highcharts = Highcharts; // required
  chartConstructor = 'chart'; // optional string, defaults to 'chart'
  options: any = {};
  updateFlag = false; // optional boolean
  oneToOneFlag = false; // optional boolean, defaults to false
  runOutsideAngularFlag = false; // optional boolean, defaults to false

  @Input() public si: any;

  constructor(
    private datePipe: DatePipe
  ) {
    this.iniChart();
  }

  ngOnChanges() {
    this.updateFlag = false;

    if(this.si){
      this.options.series[0] = {
        data: [{
            radius: '115%',
            innerRadius: '100%',
            y: this.si
        }]
      }
      console.log(this.options);
    } else {
      this.options.series[0] = {
        data: []
      }
    }
    this.updateFlag = true;
  }

  private iniChart(){
    this.options = {
      chart: {
          type: 'solidgauge'
      },
      pane: {
          startAngle: 0,
          endAngle: 360,
          center: ['50%', '50%'],
          background: {
              outerRadius: '115%',
              innerRadius: '100%',
              backgroundColor: '#191B26',
              borderWidth: 0
          }
      },
      series: [{
        data: []
      }],
      yAxis: {
          min: 0,
          max: 1,
          lineWidth: 0,
          tickPositions: [],
          minorTickInterval: null,
          tickWidth: 0,
          stops: [
            [0.5, {
              linearGradient: {
                x1: 0.5,
                x2: 0.5,
                y1: 0,
                y2: 1
              },
              stops: [
                [0, '#ff5f6d'],
                [1, '#692895']
              ]
            }],
            [1, {
              linearGradient: {
                x1: 1,
                x2: 0,
                y1: 0,
                y2: 1
              },
              stops: [
                [0, '#ff5f6d'],
                [0.5, '#692895'],
                [1, '#0746E2']
              ]
            }]
          ],
      },
      plotOptions: {
          solidgauge: {
              linecap: 'round',
              stickyTracking: false,
              rounded: true,
              dataLabels: {
                  borderWidth: 0,
                  useHTML: true,
                  format: "{point.y:.2f}"
              }
          }
      },
      legend: {
        enabled: false
      },
      tooltip: {
        enabled: false
      }
    }
  }
}
```

And my component.html file looks like this

```
<h6 class="h6" *ngIf="!si">No Data Available</h6>
<highcharts-chart [Highcharts]="Highcharts" [constructorType]="chartConstructor" [options]="options" [(update)]="updateFlag" [oneToOne]="oneToOneFlag"></highcharts-chart>
```
So this is the thing:

I use the HOME component in my app for the routes of following type:

> localhost:4200/registry/:cryptoSymbol
> 
> e.g. localhost:4200/registry/btc
> e.g. localhost:4200/registry/eth

My HOME component uses my app-gauge component. When I change the route from:

localhost:4200/registry/btc

to:

localhost:4200/registry/eth

my si value from component.ts changes. This in turn updates the dataLabel, but my colored gauge is lost. If I refresh the page everything is back to normal, but again if I change the route within the same :cryptoSymbol my solid gauge updates dataLabel but not the gauge itself.

Look at this image 1 behaving right 
<img width="220" alt="screen shot 2018-12-24 at 8 18 24 pm" src="https://user-images.githubusercontent.com/31106393/50403590-29044280-07b9-11e9-93df-49f31e7f4ffd.png">

and image 2 misbehaving on route change.
<img width="220" alt="screen shot 2018-12-24 at 8 19 03 pm" src="https://user-images.githubusercontent.com/31106393/50403580-18ec6300-07b9-11e9-8212-0091fd218c18.png">

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

In general when you are changing URL of a site with a Highcharts chart then each chart's clip-path URL is being updated to refer to the old URL. Here's a similar problem with a suggested solution: https://github.com/highcharts/highcharts/issues/5244#issuecomment-214674124 I'll add a comment in that thread, but please feel free to add your own comment if you would have any info that could help with that issue.
