### ISSUE TITLE
unable to run repo on local , throw error of LICENSE 

### ISSUE THREAD

**Issue by zymr-keshav** [highcharts/highcharts-angular#103]
I tried to clone this library and for that i did this 

git clone <reponame.git>
npm install
npm start -- port 12345 

but it throws errors as below

 

> Copying ./LICENSE to dist/highcharts-angular/LICENSE
> fs.js:1910
>   binding.copyFile(src, dest, flags);
>           ^
> 
> Error: ENOENT: no such file or directory, copyfile '/opt/highcharts-angular/LICENSE' -> '/opt/highcharts-angular/dist/highcharts-angular/LICENSE'
> 

what needs to do for this? I have checked that LICENSE file is there in the repo.

heere is the Tree strcuture

```text
.
├── CHANGELOG.md
├── LICENSE
├── README.md
├── angular.json
├── e2e
├── highcharts-angular
           ├── index.js
           ├── js
           ├── karma.conf.js
           ├── node_modules
           ├── package-lock.json
           ├── package.json
           ├── protractor.conf.js
           ├── src
           ├── tasks
           ├── tsconfig.json
          └── tslint.json
├── CHANGELOG.md
├── karma.conf.js
├── ng-package.json
├── ng-package.prod.json
├── package.json
├── src
├── tsconfig.lib.json
├── tsconfig.spec.json
└── tslint.json



```

**Comment by KacperMadej** [comment]
Hi @zymr-keshav 

Thank you for reporting about the problem.

The script run build before running a server. `dist` folder is not created in your case, probably due to some uncaught error when trying to create new directories and files. Seems like the demo app has some dependencies versions set not strict enough and there's a version mismatch between some dependencies.

After [updating demo to v7](https://github.com/highcharts/highcharts-angular/issues/96) this problem should be resolved.

**Comment by KacperMadej** [comment]
Dependencies are now set precisely, so similar issues should be prevented.
Closing as resolved.
In case you are able to recreate the problem with new version (2.4.0) of the repository please leave a comment and the issue could be reopened.

**Comment by zymr-keshav** [comment]
Thanks for the response. yes, this is working fine with Angular v 7 but I have **Angular 6.1.10** for my project which version of Highchart is compatible with this?

**Comment by KacperMadej** [comment]
The highcharts-angular component is compatible with that Angular version. The repository here is used as a demo app and contains the component. The component usage (with a minimal demo app instructions) is presented in [this documentation section](https://github.com/highcharts/highcharts-angular#hello-world-demo). The component itself can be obtained through NPM, build with this repository and base files are [here](https://github.com/highcharts/highcharts-angular/tree/master/highcharts-angular/src/lib).
