### ISSUE TITLE
Passing data into highcharts in the HTML tag as a directive?

### ISSUE THREAD

**Issue by tonym99** [highcharts/highcharts-angular#111]
Is there any way to pass data into highcharts via an HTML directive in the highcharts-chart tag?  Something like this:

<highcharts-chart [mydata]="1234">
</highcharts-chart>

Thanks

**Comment by KacperMadej** [comment]
Hi @tonym99 

There's [`[options]="chartOptions"`](https://github.com/highcharts/highcharts-angular#options-details), but if you require more dedicated way then I suggest creating another component that will wrap around the highcharts-angular component to pass on the data into the correct part of chartOptions.

This is not a bug. [For technical support please use tech support channels.](https://github.com/highcharts/highcharts-angular#help-and-faq)
