### ISSUE TITLE
Highcharts error #17 while creating areasplinerange in angular 6

### ISSUE THREAD

**Issue by vikasnale** [highcharts/highcharts-angular#112]
I am creating **areasplinerange**  using this library but i am not able to plot it as i am getting error Highcharts error #17 asking to use highcharts-more.js file.  

My object i pass works in jfiddle  https://jsfiddle.net/vikasnale/f0cxgqv7/  
but not in angular 6   https://next.plnkr.co/edit/hXMhHJMFtymZrmOi

But i am not able to figure out how to solve this. Please guide

**Comment by KacperMadej** [comment]
Hi @vikasnale 

The error is about missing function type. The function type is defined in the highcharts-more file as you could see in the HTML section of the demo.

To resolve the problem add missing highcharts-more file.
Closing as this is quite common mistake (missed file), but if this will not resolve the problem please leave a comment and the issue could be reopened.

**Comment by vikasnale** [comment]
Hi @KacperMadej ,
Thanks for quick feedback.  I tries various ways to add highchart-more file in my code, but i was not able to use it. I must be missing some minute thing. Can you please guide me how can i add that file. It will be great-full if you could advice me some pointer to work it out.

Thanks a lot again.

**Comment by KacperMadej** [comment]
> I'll open an enhancement suggestion on main Highcharts repo about this.

https://github.com/highcharts/highcharts/issues/9892

**Comment by vikasnale** [comment]
@sebastianbochan, Thanks a lot.

It worked like charm :)

**Comment by sorb999** [comment]
@sebastianbochan @vikasnale  it works with normal build i.e. `ng build`. But it is not working with production build. I am getting same error after `ng build --pod`.

**Comment by KacperMadej** [comment]
@sorb999 
Please see a similar issue for possible solution - https://github.com/highcharts/highcharts-angular/issues/146
