### ISSUE TITLE
Issue with update flag

### ISSUE THREAD

**Issue by sjerman** [highcharts/highcharts-angular#116]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
Have a  'rolling' data series with max of 5 points that are updated every 5 secs. Using update flag to signal change ... however chart is not updated once the data array is full. See following code:

```
    this.subscription = this.apInfo.subscribe(
      d => {
        const data = this.sparkLineBase['series'][0]['data'] as number[];
        data.push(d);
        if (data.length > 5) {
          data.shift();
        }
        this.updateFlag = true;
      }
    );
```
 The update flag is reset each time, but the graph is not changed.

### Expected behavior
Chart should update each time a point is changed.

### Setup used
Angular CLI: 7.1.4
Node: 8.9.
"highcharts": "^7.0.1",
"highcharts-angular": "^2.4.0"

**Comment by KacperMadej** [comment]
Hi @sjerman 

Thank you reporting about the problem.

Please add a live demo or provide any other way to recreate the problem. The code you have provided so far if not enough for me to recreate the problem.

Have you tried to recreate the problem with a minimal chart configuration? A minimal live demo would best, but any demo will do for a start.

**Comment by hsunesara786** [comment]
Do we have an addPoint option on this wrapper. I am trying to update charts in realtime.
