### ISSUE TITLE
Licence and doubts about disabled credits

### ISSUE THREAD

**Issue by rabindranathfv** [highcharts/highcharts-angular#117]
i have a doubt about disabled credits, if i want to use this wrapper of highchart for angular and use 

```
credits: {
            enabled: false
        }
```
i want hide the signature of highchart.com on charts for web App, is it necessary buy the licence of highchart?

**Comment by KacperMadej** [comment]
Hi @rabindranathfv 

You could disable the credits for highcharts.com, just remember about attribution required by free license.

A longer answer:

https://shop.highsoft.com/highcharts says:

> If you are a non-profit company, or use our products for personal use, you may enjoy our software for free under a Creative Commons (CC) Attribution-NonCommercial licence

CC license mentioned there says (among other things):

> Under the following terms: Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

Based on that, you don't have to use credits to fulfill the attribution requirement - credits are enabled by default for you convenience.

Notice: in case of questions about license you should contact [Highcharts Sales Department](https://shop.highsoft.com/contact)
