### ISSUE TITLE
how to split the data set into ohlc and volume in angular

### ISSUE THREAD

**Issue by aravind-ui** [highcharts/highcharts-angular#119]
Hi,

I'm trying to implement highstock chart in angular with ohlc and volume.
Can you suggest to split it the ohlc and volume?

**Comment by KacperMadej** [comment]
Hi @aravind-ui 

For general technical support please contact through support channels https://www.highcharts.com/blog/support/

What do you mean by split the ohlce and volume? Do you mean how to process data? What's the data format then? Do you mean split the chart? Use multiple y axes with different top and height options.

This is not a wrapper bug, so please continue with technical support through the provided link.
