### ISSUE TITLE
Unable to load pyramid chart

### ISSUE THREAD

**Issue by shahmeee** [highcharts/highcharts-angular#123]
This is the error im getting in console. am i missing anything ?

```
Highcharts Error #17
The requested series type does not exist
This error happens when you are setting chart.type or series.type to a series type that isn't defined in Highcharts. A typical reason may be that your are missing the extension file where the series type is defined, for example in order to run an arearange series you need to load the highcharts-more.js file.
```

component page

import * as Highcharts from "highcharts";

this.chartOptions = {
      chart: {
        type: 'pyramid'
      },
      title: {
        text: 'Sales pyramid',
        x: -50
      },
      plotOptions: {
        series: {
          dataLabels: {
            enabled: true,
            format: '<b>{point.name}</b> ({point.y:,.0f})',
            softConnector: true
          },
          center: ['40%', '50%'],
          width: '80%'
        }
      },
      legend: {
        enabled: false
      },
      series: [{
        name: 'Unique users',
        data: [
          ['Website visits', 15654],
          ['Downloads', 4064],
          ['Requested price list', 1987],
          ['Invoice sent', 976],
          ['Finalized', 846]
        ]
      }]
    }

html page

<highcharts-chart
  [Highcharts] = "highcharts"
  [options] = "chartOptions"
  style = "width: 100%; height: 400px; display: block;">
</highcharts-chart>

**Comment by KacperMadej** [comment]
Hi @shahmeee 

The series type module is missing.

You could check what modules are required e.g. by checking a demo of the series you want to use - https://www.highcharts.com/demo/pyramid (in the JSFiddle demo, HTML sections has all required files listed).

Then load the required files based on the docs here: https://github.com/highcharts/highcharts-angular#to-load-a-module

This is quite common issue, so I'll close it now, but the issue could be reopened if needed.

**Comment by AbramsM1A2** [comment]
The codepen and jsfiddle are still outdated, please add the missing script 
`<script src="https://code.highcharts.com/modules/series.js"></script> `
