### ISSUE TITLE
labels.items doesn't refresh

### ISSUE THREAD

**Issue by L-Steffen** [highcharts/highcharts-angular#126]
I have an issue with the labels.items of my Highcharts instance. I just don't manage to get them refreshed.
I have a graph that can be filtered through the back-end. When I get the new generated data i update the data in my chartOptions which I use in the html as  `[options]="chartOptions"`. 

The chartOptions are instanciated from my default class like this: `this.chartOptions = new GraphConfigSeqAtteptedVsAchived().chartOptions; `

The Class looks like this:
`import * as Highcharts from 'highcharts';

export class GraphConfigSeqAtteptedVsAchived{
	public chartOptions: any; 

	constructor(){
		this.chartOptions = {
		chart: {
			height: 600,
			width: 620,
			events:{load: function(){
	            this.myTooltip = new Highcharts.Tooltip(this, this.options.tooltip);         
	        	}
	     	},
			backgroundColor: 'transparent',
		},
		credits: {
			text: 'charname',
        	href: ''
		},
		labels: {
	        
	    },
	    exporting:{
            chartOptions:{
                title: {
                    text:'not set',
                    style:{
						color: '#000000'
					},
					margin: 0
                }
            }
        },
        tooltip: {
            enabled: false
        },
		xAxis: {
			min: -10,
			max: 0,
			width: 535,
			title: {
				text: 'Rainfall (mm)',
				style: {
					fontWeight: "bold",
					color: '#000000'
				}
			},
			reversed: true,
			tickInterval: 1
		},
		yAxis: {
			min: -10,
			max: 0,	
			title: {
				text: 'Rainfall (mm)',
				style: {
					fontWeight: "bold",
					color: '#000000'
				}
			},
			reversed: true,
			tickInterval: 1
		},
		title: {
			text: ' as',
			margin: 0,
			style:{
				color: 'transparent'
			}
		},
		legend: {
			layout: 'vertical',
			align: 'left',
			verticalAlign: 'top',
			x: 100,
			y: 90,
			floating: true,
			backgroundColor: '#FFFFFF',
			borderWidth: 1,
			navigation: {
				enabled: false
			}
		},
		plotOptions: {
			scatter: {
				stickyTracking: false,
                allowPointSelect: true,
				marker: {
					radius: 3,
					states: {
						hover: {
							enabled: true,
							lineColor: 'rgb(100,100,100)'
						}
					}
				},
				tooltip: {
					headerFormat: '<b>{series.name}</b><br>',
					pointFormat: '',
					hideDelay: 500
				},
				symbol: "circle",
                events: {

                    mouseOut: function() {
                        this.chart.myTooltip.hide();
                        this.chart.myTooltip.options.enabled = false;
                    },
                    mouseOver: function() {
                        if(this.halo) {
                            this.halo.attr({
                               'class': 'highcharts-tracker' 
                            }).toFront();   
                        }
                    },
                    click: function(event) {
                        this.chart.myTooltip.options.enabled = true;
                        this.chart.myTooltip.refresh(event.point, event);
                    }                  
                }  
			},
			line:{
				events: {
	            	legendItemClick: function () {
	                	return false; 
		            }
		        }
			},
            series:{
				allowPointSelect: true
            }

		},
		series: [{
			type: 'line',
			data: [[30, 30], [-30, -30]],
			marker: {
				enabled: false
			},
			states: {
				hover: {
					lineWidth: 1
				}
			},		
			showInLegend: false,	
			color: "rgba(0, 0, 0, 0.6)",
			enableMouseTracking: false
		},{
			type: 'line',
			data: [[30, 29.5], [-29.5, -30]],
			marker: {
				enabled: false
			},
			states: {
				hover: {
					lineWidth: 0
				}
			},			
			showInLegend: false,
			dashStyle: 'ShortDash',
			color: "rgba(125, 162, 159, 0.35)",
			enableMouseTracking: false
		},{
			type: 'line',
			data: [[29.5, 30], [-30, -29.5]],
			marker: {
				enabled: false
			},
			states: {
				hover: {
					lineWidth: 0
				}
			},
			showInLegend: false,
			dashStyle: 'ShortDash',
			color: "rgba(125, 162, 159, 0.35)",
			enableMouseTracking: false
		},{
			type: 'line',
			data: [[29, 30], [-30, -29]],
			marker: {
				enabled: false
			},
			states: {
				hover: {
					lineWidth: 0
				}
			},
			showInLegend: false,
			dashStyle: 'ShortDash',			
			color: "rgba(197, 144, 161, 0.35)",
			enableMouseTracking: false
		},{
			type: 'line',
			data: [[30, 29], [-29, -30]],
			marker: {
				enabled: false
			},
			states: {
				hover: {
					lineWidth: 0
				}
			},
			showInLegend: false,
			dashStyle: 'ShortDash',
			color: "rgba(197, 144, 161, 0.35)",
			enableMouseTracking: false
		}]
	}
	}
}`

The generated data is in the typescript dynamically added and all of that works just fine. Everything is refreshed after I set the updateFlag for `[(update)]="updateGraph"`. The axis titles are also fine.

The only thing that's not refreshed for me are the labels i dynamically added to the chart like this:
`let labelTotalNumberOfEyes = {
                    html : this.translate.instant('GRAPHS.TOTAL_NUMBER_OF_EYES') + ': ' + (scatterSeries.data.length + scatterSeriesRetreatment.data.length),
                    style : {
                        left : '330px',
                        top : '368px',
                        fontSize : '14px',
                        backgroundColor: '#FFFFFF',
                        borderWidth: 1,
                    }
                }  
                this.chartOptions.labels.items.push(labelTotalNumberOfEyes);`

Does someone have any idea what I'm might doing wrong? I don't see any further option than just setting this update flag and it works fine for everything but the labels. 

Please let me know if you're missing any information.

Thanks in advance.

**Comment by L-Steffen** [comment]
Would it maybe be an option to take out the update part in my project from your method updateOrCreateChart and just recreate the chart always or do you see issues with that approach?

`
updateOrCreateChart() {
    if (this.chart && this.chart.update) {
      this.chart.update(this.optionsValue, true, this.oneToOne || false);
    } else {
      this.chart = (this.Highcharts as any)[this.constructorType || 'chart'](
        this.el.nativeElement,
        this.optionsValue,
        this.callbackFunction || null
      );

      // emit chart instance on init
      this.chartInstance.emit(this.chart);
    }
  }
`

**Comment by KacperMadej** [comment]
Hi @L-Steffen 

Used chart.update method should work with all and any updates, so if anything is not working then it might be a bug in Highcharts.

Are you able to recreate the problem in a pure JS demo with initial chart options and later called chart.update with new options? If not, then please at least share the minimal options set for init and update that are causing the problem.

**Comment by L-Steffen** [comment]
@KacperMadej thank you for your feedback. I put that topic into a sandbox to reproduce it. As you can see it's a minimal setup in which a label item is added to the chart option and then change the text on the button click. The chart is correctly updated but the changed label not. You can find that example here:  https://codesandbox.io/s/l22jr69wjq

I used another angular component before but at that time I was on angular 4 with an older version of Highcharts. With that version it worked fine. After upgrading Highcharts to 7.0.3, angular to 6.1.10 and change to your in general really good wrapper this problem occured. The axis and series are updated just fine but the labels not.

**Comment by KacperMadej** [comment]
This looks like a general Highcharts problem and it's reported here: https://github.com/highcharts/highcharts/issues/10429

I'll close this issue as the one on main Highcharts repo stays open and awaits to be resolved.
