### ISSUE TITLE
Dynamic Chart inside ngFor

### ISSUE THREAD

**Issue by xts-velkumars** [highcharts/highcharts-angular#128]
Good day, 

I need to draw a line chart inside ngFor, how i can able to bind different chart data.

```
<div *ngFor="let timeSheet of  timeSheetList">            
        <div fxLayout="row" class="mar-top-20 apr-chart-container">
                      <highcharts-chart [Highcharts]="highcharts"
                                        [constructorType]="chartConstructor"
                                        [options]="chartOptions"
                                        [callbackFunction]="chartCallback(highcharts, timeSheet)"
                                        [(update)]="updateFlag"
                                        [oneToOne]="oneToOneFlag"
                                        [runOutsideAngular]="runOutsideAngularFlag"
                                        style="width: 480px; height: 120px; display: block;"></highcharts-chart>
      </div>
</div>
```

**Comment by KacperMadej** [comment]
Hi @xts-velkumars 

How about binding chart's options to data based on the *ngFor variables or it's iterator?
Now you have `[options]="chartOptions"`, so it could be something like `[options]="chartOptions[i]"` where `i` is the iterator, or `[options]="timeSheet.chartOptions"`.

In case of any problems you could create a live demo, so I could check for errors.

**Comment by xts-velkumars** [comment]
@KacperMadej 

Could you please give me more details about how the chartOptions needs to defined. 

For now I'm getting below data from server

"timeSheetChartData": [
          {
            "xAxis": "TS0025",
            "yAxis": 28
          },
          {
            "xAxis": "TS1884",
            "yAxis": 12
          },
          {
            "xAxis": "TS2006",
            "yAxis": 32
          },
          {
            "xAxis": "TS0356",
            "yAxis": 14
          },
          {
            "xAxis": "TS0874",
            "yAxis": 34
          },
          {
            "xAxis": "TS1321",
            "yAxis": 15
          }
        ]

**Comment by xts-velkumars** [comment]
@KacperMadej 

I have created a demo as well, you can play around

 (https://stackblitz.com/edit/angular-f7wofv)

**Comment by KacperMadej** [comment]
Chart options are explained here: https://github.com/highcharts/highcharts-angular#options-details
You have a chart with the options, so next step is just to copy it and modify - then you will have multiple options sets.

You are loading data in the loop using `timeSheet.timeSheetTableData`, so you could do the same for the charts. Store the chart options in each of the `timeSheet`s and you will be able to load in the same way.

I'm not sure what do you want to do with the `timeSheetChartData` from your last comment, but if you will edit the chart options set with that data and then store it on `timeSheet`s you will be able to apply the chart options in the Angular loop.

**Comment by xts-velkumars** [comment]
@KacperMadej 

Thanks for your suggestion, it works as excepted.
