### ISSUE TITLE
How can I update the chart data.

### ISSUE THREAD

**Issue by Vigor111** [highcharts/highcharts-angular#13]

**Comment by KacperMadej** [comment]
Chart's data can be updated by changing the options object in a way that it will be picked up by Angular - like [in this demo](https://github.com/highcharts/highcharts-angular/blob/master/src/app/app.component.ts#L50).

If a change is nested then there's `update` flag to force update, explained here (number 5):
https://github.com/highcharts/highcharts-angular#options-details and a demo is [here](https://github.com/highcharts/highcharts-angular/blob/master/src/app/app.component.ts#L62-L63).

We are trying to keep github for bug. You can contact us through any other support channel - e.g. e-mail: support@highcharts.com.
More info at https://www.highcharts.com/support

**Comment by Vigor111** [comment]
Thanks for your answer

**Comment by montecristo91** [comment]
Thank you, I was looking everywhere for the answer.
