### ISSUE TITLE
Tilemap invert is not working

### ISSUE THREAD

**Issue by fil-forti** [highcharts/highcharts-angular#131]
### Describe the bug
I am creating the tilemap as in the example for the US population (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/honeycomb-usa/), but the result is a map which has x and y inverted.

### Expected behavior
The expected behavior is that setting `inverted: true` will show the map as in the example, but changing the value doesn't affect the result. 

#### Steps required to recreate the problem in the demo:
```
import * as Highcharts from "highcharts";
import MapModule from "highcharts/modules/map";
import TileMapModule from "highcharts/modules/tilemap";

MapModule(Highcharts);
TileMapModule(Highcharts);

export class TileMapComponent implements OnChanges, OnInit {

   Highcharts: typeof Highcharts = Highcharts;
   options: Highcharts.Options = {
      chart: {
        type: "tilemap",
        height: "100%"
        inverted: true
      },
      ...
   }
 
```
### Setup used
```
 "highcharts": "^7.0.3",
 "highcharts-angular": "^2.4.0",
```

Am I using a wrong configuration, or is there a bug within the tilemap options? Thank you

**Comment by pawelfus** [comment]
Hi @fil-forti 

You posted on our bug tracker. If you have questions, please contact with us by email or use our forum, see details: https://www.highcharts.com/blog/support/
