### ISSUE TITLE
Data not displayed in ColumnRange graph

### ISSUE THREAD

**Issue by sebcaps** [highcharts/highcharts-angular#132]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
Trying to implement a column range graph, I can see plot area, series on X axis but not the data.
module `ColumnRange `is imported from` highcharts-more`
### Expected behavior
Data are displayed

### Demo
[Stackblitz](https://stackblitz.com/edit/angular-adpgpc?file=src%2Fapp%2Fgraph.component.ts)

**Comment by pawelfus** [comment]
Hi @sebcaps 

There should be `chartOptions.series.type` or `chartOptions.chart.type`, not just `chartOptions.type`, see: https://stackblitz.com/edit/angular-laa1vk?file=src/app/graph.component.ts

**Comment by sebcaps** [comment]
My bad 😕 !
Thx for the help. Prb solved.

**Comment by pawelfus** [comment]
No problem :) Good luck!
