### ISSUE TITLE
when I use the colorAxis option in the heatmap chart, the 'colorAxis' can not work! My highcharts-angular version is 

### ISSUE THREAD

**Issue by a524631266** [highcharts/highcharts-angular#133]
My version follows:
"highcharts-angular": "^2.4.0",
"highcharts": "^7.0.3",

Cannot show colorAxis in the chart!

my options:
```js
  chart: {
        type: 'heatmap',
        // inverted: true,
        backgroundColor: 'rgba(0,0,0,0)',
        zoomType: 'x',
        panKey : 'ctrl',
    },
    colorAxis: {
        accessibility: {
            enabled : true,
        },
        stops: [
            [0, '#3060cf'],
            [0.5, '#fffbbc'],
            [1, '#c4463a']
        ],
        className: 'heatmaplegend',
        visible: true,
    },
  title: {
        text: null,
        align: 'center',
        style: {
            fontSize: '16px',
            fontWeight: 'bold',
            color: 'black'
        }
    },
legend: {
        y: 20,
    },
xAxis: {
        categories: [],
        text: null,
},
series: [{
        data: [],
        borderWidth: 0,
        colsize: 1, // one day
        turboThreshold: Number.MAX_VALUE,
}]
```

**Comment by KacperMadej** [comment]
Hi @a524631266 

Please check if you have loaded files required to display the colorAxis, like Highmaps or heatmap module or map module.

If this doesn't resolve you problem please add Highcharts instance config (files loaded and initialized for Highcharts) and in case you have any errors in browser console, please share them.

**Comment by a524631266** [comment]
> Hi @a524631266
> 
> Please check if you have loaded files required to display the colorAxis, like Highmaps or heatmap module or map module.
> 
> If this doesn't resolve you problem please add Highcharts instance config (files loaded and initialized for Highcharts) and in case you have any errors in browser console, please share them.

I have solved this problem by  initialling the config into the **Component Class:**
```js     
chartOptions = {
      chart: {
        type: 'heatmap',
        backgroundColor: 'rgba(0,0,0,0)',
      },
      colorAxis: {
           .....
      },
      legend: {
        enabled: true,
        // y: 20,
        },
      }
     
     updateChart(){
      new HeatmapselectorOption(this).getHichartOptionFromInitCaseInfo(data));
    }

```
,in html: 
    ```  <highcharts-chart [options]="chartOptions" .../>```

in HeatmapselectorOption.ts
```js      
chart: {
        type: 'heatmap',
        // inverted: true,
        backgroundColor: 'rgba(0,0,0,0)',
        zoomType: 'x',
        panKey : 'ctrl',
    },
    colorAxis: {
        accessibility: {
            enabled : true,
        },
        stops: [
            [0, '#3060cf'],
            [0.5, '#fffbbc'],
            [1, '#c4463a']
        ],
        className: 'heatmaplegend',
        visible: true,
    },
  title: {
        text: null,
        align: 'center',
        style: {
            fontSize: '16px',
            fontWeight: 'bold',
            color: 'black'
        }
    },
legend: {
        y: 20,
    },
xAxis: {
        categories: [],
        text: null,
},
series: [{
        data: [],
        borderWidth: 0,
        colsize: 1, //one day
        turboThreshold: Number.MAX_VALUE,
}]
```
as before, i only use  colorAxis in another class from HeatmapselectorOption.ts  which offer to other charts as options. 

That makes me very confused。

**Comment by KacperMadej** [comment]
> I have solved this problem

Good new, thank you for sharing your solution. The problem is resolved, so the issue will be closed.

I could try to make more of this, but I still don't have answers from my previous comment and there's no context for the `new HeatmapselectorOption(this).getHichartOptionFromInitCaseInfo(data));`, so this will be all unless new comments will show up.
