### ISSUE TITLE
issue on implementing y axis scroll bar with highstock.js

### ISSUE THREAD

**Issue by mohideensameer** [highcharts/highcharts-angular#136]
When we implement scrollbar for yAxis in Highstock, 0 axis is not getting aligned for both y - primary & secondary axis. Is there any way to resolve the issue.
**JSFiddle:** https://jsfiddle.net/eht0grm1/1/

**Comment by KacperMadej** [comment]
Hi @mohideensameer 

Thank you for reporting about the problem.

The problem is a general Highstock issue, so I have reported it in the main Highcharts repository's issues list: https://github.com/highcharts/highcharts/issues/10618
