### ISSUE TITLE
How to refresh the network graph when the data gets updated?

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [highcharts/highcharts-angular#139]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
I am able to show the network graph in the UI. But when the data gets updated, i am not seeing any changes in the graph. There are some unrelated issues i was getting. I also used the update attribute to update the data, but there is no use.

### Expected behavior
The graph should render as per the updated data when we pass.

### Demo
Please provide live demo of the problem or provide any other way to recreate the problem.

#### Steps required to recreate the problem in the demo:
1. ...

### Setup used
 - NodeJS version ... Latest LTS
 - Angular version ... Latest
 - TypeScript version ... Latest
etc.

**Comment by KacperMadej** [comment]
Hi @rajeshwarpatlolla 

Please provide live demo of the problem or provide any other way to recreate the problem.

**Comment by EmilienRamos** [comment]
Hey !
I'm using highcharts-angular and my `series` array comes from a parent component.

I pass my datas via an Input(), who fill a behaviorSubject.

Each 30s, my series are updated.
I need the chart to be updated in consequences.

Here's my code :
```typescript
Highcharts: typeof Highcharts = Highcharts;

chartOptions: Highcharts.Options;

updateFlag = true;

@Input()
get series(): any[] {
    return this.series$.value;
}
set series(value) {
    this.series$.next(value);
}

/** Series BehaviorSubject */
series$ = new BehaviorSubject<any[]>(null);


ngOnInit() {
    this.chartOptions = {
      chart: {
        type: 'variablepie',
      },
      tooltip: {
        pointFormat: `
          <span>{point.name}</span><br />
          <span>{point.percentage:.1f}% - {point.y}</span>
          `,
      },
      plotOptions: {
        variablepie: {
          size: '85%',
          allowPointSelect: true,
          colors: ['red', 'blue, 'green],
        }
      },
      series: [{
        size: '85%',
        zMin: 0,
        type: 'variablepie',
        data: []
      }],
    };

    this.series$.subscribe(series => {
      this.chartOptions.series[0].data = series;
      Highcharts.chart(this.chartOptions).update(this.chartOptions);
    });
}
```

This is my .html file .html :
```html
<highcharts-chart *ngIf="hasSeries"
    style="width: 100%; height: 400px; display: block"
    [Highcharts]="Highcharts"
    [(update)]="updateFlag"
    [options]="chartOptions">
  </highcharts-chart>
```

Unfortunately, my chart is never display.
I'm getting this error : `www.highcharts.com/errors/13` - `Rendering div not found
`

Do you have an idea of why I'm getting this ?

**Comment by KacperMadej** [comment]
Hi @EmilienRamos 

I'm unsure what could be the source of the problem here without debugging the problem and testing possible solutions first. In general usage of manual chart update and creating the chart manually while the wrapper is being used will cause desynchronization of chart options and component / wrapper options, and might cause unexpected behavior.

Please contact [technical support](https://www.highcharts.com/blog/support/) with a working demo.
You case might be similar, but that this stage it needs further investigation.
The original case will be now closed due to inactivity.
If after contacting technical support you will find out that this is a bug in the wrapper then please open a new issue ticket.
