### ISSUE TITLE
Fail to compile in AOT

### ISSUE THREAD

**Issue by tleveque23** [highcharts/highcharts-angular#14]
Your own demo app work well with a simple ng serve, but with --aot it does not compile:

```
ERROR in src/app/app.component.html(46,7): : Property 'hcCallback' does not exist on type '{ hcOptions: { title: { text: string; }; subtitle: { text: string; }; plotOptions: { series: { po...'.
  Property 'hcCallback' does not exist on type '{ hcOptions: { title: { text: string; }; subtitle: { text: string; }; series: ({ type: string; da...'.
```

Same result if I update all the dependencies to the latest versions.

**Comment by KacperMadej** [comment]
Thank you for reporting @tleveque23 .

I'll check this and will try to resolve. If you have any more info then I would be thankful.

**Comment by KacperMadej** [comment]
When running `ng serve --aot` will check types based on all elements of the array. Those elements where different - only first one had the `hcCallback` property. Adding the prop to other elements of the `charts` array resolves the problem.
