### ISSUE TITLE
grammar mistake

### ISSUE THREAD

**Issue by kushalatreya** [highcharts/highcharts-angular#140]
### Describe the bug
> Inside: Getting started --> Installing section, 
Right side names, in double quotes, are just names of variables you are going to set next, so you could name then whatever you like. 

### Expected behavior
Right side names, in double quotes, are just names of variables you are going to set next, so you could name them whatever you like. 
### Demo
replace the word (then) to (them).
![Capturethen](https://user-images.githubusercontent.com/17897958/57217915-998b5d80-6ffc-11e9-9a48-3f932c850aa2.PNG)

**Comment by KacperMadej** [comment]
Hi @kushalatreya 

Thank you for reporting about the typo.
