### ISSUE TITLE
 SolidGauge with marker or indicator

### ISSUE THREAD

**Issue by EitanD1** [highcharts/highcharts-angular#142]
hi
I made this fiddle https://jsfiddle.net/uvew9zc0/
based on this forum topic
https://www.highcharts.com/forum/viewtopic.php?t=40754

it works fine with jquery. i want it on an angluar(7) project.
i added pInt function which is missing in highcharts.d.ts, but i could'nt find a proper way to add `Highcharts.seriesTypes.gauge.prototype.translate =function().....`
first- because "Property 'seriesTypes' does not exist on type 'HighCharts'"
second - i'm not sure where to place the code. 
(iv'e read this post https://www.highcharts.com/docs/advanced-chart-features/typescript and even this demo didn't work

```
import * as Highchart from 'highcharts';

Highcharts.Point.prototype.highlight = function (event) {
    event = this.series.chart.pointer.normalize(event);
    this.onMouseOver(event);
    this.series.chart.tooltip.refresh(this);
    this.series.chart.xAxis[0].drawCrosshair(event, this);
};
```
)

thanx

**Comment by KacperMadej** [comment]
Hi @EitanD1 

Thank you for reporting about the issue.

The code you have added (or would like to use, but still was added) could be resolved as a plugin (you might want to add additional .dts file for better TS flow) or as a wrapper - both documented in the wrapper docs: https://github.com/highcharts/highcharts-angular#to-load-a-wrapper
