### ISSUE TITLE
 Do not take some data from "lang"

### ISSUE THREAD

**Issue by jhonnyperezm** [highcharts/highcharts-angular#143]
Hello, I am trying to change some data of my graphic, but in **lang** it does not take the changes
```
      lang: {
        months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 
         'Octubre', 'Noviembre', 'Diciembre'],
        weekdays: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        shortMonths: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        rangeSelectorFrom: "Desde",
        rangeSelectorTo: "Hasta",
        rangeSelectorZoom: "Período",
      },
```

      <highcharts-chart style="width: 100%; display: block" [Highcharts]="Highcharts" [constructorType]="'stockChart'"
        [options]="chartOptions">
      </highcharts-chart>

I do not take the changes

**Comment by KacperMadej** [comment]
Hi @jhonnyperezm 

Thank you for contacting us about the problem.

The `lang` is global and should be set as explained in here: https://github.com/highcharts/highcharts-angular#to-use-setoptions
