### ISSUE TITLE
Bundle size with highstock

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts-angular#145]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
In my app I'm using charts from both basic highcharts and highstock. As far as I know the latter includes the former. So in my bundle I get this picture:
![Screenshot_2019-06-07_17-44-05](https://user-images.githubusercontent.com/25563221/59112746-4d5d7100-894c-11e9-921a-6ea19eed7bf7.png)

And even if I disable all of charts but one from highstock I get this overweight bundle anyway.

### Expected behavior
Ability to manage imports and eventual bundle should be more flexible

### Setup used
 - Highcharts - 7.1.1
 - highcharts-angular - 2.4.0
 - Angular - 8.0.0

**Comment by KacperMadej** [comment]
Hi @diogen737 

Thank you for reporting about the problem.

Highstock = Highcharts + stock module,
so if you have Highcharts and stock module then you don't need Highstock and if you have Highstock you don't need to load Highcharts (nor stock module).

The dependency is better described in general Highcharts documentation in here: https://www.highcharts.com/docs/getting-started/installation 

If you are having files that you are not using in your bundle then maybe something wrong is with the software that creates the bundle or the files are used somewhere that you have missed. The wrapper expects Highcharts to be loaded, so it doesn't load the Highcharts package at all.

**Comment by diogen737** [comment]
@KacperMadej I tried to import all of the Highcharts instances from highcharts/highstock but the bundle remained the same

**Comment by diogen737** [comment]
@KacperMadej never mind, solved it with webpack:
```
const webpack = require('webpack');
module.exports = {
    plugins: [
        new webpack.NormalModuleReplacementPlugin(
            /^highcharts$/,
            'highcharts/highstock'
        )
    ]
};
```
You can close the issue
