### ISSUE TITLE
ng build --prod -> ERROR Error: Highcharts error #17

### ISSUE THREAD

**Issue by Robinyo** [highcharts/highcharts-angular#146]
### Describe the bug
When I build a non-production version of my application:

```
ng build
```

It works as expected:

![image](https://user-images.githubusercontent.com/12203540/59481909-b93e5d00-8ea9-11e9-88ed-eb738c3f4295.png)

**Demo**
Firebase Hosting: [Serendipity](https://serendipity-f7626.firebaseapp.com)

**Source Code**
GitHub: [Serendipity](https://github.com/Robinyo/serendipity)

When I build a production version of my application:

```
ng build --prod --source-map
```

At runtime I receive the following error:

![Screen Shot 2019-06-14 at 13 12 38](https://user-images.githubusercontent.com/12203540/59481217-bf7f0a00-8ea6-11e9-9f21-4beb047e5113.png)

### Expected behaviour
I followed the installation steps as per the highcharts-angular README.md.

I installed:

```
npm install highcharts-angular --save
npm install highcharts --save
```

I imported the `HighchartsChartModule`:

See: [dashboard-widgets.module.ts](https://github.com/Robinyo/serendipity/blob/master/projects/dashboard-widgets/src/lib/dashboard-widgets.module.ts)

I imported `Highcharts`:

See: [funnel-chart.component.ts](https://github.com/Robinyo/serendipity/blob/master/projects/dashboard-widgets/src/lib/highcharts-angular/components/funnel-chart/funnel-chart.component.ts)

```
import { Component, OnInit } from '@angular/core';

import * as Highcharts from 'highcharts';
import funnel from 'highcharts/modules/funnel';

funnel(Highcharts);

// import HC_more from 'highcharts/highcharts-more';
// HC_more(Highcharts);

@Component({
  selector: 'widget-funnel-chart',
  template: `
    <highcharts-chart
      [Highcharts]="Highcharts"
      [options]="chartOptions"
      style="width: 100%; height: 100%; display: inline-block;">
    </highcharts-chart>
  `,
  styles: []
})

...

```

### Demo
Firebase Hosting: [Serendipity](https://serendipity-f7626.firebaseapp.com)

#### Setup

Angular 7.2.15
"highcharts": "^7.1.2"
"highcharts-angular": "^2.4.0"
"typescript": "^3.2.4"

See: [package.json](https://github.com/Robinyo/serendipity/blob/master/package.json)

**Comment by baskaranr** [comment]
@Robinyo Could you please try the solution provided in below ticket.
https://github.com/highcharts/highcharts-angular/issues/138

It was worked for me, in bubble chart case.

**Comment by Robinyo** [comment]
@baskaranr 

Fixed :)

```
import * as Highcharts from 'highcharts';

import funnel from 'highcharts/modules/funnel';
// funnel(Highcharts);

...

export class FunnelChartComponent implements OnInit {

  Highcharts: typeof Highcharts = Highcharts;

  ...

  constructor() {

    funnel(this.Highcharts);
  }

  ngOnInit() {}

}
```

See: [funnel-chart.component.ts](https://github.com/Robinyo/serendipity/blob/master/projects/dashboard-widgets/src/lib/highcharts-angular/components/funnel-chart/funnel-chart.component.ts)

**Comment by KacperMadej** [comment]
Hi @Robinyo 

The demo works.
**Please be sure that you want to keep this repository public as it gives an easy access to all the e-mails.**

Could you create a simple example for the broken app - for the error?
Maybe I have just missed steps required to recreate the problem - please write them if this is the case.

**Comment by Robinyo** [comment]
Hi @KacperMadej 

As per @baskaranr 's response I moved the following line:

```
funnel(Highcharts);
```
into my [component](https://github.com/Robinyo/serendipity/blob/master/projects/dashboard-widgets/src/lib/highcharts-angular/components/funnel-chart/funnel-chart.component.ts)'s constructor:
```
  constructor() {

    funnel(this.Highcharts);
  }
```

I then rebuilt the application (`ng build --prod --source-map`) and redeployed it to Firebase Hosting and I no longer receive any Highcharts-related runtime errors. 

## Demo

Firebase Hosting: [Serendipity](https://serendipity-f7626.firebaseapp.com)

## Quick Links

[Serendipity Developer Documentation](https://github.com/Robinyo/serendipity/blob/master/docs/developer.md)
