### ISSUE TITLE
getSGV method is not available in angular-highcharts

### ISSUE THREAD

**Issue by chandanamadu** [highcharts/highcharts-angular#150]
### Describe the bug
The "getSVG" method is missing from angular-highcharts which is available in the Highchart

### Expected behavior
getSVG method should return an SVG representation of the chart.
[Highchart PAI](https://api.highcharts.com/class-reference/Highcharts.Chart#getSVG)

### Demo
Please provide live demo of the problem or provide any other way to recreate the problem.

> import { Chart } from 'angular-highcharts';
> const chartObj = new Chart(chartOption);
> chartObj.getSVG //  not defined

### Setup used
 - NodeJS version  -  v10.16.0
 - Angular cli version - 8.0.3
 - TypeScript version - ~3.5.3
- angular-highcharts : ^8.0.2,
etc.
please refer the attached package.json file ref.
![image](https://user-images.githubusercontent.com/9349781/61110483-feec4680-a4a4-11e9-856e-f391709a7994.png)

**Comment by KacperMadej** [comment]
Hi @chandanamadu 

This is not a repository for angular-highcharts
