### ISSUE TITLE
Gantt chart not displaying with Error: <rect> attribute y: Expected length, "NaN"

### ISSUE THREAD

**Issue by viqashussain** [highcharts/highcharts-angular#151]
### Describe the bug
I'm trying to display a very simple gantt chart, config which I have taken from the offical HighCharts examples, but it is not displaying anything, and I get the error `<rect> attribute y: Expected length, "NaN"` in the console. 

### Expected behavior
The gantt chart should be displayed like [this ](https://jsfiddle.net/hp23d84s/3/) JsFiddle example.

### Demo
[StackBlitz Demo](https://stackblitz.com/edit/angular-1vbtnk)

#### Steps required to recreate the problem in the demo:
See StackBlitz demo above. Gantt chart does not display on the app loading.

### Setup used
See Stackblitz demo above.

**Comment by KacperMadej** [comment]
Hi @viqashussain 

It looks like you have not set the correct constructor for the Gantt. In HTML use code like:

```html
<highcharts-chart [Highcharts]="Highcharts" [options]="chartOptions"
[constructorType]="'ganttChart'"
  style="width: 100%; height: 400px; display: block;">
</highcharts-chart>
```

This topic is covered by documentation here: https://github.com/highcharts/highcharts-angular#options-details

**Comment by viqashussain** [comment]
Yes you're right, thank you!
