### ISSUE TITLE
How to add no-data-to display to chart ?

### ISSUE THREAD

**Issue by somasekhar233** [highcharts/highcharts-angular#152]
like injection the exporting module.is there a way to add the no-data module to high chart
Thanks in advance

**Comment by KacperMadej** [comment]
Hi @somasekhar233 

Add it as any other module - https://github.com/highcharts/highcharts-angular#to-load-a-module
In case the module you want to add depends on other modules then initialize them in correct order.

If this doesn't resolve your problem please add code that you have used - preferable in a form of a live demo - and the issue could be reopened.
