### ISSUE TITLE
Dependencies in live demos of FAQ are outdated 

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts-angular#153]
When I was checking the demos in the FAQ section of the README.md file, I saw that the dependencies seems to be outdated as Angular 8 and highcharts v7.1.2 is out. Ex. https://codesandbox.io/s/lpn3yvv3zl

So I just want to inform you about this and ask if it is possible to update them.

**Comment by KacperMadej** [comment]
Hi @LoganDupont 

Thank you for pointing this one out.
Updated to Angular 8.1.3 and Highcharts 7.1.2.

(Only problem was core-js version that is causing some problems in the sandbox, so an older version needs to be used, but this is not a relevant issue for the Highcharts or the Highcharts wrapper for Angular.)
