### ISSUE TITLE
Re-grouping of Gantt chart Y axis for second time breaks only when collapsed property is set

### ISSUE THREAD

**Issue by IAm-Naveen** [highcharts/highcharts-angular#156]
Hello Guys ,

The purpose for me to have a live data visualization using ganttchart.
Which means the chart will be updated like every 10 seconds , this works fine if the gantt chart Y series structure doesn't change , if the series structure changes it breaks let me give you an example 

If i have 3 categories grouped for the first time it works , after lets say 10 seconds i am re grouping the series taking elements from 2nd category and assigning that to first category series it breaks Below is the working example .

https://stackblitz.com/edit/angular-3ucqgp

PS : If in above link projects gives an error , please update anything in app.component.html and save it automatically rectifies (Guess issue with Stack-blitz) .

Let me know if am doing something wrong

**Comment by KacperMadej** [comment]
If this issue is not different than the https://github.com/highcharts/highcharts/issues/11742
then it should be closed as the problem is reported on the main Highcharts repo and is about core Highcharts feature and not about this wrapper.

**Comment by IAm-Naveen** [comment]
I felt this issue was with grouping and the other one was after updating category click wasn't working 
Ya this can be closed as you have already referenced this issue in https://github.com/highcharts/highcharts/issues/11742 .

I am closing this one
