### ISSUE TITLE
Gantt chart : yAxis shrinking in exported chart 

### ISSUE THREAD

**Issue by Dronh** [highcharts/highcharts-angular#159]
Expected view:  Height of the bars should be constant
![Capture](https://user-images.githubusercontent.com/22931138/63682114-ce722900-c814-11e9-8e45-f7b68bf09e63.PNG)

Exported view: 
![chart (1)](https://user-images.githubusercontent.com/22931138/63678910-ce225f80-c80d-11e9-9ab1-5f94fcb2cedb.jpeg)

**Comment by KacperMadej** [comment]
Hi @Dronh 

This looks like a problem with setting exporting size or a problem with Gantt chart (hard to be sure without the live demo of the problem), and not a problem with Highcharts wrapper for Angular.

For Highcharts technical support see https://www.highcharts.com/blog/support/
