### ISSUE TITLE
Custom tooltip and axis values

### ISSUE THREAD

**Issue by xbotuk** [highcharts/highcharts-angular#17]
I would like to have custom formatted tooltips and axis values. How to achieve this?

**Comment by sebastianbochan** [comment]
Hi @xbotuk 
We use github for reporting bugs, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

**Comment by KacperMadej** [comment]
Chart's options passed to the component are the same as in the default Highcharts API, so you can do this the same as in the pure JS Highcharts chart.
https://api.highcharts.com/highcharts/
https://www.highcharts.com/docs
