### ISSUE TITLE
chart.type Attribute is ignored

### ISSUE THREAD

**Issue by bvinicius** [highcharts/highcharts-angular#177]
Hello,

I am trying to plot a **areaspline** chart in my application, but when i set the type, the value is ignored, and it defaults to the **area** chart.

Here is the current options object to my chart: 

```
  private chartOptions = {
    title: "RECONEXÕES POR DIA",
    chart: {
      type: 'areaspline',
      zoomType: 'x',
      events: {
        load: (e) => {
          this.chart = e.target //my way to get the chart instance.
        }
      }
    },
    series: [
      {
        name: 'RECONEXÕES POR DIA',
        color: '#FBA92B',
        data: [] //the data is given through API call
      }
    ],
  };
```

The code above gets the following result: 

![image](https://user-images.githubusercontent.com/48422883/74289489-edef0680-4d0d-11ea-89c0-d18e685caa35.png)

I am using highcharts-angular version 2.4.0 and angular 6.0.2.

Let me know if there's more information I could give! 
Thanks for the wrapper.

**Comment by totszwai** [comment]
Which highcharts version? You should provide a jsfiddle?

**Comment by bvinicius** [comment]
Actually, I didn't realize I was calling `chart.update()` function in my component, with the `type` option set to **line**. So the `type` value was always being overwritten. Changing the `type` value to **areaspline** in the function call solved my problem.
