### ISSUE TITLE
Link to "Solving problems" is 404

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts-angular#179]
### Describe the bug
There is a link named "Solving problems" that occurs at [README.md#L276](https://github.com/highcharts/highcharts-angular/blame/4cea96f84dca2ceef869b6eef1cc7cd8af4e96fa/README.md#L276) and [README.md#L321](https://github.com/highcharts/highcharts-angular/blame/4cea96f84dca2ceef869b6eef1cc7cd8af4e96fa/README.md#L321). Clicking on this link navigates to a site giving 404.

### Expected behavior
Link to typescript documentation, probably to the url https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-beta

**Comment by KacperMadej** [comment]
Thank you @jon-a-nygaard 😃 👋
