### ISSUE TITLE
Can I use all highcharts features/settings?

### ISSUE THREAD

**Issue by Waterfront97** [highcharts/highcharts-angular#18]
Hi,

when you say: "Official minimal Highcharts wrapper for Angular"
on your readme file, what does "minimal" mean?

Can I use the full functionality with this wrapper or just the ones, that are implemented yet?

Waterfront

**Comment by KacperMadej** [comment]
Hi @Waterfront97 

Yes, all features are fully supported.
`minimal` as in "we tried to have as little of code as possible to provide all features - full functionality".
If anything is not working then it should be considered as a bug and reported, so we can fix this.
