### ISSUE TITLE
getting error /node_modules/highcharts/highcharts"' has no exported member 'ChartObject' after updating to version 8.0.0

### ISSUE THREAD

**Issue by KSBharath557** [highcharts/highcharts-angular#182]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
A clear and concise description of what is wrong.

### Demo
Please provide live demo of the problem or provide any other way to recreate the problem.

#### Steps required to recreate the problem in the demo:
1. ...

### Setup used
 - NodeJS version ...
 - Angular version ...
 - TypeScript version ...
etc.

**Comment by KacperMadej** [comment]
Invalid bug report
