### ISSUE TITLE
Line series above axis space when zooming

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts-angular#184]
### Describe the bug
This problem only appeared to me when testing in Chrome. The first loaded chart doesn't have the problem with the zoom, it only appears when we change the data dynamically, as you can see the line extends beyond yAxis.

![1](https://user-images.githubusercontent.com/39968065/75379239-596fd100-58d5-11ea-8135-d88189756408.png)

Steps to reproduce:
1. Click on tab1 or tab2
2. Make zoom

Live demo:
https://codesandbox.io/s/highcharts-angular-wrapper-route-bug-8g8wq?fontsize=14&hidenavigation=1&theme=dark

### Expected behavior
The line does not extend beyond yAxis, it remains in the chart area.

Live demo:
https://jsfiddle.net/BlackLabel/14xakbfg/

**Comment by pawelfus** [comment]
Thanks for reporting the issue, it's already reported, see https://github.com/highcharts/highcharts/issues/5244 - closing as a duplicate.
