### ISSUE TITLE
Karma Unit Test case coverage for const for lazy loading

### ISSUE THREAD

**Issue by rupalij46** [highcharts/highcharts-angular#187]
I'm facing some issues in unit testing of lazy-loaded modules in Angular with constant appRoutes path. how to write unit testcase coverage for const appRoutes ? Please find below code of app-routing.module.ts

  import { NgModule, ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from "@angular/router"; import { AppRoutingComponent } from "./app-routing.component";

const appRoutes: Routes = [

{ path: "index.html", component: AppRoutingComponent }, { path: "product", loadChildren: () => import('app/dashboard/product.module').then(m => m.ProductModule) },

{ path: "", redirectTo: "/main", pathMatch: "full" } ];

export const routedComponents = [ AppRoutingComponent,

];

@NgModule({
   imports: [routing],
   exports: [RouterModule]
})

export class AppRoutingModule { }

**Comment by KacperMadej** [comment]
Hi @rupalij46 

Thank you for contacting.
For technical support please contact https://www.highcharts.com/blog/support/
