### ISSUE TITLE
Install instructions result in package being installed from Github instead of NPM

### ISSUE THREAD

**Issue by narsaym** [highcharts/highcharts-angular#19]
The install instructions [here](https://github.com/highcharts/highcharts-angular#installing) indicate the following:

>### Installing
>
>Get package from NPM in your Angular app:
>
>```cli
>npm install highcharts/highcharts-angular
>```

However, this results in the package being installed from Github, not NPM, hence ``package.json`` ends up looking like this: 
```json
...    
"highcharts-angular": "github:highcharts/highcharts-angular"
...
```
Therefore, in order to actually get the package from NPM, you must do the following instead: 

```cli
npm install highcharts-angular
```

The documentation should be updated to reflect the actual behavior. Additionally, the latest version of this npm package released [here](https://www.npmjs.com/package/highcharts-angular) is **0.1.0** while the latest on [Github](https://github.com/highcharts/highcharts-angular/releases) is **1.0.0**, is there a planned npm publish cycle to stay in sync with the latest release on Github? because it would be very useful to get a new release in npm to include the changes that are in [v1.0.0 release](https://github.com/highcharts/highcharts-angular/releases/tag/v1.0.0)

**Comment by KacperMadej** [comment]
Thank you for reporting.

@TorsteinHonsi Could you update the NPM package of `highcharts-angular`?

**Comment by TorsteinHonsi** [comment]
Done
