### ISSUE TITLE
how to add custom date picker 

### ISSUE THREAD

**Issue by srinugodhala** [highcharts/highcharts-angular#190]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

**Comment by mateuszkornecki** [comment]
Hello,

For general tech support, please contact us via one of the official support channels www.highcharts.com/support. Here you can report bugs or request features.

Regards.
