### ISSUE TITLE
oneToOne will violate a on* property security issue during ng tests.

### ISSUE THREAD

**Issue by fallenreaper** [highcharts/highcharts-angular#191]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
When using highcharts, i needed to leverage [oneToOne]="true" but i noticed that for Angular's testing framework, it will throw an error with regard to security issues.

### Expected behavior
Since it is an Angular error, there should be  property rename to something which allows us not get the on* security issues.

### Demo
```
<div #wrapper>
    <highcharts-chart [options]="chartOptions"
                      [Highcharts]="Highcharts"
                      [oneToOne]="true"
                      [(update)]="updateChart"></highcharts-chart>
</div>
```
With the above answer, and properties set, when doing `ng test`, it will error stating:

> Failed: Template parse errors:
> Binding to event property 'oneToOne' is disallowed for security reasons, please use (eToOne)=...
> If 'oneToOne' is a directive input, make sure the directive is imported by the current module. ("hart [options]="chartOptions"
>                       [Highcharts]="Highcharts"
>                       [ERROR ->][oneToOne]="true"
>                       [(update)]="updateChart"></highcharts-chart>

#### Steps required to recreate the problem in the demo:
I create an angular application leveraging high chrts.  My version _ng --version_ is s follows:
```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/animations               8.2.12
@angular/cdk                      8.2.3
@angular/cli                      8.0.6
@angular/material                 8.2.3
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by KacperMadej** [comment]
>If 'oneToOne' is a directive input, make sure the directive is imported by the current module. 

It is a directive input. Please make sure that directive is imported by your current module.

I am still seeing [the relevant issue for Angular](https://github.com/angular/angular/issues/11756) as closed and resolved in favor of allowing this `oneToOne` name. Also, the name is taken from a Highcharts argument for the chart.update function, so it's not like the wrapper is forcing something without any reason. If my arguments are not valid please share more info and we could find a solution that will work for everybody and the issue will be then reopened.

(Internal note: Relevant general test: https://github.com/highcharts/highcharts-angular/issues/60#issuecomment-416188600 )

**Comment by fallenreaper** [comment]
When Looking at it more, This root seems to come from: https://www.npmjs.com/package/highcharts-angular
as the highcharts itself is a javascript option primarily, I figured this port would do well.    I can look to reach out to one of their developers in order to see if the issue is nested deeper or not. 
@TorsteinHonsi @blacklabel might have some insight as i didnt see anything in their documentation which would lead me to believe this would fail in Tests but not in Prod

**Comment by KacperMadej** [comment]
> My package.json shows: "angular-highcharts": "^8.0.3"

In that case, you are using a wrong package as this is not an official package. For Highcharts use `highcharts` and for the wrapper `highcharts-angular`.

The error you were getting for the `oneToOne` is not showing if the definitions are connected properly and they are provided, so this is either a problem with Angular or with the way you have set up the wrapper. Unless something changed and there is another reason that this could happen. If so please share more info and the issue could be reopened.

**Comment by karolkolodziej** [comment]
A few things might have changed since the last time but I'm pretty sure that it shouldn't influent our wrapper if everything is properly configured. 
Could you please share an example where it fails?
