### ISSUE TITLE
colorAxis on bar chart doesn't work

### ISSUE THREAD

**Issue by vuhp** [highcharts/highcharts-angular#193]
I'm trying to add a color axis to my bar chart but unable to do so, even though there is no error in the console.
Here is [the code](https://codesandbox.io/embed/angular-kkyh0?fontsize=14&hidenavigation=1&theme=dark) for your checking.

With that same chart options, it can show the color axis if used highcharts directly, please refer to [this demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/coloraxis/custom-color-key/): 

Thank you.

**Comment by mateuszkornecki** [comment]
Hi @vuhp,

Sorry for the late reply.

To make it work you need to import and initialize the color axis module. After importing the module everything will work correctly.

```javascript
import colorAxis from "highcharts/modules/coloraxis";
colorAxis(Highcharts);
```

https://codesandbox.io/s/angular-y5yji?file=/src/app/app.component.ts:85-161
