### ISSUE TITLE
Dynamic change of timezone offset works only once

### ISSUE THREAD

**Issue by vodess** [highcharts/highcharts-angular#195]
### Describe the bug
In provided example the x axis shifts only after first change of the timezoneOffset option. Any other changes are ignored.

### Expected behavior
When timezoneOffset property is changed, it should be reflected in the chart, for example the x axis should shift accordingly.

### Demo
[highcharts-angular demo](https://codesandbox.io/s/angular-sz6l2)
[pure highcharts demo](https://jsfiddle.net/qbvf0guj/2/)

#### Steps required to recreate the problem in the demo:
1. Click on the Change timezone offset button
2. Watch the shifting of the x axis. In provided pure highcharts demo, it shifts everytime we hit the button. In highcharts-angular it shifts only after first click on that button:

![image](https://user-images.githubusercontent.com/15703819/80615177-a2f8ab80-8a3f-11ea-9f24-b1ae9d10ab48.png)
![image](https://user-images.githubusercontent.com/15703819/80615188-a68c3280-8a3f-11ea-871d-72b3cf3b7335.png)
![image](https://user-images.githubusercontent.com/15703819/80615204-aa1fb980-8a3f-11ea-8543-211173a81818.png)

Is this a bug or am I missing something (maybe regarding update property of the wrapper component) please?

Highcharts version: 8.0.4,
highcharts-angular version: 2.4.0

**Comment by KacperMadej** [comment]
Hi @vodess 

Thank you for reporting the problem.

The difference is in setting initial time options in the Angular demo and not setting the initial time options in the pure JS demo. This is Highcharts bug and is now reported here: https://github.com/highcharts/highcharts/issues/13670

I apologize for the long reply time - in case of questions please contact technical support for faster reply time. https://www.highcharts.com/blog/support/
