### ISSUE TITLE
Highstock with Ionic (Angular 8) will not load

### ISSUE THREAD

**Issue by cyberluke** [highcharts/highcharts-angular#198]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
Highcharts working fine in Ionic. But none of your solutions with highcharts-angular are working with Highstock. It will simply not render. For example this your jsFiddle is not working under Ionic and Angular 8 (emphasis on Ionic): https://codesandbox.io/s/angular-6ly2j

I was able to get it working without your directive.

Using Step 3 here in this Ionic Highcharts tutorial: https://medium.com/enappd/create-charts-in-ionic-4-apps-and-pwa-using-highcharts-63f8a00bae06 and replacing it with options from your jsFiddle it is finally working. I just imported Highstock using `import * as Highcharts from 'highcharts/highstock';` and supplied the options. 

Thanks to the tutorial, it also helped to put the code inside ionViewDidEnter() and now I don't need setTimeout with your custom callback to redraw the chart in order to get correct width.

It seems your solution is only working with generic Highcharts, not Highstock under Ionic. No error is output in the console. HTML is generated with your directive. There is blank box with some ul/li bullets without any CSS styles. No text is printed.

### Setup used
 - Ionic 5.0.0 (default bundle from website including Angular 8)
 - Angular version 8.2.14
 - TypeScript version 3.4.3
 - Highcharts 8.1.0

**Comment by cyberluke** [comment]
I just identified the problem:
```import IndicatorsAll from 'highcharts/indicators/indicators-all';
import DragPanes from 'highcharts/modules/drag-panes';
import AnnotationsAdvanced from 'highcharts/modules/annotations-advanced';
import PriceIndicator from 'highcharts/modules/price-indicator';
import StockTools from 'highcharts/modules/stock-tools';```

```IndicatorsAll(Highcharts);
DragPanes(Highcharts);
AnnotationsAdvanced(Highcharts);
PriceIndicator(Highcharts);
StockTools(Highcharts);```

This will break it. Without this, it works.

**Comment by cyberluke** [comment]
Ok, so the problem was because of CSS styles. Ionic use only SCSS and this did not work:
@import 'node_modules/highcharts/css/stocktools/gui.scss';
@import 'node_modules/highcharts/css/annotations/popup.scss';

I had to manually create highcharts.css file and put this content inside and use this in angular.json:
```            "styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              },
              {
                "input": "src/highcharts.css"
              }```

Is there a better way?

What is advantage of using your directive? Right now I don't miss it.

**Comment by KacperMadej** [comment]
Hi @cyberluke 

You have used the wrapper and provided a working demo (https://codesandbox.io/s/angular-6ly2j). 

Your issue description is very unclear - I understand that you might not be able to write perfectly in Eglish, but you should be able to see when code formatting is overlapping with the text.

If you just want to promote some related articles then it's fine, but this issue is not a valid bug report nor enhancement request, so this issue will be closed.

For general tech support, please see www.highcharts.com/support.
