### ISSUE TITLE
Angular 9: Export all charts by passing ids into single pdf

### ISSUE THREAD

**Issue by ajaysattikar** [highcharts/highcharts-angular#199]
There is no provision to export all the charts in a single pdf with Highchart using angular 2+.
It will be helpful if we have any API from Highchart team, 
e.g. By passing all the ids of charts present in that web page, it should export all the charts in one PDF on click of say a button "export all".

**Comment by mateuszkornecki** [comment]
Hello,

For general tech support, please contact us via one of the official support channels www.highcharts.com/support. Here you can report bugs or create a feature request.

I can see that a similar thread is already created on our forum, please take a look at it, the solution could be already posted. 
https://www.highcharts.com/forum/viewtopic.php?f=9&t=43894

Regards.
