### ISSUE TITLE
Update series dynamically

### ISSUE THREAD

**Issue by nemupm** [highcharts/highcharts-angular#20]
This library seems not able to update series dynamically(add or remove series collection)
because 'oneToOne' argument is false.

https://github.com/highcharts/highcharts-angular/blob/d8db0f7bdbe0d97c15b35e87dbc9561c132b2626/src/app/highcharts-chart.component.ts#L32
https://api.highcharts.com/class-reference/Highcharts.Chart#update

I think it is better to enable to update series by specifying oneToOne to be true or enabling to set oneToOne argument at @Input or something.

**Comment by TorsteinHonsi** [comment]
Agreed, this was the intention by adding the `oneToOne` parameter. From next release it is also integrated into the Data module.

**Comment by nemupm** [comment]
I understand, thanks for letting me know that.

**Comment by nadiamechlia** [comment]
try:` this.chart.ref.update(this.optionsValue); `
