### ISSUE TITLE
Pie chart with all values to 0 show error message.

### ISSUE THREAD

**Issue by Crocsx** [highcharts/highcharts-angular#201]
### Describe the bug
When using pie chart, and setting all series data to y, an Error message is displayed in the console.

### Expected behavior
Should not show an error message 

### Demo
https://stackblitz.com/edit/angular-ivy-sbghwm?file=src/app/app.component.ts

#### Steps required to recreate the problem in the demo:
1) if you set the series data to         `data: [{name: '111', y : 0}, {name: '222', y: 0}, {name: '333', y : 0}],` the message will appear 
> ERROR ReferenceError: "Highcharts is not defined"

2) just set to like `        data: [{name: '111', y : 0}, {name: '222', y: 0}, {name: '333', y : 1}],` and no message will be displayed 

### Setup used
Same as the Stackblitz

**Comment by mateuszkornecki** [comment]
Hello, thanks for reporting the issue. 

It seems to be related to the issue reported on the Highcharts repository: https://github.com/highcharts/highcharts/pull/13686 

The fix should be released soon, until then you could use the previous Highcharts version (8.1.0) and everything should work correctly.

Best regards.

**Comment by Crocsx** [comment]
Thanks, the previous version as a type mistake that break my compilations so I can't go back. I will wait for the fix :)

**Comment by Crocsx** [comment]
@mateuszkornecki I updated to 8.1.2, but this is still a problem

https://stackblitz.com/edit/angular-ivy-udtk3a?file=package.json

**Comment by saurabh47** [comment]
@Crocsx This issue is fixed in highcharts 8.2.2 

https://stackblitz.com/edit/angular-ivy-e8tbrl?file=src%2Fapp%2Fapp.component.ts
