### ISSUE TITLE
Is it possible to reduce prod bundle size?

### ISSUE THREAD

**Issue by adams-family** [highcharts/highcharts-angular#202]
### Requested feature description
Possibility to reduce bundle size generated by `ng build --prod --aot --build-optimizer`

### Details
I've implemented the 'hello world' example from `readme.md` and the size of my main-es.js file went up from **193k** to **456k** which seems to me a lot.

Is it possible to reduce this footprint?

This is literally everything I've added:

Into `app.module.ts`:

```ts
...
import { HighchartsChartModule } from 'highcharts-angular';

@NgModule({
  imports: [
    ...
    HighchartsChartModule
```

Into `my.component.ts`:

```ts
import { Component, OnInit } from '@angular/core';
import * as Highcharts from 'highcharts';

@Component({
  selector: 'my',
  templateUrl: './my.component.html',
  styleUrls: ['./my.component.less']
})
export class MyComponent implements OnInit {
  Highcharts: typeof Highcharts = Highcharts;
  chartOptions: Highcharts.Options = {
    series: [{
      data: [1, 2, 3],
      type: 'line'
    }]
  };

  constructor() { }
  ngOnInit(): void {
  }
}
```

Into `my.component.html`:

```html
<highcharts-chart 
  [Highcharts]="Highcharts"
  [options]="chartOptions"

  style="width: 100%; height: 400px; display: block;"
></highcharts-chart>
```

**Comment by KacperMadej** [comment]
Hi @adams-family 

Thank you for reporting the problem.

You could analyze the bundle structure and components size to check which packages are added and verify if their size is not alarming. For example using https://github.com/webpack-contrib/webpack-bundle-analyzer

The size change could be caused by adding Highcharts and some additional (if not used before) Angular core parts. If you will have any details about the problematic packages we could investigate if those are not required and if the bundle size could be reduced.

**Comment by adams-family** [comment]
Hi @KacperMadej 

Thanks for your response. In the meantime I realized that 200k is not as much of code considering that the entire Highcharts library + the Highcharts Angular library are both included.

Nonetheless, I installed weboack bundle analyzer and attaching the screenshit - is this what you were asking for?

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/19559733/84643517-3efe4980-aefe-11ea-937f-53790d5f847d.png">

**Comment by KacperMadej** [comment]
Thank you for the screenshot. Everything looks fine to me - nothing suspicious or anything that could improve the size significantly. It is like you wrote - 200k is not that much.

If you need to reduce the code as much as possible you could consider [a custom build of Highcharts](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files), but this won't be a significant size reduction when compared with the whole bundle.

Maybe there is an option to load moment js local files dynamically based on the client-side localization / time-zone? It takes up a lot of space and I imagine it's never the case that all those files are needed.

**Comment by stevethemacguy** [comment]
@adams-family. It's possible to keep HighCharts out of the main app bundle, though I haven't tried this method myself. See the articles below:

https://robferguson.org/blog/2019/09/23/dynamically-importing-highcharts/
https://medium.com/lacolaco-blog/angular-dynamic-importing-large-libraries-8ec079603d0

Unless you're really trying to squeeze every last drop of performance, however, I wouldn't recommend spending too much time on those articles.

We've put a lot of work into optimizing our bundles, but HighCharts is still our largest dependency (about 98kb gzip). Assuming you're compressing your JS with gzip or brotli, the actual bundle size will be the 'Gzipped size' shown in the screenshot, not the 'stat' or 'parsed' size.

Getting HighCharts working in a production (AOT/IVY) build, however, is another story. See [this ticket](https://github.com/highcharts/highcharts-angular/issues/161) if you haven't yet.

**Comment by adams-family** [comment]
@stevethemacguy ok, I agree, thanks for your comments on this. I'm marking this as closed.

**Comment by adams-family** [comment]
Thanks @KacperMadej, as well!

Yes, I was already trying to get rid of the unnecessary locales in momentjs, appearantly the official repo doesn't support it yet. FYI: https://stackoverflow.com/questions/49851277/how-to-exclude-moment-locales-from-angular-build
