### ISSUE TITLE
Options not set after reflow (Ionic App)

### ISSUE THREAD

**Issue by vidhi-mistry** [highcharts/highcharts-angular#206]
I used the reflow inside chart callback to force fit the graph into is parent element. Reflow does the trick of making the chart fit but the chart options changes.

Without reflow the chart loads with the scrollbar set to **extreme right.** After reflow the chart loads with scrollbar set to **extreme left**.

### Not using reflow:
This is how it looks on the [official demo page](https://www.highcharts.com/docs/chart-concepts/scrollbar)
Scrollbar position : Extreme right
<img src="https://user-images.githubusercontent.com/40681317/85777431-9f0ba180-b6ef-11ea-94b7-92302c022847.JPG" width="400">

### After reflow
This is how it looks in my app
Scrollbar position : Extreme left
<img src="https://user-images.githubusercontent.com/40681317/85777461-a5018280-b6ef-11ea-8844-264bfe382cc1.JPG" width="400">

### Expected Behaviour: 
After reflowing, the chart should be displayed with the options set. It should look same before or after reflow, i.e. the scrollbar position set to the one set in options. In my case, scrollbar position set to **extreme left**.

### Code 
https://github.com/vidhi-mistry/ionic-highcharts

### Setup 
Ionic:

Ionic CLI : 5.4.16
Ionic Framework : @ionic/angular 5.2.2
@angular-devkit/build-angular : 0.901.9
@angular-devkit/schematics : 9.1.9
@angular/cli : 9.1.9
@ionic/angular-toolkit : 2.2.0

Utility:

cordova-res : 0.15.0
native-run : 1.0.0

System:

NodeJS : v12.17.0
npm : 6.14.4

Highcharts:
highcharts : v8.1.2
highcharts-angular : v2.0.4

**Comment by mateuszkornecki** [comment]
Thanks for reporting the issue @vidhi-mistry .

It seems that it is a highcharts bug (`scrollPositionX` is not respected after the chart.reflow()). I have already reported it on the highcharts repository, you can track the progress here: https://github.com/highcharts/highcharts/issues/13778

Closing since it is not related to the highcharts-angular wrapper.

**Comment by vidhi-mistry** [comment]
Thanks!
