### ISSUE TITLE
PlotBands not show in gauge chart

### ISSUE THREAD

**Issue by giuliavt** [highcharts/highcharts-angular#208]
PlotBands not shows in gauge chart 

### Expected behavior
Hi, I'm trying to build a gauge chart but shows for few millisecond the right plotbands so after the plotbands not shows the right colors and shows grey color. But when I export the png or jpeg file it results right. I'm trying also to set zIndez to 20 but same result.
 
### Demo
in HTML file

<highcharts-chart 
[Highcharts]="Highcharts2"
[options]="chartOptions2"
[constructorType]="chartConstructor2"
  style="width: 20%; height: 600px; display: block;"
></highcharts-chart>

in TS file

  private Highcharts2 = Highcharts;
  private chartConstructor2: string = 'chart';
private chartOptions2: Highcharts.Options = {
        chart: {
            type: 'gauge',
            plotBackgroundColor: null,
            plotBackgroundImage: null,
            plotBorderWidth: 0,
            plotShadow: false
        },
    
        title: {
            text: 'Speedometer'
        },
    
        pane: {
            startAngle: -150,
            endAngle: 150,
            background: [{
                backgroundColor: {
                    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                    stops: [
                        [0, '#32CD32'],
                        [1, '#32CD32']
                    ]
                },
                borderWidth: 0,
                outerRadius: '109%'
            }, {
                backgroundColor: {
                    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                    stops: [
                        [0, '#32CD32'],
                        [1, '#32CD32']
                    ]
                },
                borderWidth: 1,
                outerRadius: '107%'
            }, {
                // default background
            }, {
                backgroundColor: '#32CD32',
                borderWidth: 0,
                outerRadius: '105%',
                innerRadius: '103%'
            }]
        },
    
        // the value axis
      
        series: [{
            type: 'gauge',
            name: 'Speed',
            data: [80],
            tooltip: {
                valueSuffix: ' km/h'
            }
        }],
        
      yAxis: {
            min: 0,
            max: 200,
            minorTickInterval: 'auto',
            minorTickWidth: 1,
            minorTickLength: 10,
            minorTickPosition: 'inside',
            tickPixelInterval: 30,
            tickWidth: 2,
            tickPosition: 'inside',
            tickLength: 10,
            title: {
                text: 'km/h'
            },
            plotBands: [{
                zIndex:20,
                from: 0,
                to: 120,
                color: '#32CD32' // green
            }, {
                zIndex:20,
                from: 120,
                to: 160,
                color: '#FFFF00' // yellow
            }, {
                zIndex:20,
                from: 160,
                to: 200,
                color: '#FF0000' // red
            }]
        }
    
    };

This is what I download when I clic on "Download JPEG image"
![speedometer](https://user-images.githubusercontent.com/44233787/86108580-a05c1600-bac3-11ea-95af-f9e61305865a.jpeg)
and this is what I see on browsers
![Immagine1](https://user-images.githubusercontent.com/44233787/86108735-d600ff00-bac3-11ea-9538-4c8630e13ded.png)

### Setup used
Angular 6
in package.json
.
.
  "highcharts": "^8.1.2",
    "highcharts-angular": "^2.4.0",
.
.
 "@angular/cli": "~6.2.4",
 "@types/node": "~8.9.4",
    "typescript": "^2.9.2"

Thank you in advance

**Comment by pawelfus** [comment]
Hi @giuliavt 

Thank you for reporting the issue. Tried to recreate the issue without angular, this is the result: https://jsfiddle.net/BlackLabel/e5cL76jh/ - it's the same as the one you get when exporting. Could you try recreate issue as a standalone one? For example using stackblitz. Thanks!

**Comment by giuliavt** [comment]
Hi @pawelfus ,
thank you for your reply.
I solved setting by css the z-index:2 at class highcharts-plot-bands-0, so I think that in my project there was something that overwrite it.
Thank you anyway.

**Comment by mateuszkornecki** [comment]
That's great to hear!

Closing as it is solved.
