### ISSUE TITLE
Solidgauge chart

### ISSUE THREAD

**Issue by aislingvasey** [highcharts/highcharts-angular#21]
Hi there

I have heat maps and scatter charts working fine using highcharts-angular but i can't get a solidgauge example working.

Error:
`RiskWidgetComponent.html:10 ERROR TypeError: c.init is not a function
    at a.Chart.initSeries (highcharts.js:237)
    at highcharts.js:261
    at Array.forEach (<anonymous>)
    at a.each (highcharts.js:27)
    at a.Chart.firstRender (highcharts.js:261)
    at a.Chart.init (highcharts.js:237)
    at a.Chart.getArgs (highcharts.js:236)
    at new a.Chart (highcharts.js:235)
    at Object.a.chart (highcharts.js:235)
    at HighchartsChartComponent.updateOrCreateChart (highcharts-chart.component.ts:33)`

I have include HighchartsChartComponent directly in my source code to avoid other issues.

I have a custom helper class with this code:
`import * as Highcharts from 'highcharts';

import * as HC_exporting from 'highcharts/modules/exporting';
HC_exporting(Highcharts);

import * as HC_solidgauge from 'highcharts/modules/solid-gauge';
HC_solidgauge(Highcharts);
...

export class HighchartsGaugeComponent {
  theChart : any;

  Highcharts = Highcharts; 
  chartConstructor = 'chart'; 
  chartOptions = {

      chart: {
          type: 'solidgauge'
      },

      title: null,

      pane: {
          center: ['50%', '85%'],
          size: '140%',
          startAngle: -90,
          endAngle: 90,
          background: {
              backgroundColor: '#EEE',
              innerRadius: '60%',
              outerRadius: '100%',
              shape: 'arc'
          }
      },

      tooltip: {
          enabled: false
      },

      credits: {
          enabled: false
      },

      plotOptions: {
          solidgauge: {
              dataLabels: {
                  y: 5,
                  borderWidth: 0,
                  useHTML: true
              }
          }
      },

      yAxis: {
          min: 0,
          max: 200,
          title: {
              text: 'Speed'
          }
      },

      series: [{
          name: 'Speed',
          data: [80],
          dataLabels: {
              format: '{y}'
          },
          tooltip: {
              valueSuffix: ' km/h'
          }
      }]
  };
  // Callback function after the chart is create
  chartCallback = (chart)  => {
    if (this.theChart == null) {
      this.theChart = chart;
      console.log('Set chart: '+this.theChart);
    }
  };
  // Used to indicate when the chart UI should be updated
  updateFlag = false;

...
`
Could you please point out what is incorrect with my code?

Thanks very much.

**Comment by KacperMadej** [comment]
Hi @aislingvasey 

The `solid-gauge` needs `highcharts-more` loaded before it. Like in HTML part of this pure JS demo: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-solid/

**Comment by aislingvasey** [comment]
How do you do that in Angular using your library?
I thought this loaded it:

**Comment by aislingvasey** [comment]
import * as Highcharts from 'highcharts';

**Comment by KacperMadej** [comment]
The code you posted loads only Highcharts. For solid gauge highcharts-more is required. You could load it before the solid-gauge module like:
```
import * as HC_more from 'highcharts/highcharts-more';
HC_more(Highcharts);

import * as HC_solidgauge from 'highcharts/modules/solid-gauge';
HC_solidgauge(Highcharts);
```

**Comment by aislingvasey** [comment]
Thanks - will try that out.

**Comment by ermarkar** [comment]
This expression is not callable.
  Type 'typeof import("......node_modules/highcharts/highcharts-more")' has no call signatures
