### ISSUE TITLE
Peer dependency for Angular 10

### ISSUE THREAD

**Issue by tomgruszowski** [highcharts/highcharts-angular#213]
### Requested feature description
Can Angular 10 be added as a valid peer dependency? or possibly >= 9? unless you plan on updating this package more frequently to keep dependencies synced with Angular release cadence.

Thanks

**Comment by panchitoboy** [comment]
+1

**Comment by KacperMadej** [comment]
Hi @tomgruszowski 

We have plans to update to 10 next week.

**Comment by tomgruszowski** [comment]
Thanks, @KacperMadej might be prudent to follow angular version in your version naming (i.e. highcharts-angular v10), so you can maintain v9 compatibility, just a thought.

**Comment by KacperMadej** [comment]
The wrapper is in the middle of Angular and Highcharts, so we would like to follow both libraries' versions equally. So far, so good - we don't follow any of them.
Version naming based on Angular is a nice idea - if this will be a popular idea then I am sure we could make this happen.

**Comment by tomgruszowski** [comment]
It's quite common among many angular libraries to follow this convention, it also gives you the flexibility to increment the major semvar without worrying that something else will break. It's not so much on how this library depends on a specific version of angular (which it doesn't), but more so about how it's packaged, you can always package it for the appropriate major version without too much worry.

**Comment by LoganDupont** [comment]
After updating to `highcharts-angular v2.8.0` i'm still receiving warnings even if the changelog mentioned that angular is updated to version 10.

> npm WARN highcharts-angular@2.8.0 requires a peer of @angular/common@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN highcharts-angular@2.8.0 requires a peer of @angular/core@^9.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by tomgruszowski** [comment]
@LoganDupont try re-installing your node-modules maybe? this seems like it's node related.

**Comment by LoganDupont** [comment]
Well actually it's not the case. If you go to https://github.com/highcharts/highcharts-angular/blob/master/highcharts-angular/package.json you will see that there are still some peerDependencies on angular 9.
```
"peerDependencies": {
    "@angular/common": "^9.0.0",
    "@angular/core": "^9.0.0",
    "highcharts": ">=6.0.0"
  },
```

**Comment by mateuszkornecki** [comment]
@LoganDupont 
Thanks for reporting!

You are right, as far as I know, the wrapper initially supported all angular's version. It seems that after migration to the angular 9 the peer dependencies were changed. 

_Internal note_
@karolkolodziej 
```
"@angular/common": "^2.0.0-rc.0 || >=2.0.0",
"@angular/core": "^2.0.0-rc.0 || >=2.0.0",
```
