### ISSUE TITLE
highcharts-chart is not known element

### ISSUE THREAD

**Issue by danderwald** [highcharts/highcharts-angular#214]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
after upgrading from 2.4.0 to 2.6.0 with Angular 9, the component selector seems to be missing, which leads to
highcharts-chart is not known element, so that application cannot be served / build anymore with this package
reverting back to 2.4.0 fixes this issue

### Expected behavior
When Upgrading a Feature Version with semVer, package should work as before

### Demo
n/A

#### Steps required to recreate the problem in the demo:
n/A

### Setup used
 - NodeJS version 12.18.2
 - Angular version 9.1.2
 - TypeScript version 3.8.3

will try to make a demo as soon as possible

**Comment by memnon33** [comment]
I found the same issue as above this morning - my only difference is that I am using Angular 10.0.4 typescript 3.9.7

**Comment by mateuszkornecki** [comment]
Thanks for reporting the issue. We are investigating the problem to find a proper solution. For now please use the `2.4.0` version.

**Comment by mateuszkornecki** [comment]
We have just released the 2.7.0 version that should fix the problem. Could you check if it is working correctly with the current version? Any feedback would be highly appreciated.

**Comment by jeffbdye** [comment]
I'm not the original person who opened the issue, but this seems to have been resolved with v2.7.0. Previously saw those errors mentioned above (`'highcharts-chart' is not a known element`) on v2.6.0, but just upgrading to v2.7.0 has fixed it and our build succeeds. Thanks for the quick turnaround!

**Comment by mateuszkornecki** [comment]
@jeffbdye Thanks for the information! It seems that everything is working correctly, so I am closing the issue.
