### ISSUE TITLE
Dynamically Update Serie with Highcharts.stockChart({}) doesn't show Data on small Screen with scrollablePlotArea!

### ISSUE THREAD

**Issue by hsnrzv** [highcharts/highcharts-angular#237]
### Describe the bug
i try to set Option with Method **Highcharts.setOptions()** and update Data Dynamically in ngOnInit with method **Highcharts.stockChart()**. on Screen larger than 600 Datas will be shown perfectlly on chart but on Screen smaller than 600 i receive no Data on chart. after Deploying my Web App, i tried to open chart on my Phone and i don't get any Datas on chart same as when you make screen smaller than 600 on Notebook.

### Expected behavior
show Datas on small screen perfectlly as on large Screen

### Demo
https://stackblitz.com/edit/angular-ivy-ggf8af?file=src/app/app.component.ts

### Setup used
 - Angular version 8

**Comment by karolkolodziej** [comment]
As you can see in the console there is an error [15](https://www.highcharts.com/errors/15/).
After resolving that issue by simply reversing the order in the data array (`..].reverse()`) it looks like everything works as expected.

**Demo:** https://stackblitz.com/edit/angular-ivy-reqjxl

**Comment by hsnrzv** [comment]
> As you can see in the console there is an error [15](https://www.highcharts.com/errors/15/).
> After resolving that issue by simply reversing the order in the data array (`..].reverse()`) it looks like everything works as expected.
> 
> **Demo:** https://stackblitz.com/edit/angular-ivy-reqjxl

thanks a lot for your quick response. it works perfectly and totally responsive 👍
