### ISSUE TITLE
Why not bundled into an Angular module ?

### ISSUE THREAD

**Issue by tzoratto** [highcharts/highcharts-angular#24]
Hi,

I was wondering why this project is not bundled into a module. It feels very unnatural to me to add the highcharts component into the `declarations` array of my app module instead of declaring a module import in the corresponding `imports` array (as I do with every single angular dependency usually).

I'm not sure but I think the various build issues that some people encounter would be resolved by doing so.

I'm curious to know the reason behind this choice

Thanks in advance

**Comment by KacperMadej** [comment]
Hi @tzoratto 

The choice was made to make it work in a similar way as it is working in the repo. The repo is a demo - https://github.com/highcharts/highcharts-angular#demo-app Second reason is that _`declarations` are for components_ ([source](https://angular.io/guide/ngmodules)) and the wrapper is a component, so this seems like a ok choice.

However, if you could suggest any enhancement suggestions, then we'll be happy to consider them. 

You could check `v5-dev` branch to check files available there would resolve any of your issues.

Please try with standard install (as in the docs - https://github.com/highcharts/highcharts-angular#installing) and then after first error (or right after installing the `highcharts-angular` NPM package) change in `node_modules` folder the content of `highcharts-angular` to the content of the branch: https://github.com/highcharts/highcharts-angular/tree/v5-dev

If this will work then the branch will become new master. As for now it was tested on few machines and the problem was resolved, but it would be better to run more tests. In the meantime you can try the `v5-dev` branch solution.

**Comment by httpete** [comment]
This is a valid critique, and the hack for the tsconfig.json (Adding another include path) shows that this highcharts-angular is not bundled right. 

https://www.npmjs.com/package/angular-highcharts

That package is doing things the angular way, and has more contributors. and is more active. Could we understand why one would use this official wrapper instead?

**Comment by KacperMadej** [comment]
This is official, because it's handled by Highsoft - Highcharts provider.

Please check v5-dev branch to avoid the hack. If you have more info about how the wrapper could be improved then please share - we are open for enhancement suggestions.

**Comment by httpete** [comment]
all Angular components are shared via an angular package format, and are shared as Angular Modules. 
Handing the [Highcharts] to every instantiation is bad. If you see the way angular-highcharts did it, it is much cleaner. What we really want is to be completely abstracted from the underlying Highcharts <script> stuff, and have a modern es6 way to load plugins, and configure global defaults for the entire app. Then it's similiar. They have done alot of work, but as a licensed long time customer I would rather use yours.

**Comment by KacperMadej** [comment]
As a part of technical support we are trying to support any wrappers for Highcharts - the main limitations are bugs withing the third party software that we have no control of and no real influence over.

There are (and were more) issues with core Highcharts and loading multiple modules over and over again when it was not required (or even were causing errors). Most of then (if I remember correctly) were related to ES6 plugin loading and incorrect Highcharts loading. We'll reassess the situation now and check if the core is more friendly for ES6 or if there's a better way for Highcharts instance handling for multiple chart instances. Just to confirm - [this](https://github.com/cebor/angular-highcharts#using-highcharts-modules) (https://github.com/cebor/angular-highcharts#using-highcharts-modules) is the relevant part of the angular-highcharts documentation?

_Internal note:_ Enhancement: allow "global" Highcharts instance initialized once per app as default and additional (when compering with current state) source of the Highcharts instance.

**Comment by Tatsh** [comment]
I switched from _angular-highcharts_ to this version on the `v5-dev` branch. It took about an hour but I am very grateful for doing so. This fixed a number of issues I was having. Just my opinion but I think _angular-highcharts_ imposes way too much just for the sake of abstraction. It also does not solve loading of extensions (of any kind) any better than this library does.

This way of doing things via one simple component works well, especially when passing around the instantiated Highcharts object (`<child-element [highcharts]="highcharts">`). I will be glad to see the _v5-dev_ branch become the default.

**Comment by gregjacobs** [comment]
Yeah this should really be compiled into JavaScript. Just ran into the tsconfig issue as well, getting this error message:

```
ERROR in ./node_modules/highcharts-angular/src/app/highcharts-chart.component.ts
Module build failed: Error: ..\node_modules\highcharts-angular\src\app\highcharts-chart.component.ts 
is missing from the TypeScript compilation. Please make sure it is in your tsconfig via 
the 'files' or 'include' property.

The missing file seems to be part of a third party library. TS files in published libraries 
are often a sign of a badly packaged library. Please open an issue in the library repository 
to alert its author and ask them to package the library using the Angular Package 
Format (https://goo.gl/jB3GVv)
```

(note the second paragraph)

Angular CLI for 6 allows for library projects: https://github.com/angular/angular-cli/wiki/stories-create-library. Check that out?

**Comment by Tatsh** [comment]
This does need a completed type definition file, but that should be another issue. And I would add that @types/highcharts is not fully complete but it comes close. It would be good for the type definition file for the component to reference that.

**Comment by gregjacobs** [comment]
@Tatsh The `.d.ts` file with the typings would be generated during the TypeScript compilation to `.js`
