### ISSUE TITLE
Cannot find module '@highcharts/map-collection/custom/world.geo.json'. Consider using '--resolveJsonModule' to import module with '.json' extensionts

### ISSUE THREAD

**Issue by umamaheshbhamidipati** [highcharts/highcharts-angular#240]
There is an issue in angular 10,
In tsconfig.base.json file in complierOptions 
"resolveJsonModule": true, 
I have added this thing. Still the above issue exits

**Comment by karolkolodziej** [comment]
Did you install that module correctly?
Check the module's npm site: https://www.npmjs.com/package/@highcharts/map-collection
If it's not the case, please recreate the issue in the online editor because I was not able to recreate that issue on my own.

**Comment by umamaheshbhamidipati** [comment]
Yes, the issue has solved, maybe there is an issue with vs code editor, I have closed it and reopened, it is working fine now thanks, Karol :)
