### ISSUE TITLE
Getting error on prod build , I am using angular 7

### ISSUE THREAD

**Issue by togouse** [highcharts/highcharts-angular#241]
ERROR in : Type HighchartsChartComponent in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts is part of the declarations of 2 modules: AppModule in D:/timeline/src/app/app.module.ts and HighchartsChartModule in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts! Please consider moving HighchartsChartComponent in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts to a higher module that imports AppModule in D:/timeline/src/app/app.module.ts and HighchartsChartModule in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts. You can also create a new NgModule that exports and includes HighchartsChartComponent in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts then import that NgModule in AppModule in D:/timeline/src/app/app.module.ts and HighchartsChartModule in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts.

**Comment by karolkolodziej** [comment]
Could you please recreate your issue in the online code editor that I could work on?
Which version of `highcharts-angular` do you use?

**Comment by chetanGH** [comment]
> ERROR in : Type HighchartsChartComponent in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts is part of the declarations of 2 modules: AppModule in D:/timeline/src/app/app.module.ts and HighchartsChartModule in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts! Please consider moving HighchartsChartComponent in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts to a higher module that imports AppModule in D:/timeline/src/app/app.module.ts and HighchartsChartModule in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts. You can also create a new NgModule that exports and includes HighchartsChartComponent in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts then import that NgModule in AppModule in D:/timeline/src/app/app.module.ts and HighchartsChartModule in D:/timeline/node_modules/highcharts-angular/highcharts-angular.d.ts.

Try using it in Shared-module and import it in your working module, I hope this will solve the issue.

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
