### ISSUE TITLE
HowTo call method in chart ?

### ISSUE THREAD

**Issue by AizeLeOuf** [highcharts/highcharts-angular#26]
Hello,

First of all, I never see an Angular Component like that... You have still many work...

Ok for my problem, imagine a Component with a chart. Simple, I want to call .setSize(X, Y, false); from my component and of course outsite update flag and callback function you proposed.

Regards,

**Comment by KacperMadej** [comment]
Hi @AizeLeOuf 

Currently you could use callback or chart's events defined in the chart's options to access the `chart` instance. If you would like to suggest a new feature that could be useful for you then please describe it and I can label the issue as `enhancement`.


> First of all, I never see an Angular Component like that... You have still many work...

Could you elaborate, so we could improve the wrapper? If you are not telling what could be improved or what's wrong then a comment like that doesn't bring anything useful for the problem resolving.

**Comment by AizeLeOuf** [comment]
Hi,

Ok but it's not well document I think, live example is a mininum to help new users to adopt your lib. 

About features, look up other project like https://github.com/rijine/ngx-highcharts
Love their proposal to support event for example.

**Comment by KacperMadej** [comment]
I agree - live demos would be great.

Enhancements: 
- exposing chart instance
- live demos
- investigate advanced event handling (refer to: https://github.com/rijine/ngx-highcharts)

Thank you for all the info.

**Comment by attilacsanyi** [comment]
I use this way for example the `chart.exportChartLocal(...)` method with **RxJs** and `BehaviourSubject`.

```
import { OnInit, Component, ChangeDetectionStrategy } from '@angular/core';

import { Observable, BehaviorSubject } from 'rxjs';
import { filter, first, tap } from 'rxjs/operators';

import * as Highcharts from 'highcharts';

@Component({
  selector: 'chart',
  templateUrl: './chart.component.html',
  styleUrls: ['./chart.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ChartComponent implements OnInit {

  // required
  Highcharts = Highcharts;

  // optional string, defaults to 'chart'
  chartConstructor = 'chart';

  chartOptions: Highcharts.Options;

  // optional function, defaults to null
  chartCallback = this.callback.bind(this)

  // optional boolean 
  updateFlag = false;

  // optional boolean, defaults to false
  oneToOneFlag = true;

  private chartObject$: Observable<Highcharts.ChartObject>;
  private chartObjectSubject: BehaviorSubject<Highcharts.ChartObject | null>;

  constructor() { }

  ngOnInit() {
    this.chartObjectSubject = new BehaviorSubject(null);
    this.chartObject$ = this.chartObjectSubject.asObservable().pipe(filter(chartObject => !!chartObject));
    this.initChart();
  }

  exportChartLocal = (type = 'image/png', filename = 'my-chart') =>
    this.chartObject$
      .pipe(
      first(),
      tap(chart => chart.exportChartLocal({ type, filename, sourceWidth: 2048 }))
      )
      .subscribe();

  private initChart = () => {
    const chartOptions: Highcharts.Options = {};

    chartOptions.chart = { type: 'column' },

    chartOptions.title = { text: null }

    chartOptions.series = [{
      data: [1, 2, 3]
    }]

    this.chartOptions = chartOptions;
  }

  private callback(chart: Highcharts.ChartObject) {
    const options: Highcharts.Options = chart.options;
    console.log(options.chart);

    // Emit the chart object once initialised
    this.chartObjectSubject.next(chart)
  }
}
```

Thanks for any feedback.

**Comment by KacperMadej** [comment]
In case of exported chart callback and chart.load event will be called one more time on a chart that is prepared for export, so if you are setting reference in that functions, then you should add a check like `if (chart.renderer.forExport)` to know when the function is called for export.

There's no ETA for this issue, but we are working on it, so you could expect updates in next few days.
