### ISSUE TITLE
getSVG() ends with - Cannot read property 'plotOptions' of undefined

### ISSUE THREAD

**Issue by amiram** [highcharts/highcharts-angular#262]
### Describe the bug
When using `getSVG()` for the second time, it ends with an error "Cannot read property 'plotOptions' of undefined". It looks like the chart callback is called after the first call to `getSVG()` and this instance has `userOptions` undefined inside the export module. It doesn't happen with plain highcharts, just with angular.

### Expected behavior
`getSVG()` will return the svg string.

### Demo
https://stackblitz.com/edit/highcharts-angular-get-svg

#### Steps required to recreate the problem in the demo:
1. Use a callback to save the chart instance.
2. Use getSVG() twice.

### Setup used
 - Angular version - 11
 - TypeScript version 3.1.1

**Comment by karolkolodziej** [comment]
When you fire the `getSVG` method, the [chart copy is created](https://github.com/highcharts/highcharts/blob/8a4d75a34257959408ec566e3cfbc94b867aabfd/ts/Extensions/Exporting.ts#L1501) as a `new Chart(options, chart.callback)` .

Inside this second callback, the chart reference is lost. Instead of using the argument of callback (`chart`) as a reference, you can use the `Highchats` object and always have the correct chart assigned.

**Demo:** https://stackblitz.com/edit/highcharts-angular-get-svg-vioxkv

**Comment by amiram** [comment]
@karolkolodziej Thanks! but if I have more than one component and each has each own chart, will it work? Is setting the chart only once like `this.chart = this.chart || chart` is also good or there are other cases that the instance should be updated?

**Comment by karolkolodziej** [comment]
In the use case which you mentioned it also will work, however, it might generate some difficulties how to track each chart especially when you make an update the `Highcharts.charts` array becomes longer and longer.
The solution you described (`this.chart = this.chart || chart`), seems to work in my each test case.

**Comment by amiram** [comment]
I saw this in the readme page

> Notice: If you are getting chart instance from chart's load event or chart's callback funciton and will be supporting exporting, then this function runs again when the chart is exported, because a chart for export is being created. To distinguish when the function is called for the chart and when it's called for the for-export chart you could check chart.renderer.forExport. If will be set to true for the for-export chart and undefined for the main chart.

So I guess I just missed it and this is the solution.

**Comment by karolkolodziej** [comment]
Great! Thanks for sharing that!
