### ISSUE TITLE
Events are added but aren't being fired

### ISSUE THREAD

**Issue by lwensveen** [highcharts/highcharts-angular#272]
### Describe the bug
events are added but don't fire like https://github.com/highcharts/highcharts-angular/issues/71

This happened after migrating to highcharts-angular. I can see the events being attached in the chart.userOptions.chart.events, yet it doesn't fire off my dispatch, just shows some reset zoom button.

![image](https://user-images.githubusercontent.com/4800388/109505506-f347fc00-7a9c-11eb-9cb7-c4bc2b12674c.png)

### Expected behavior
Expect 

### Demo
```
  chartOptions: Highcharts.Options = {
    chart: {
      styledMode: true,
      events: null,
    },
    tooltip: {},
    exporting: {
      enabled: true,
    },
    time: {
      moment: moment,
    },
    series: [],
    global: {},
  };

  selection = (event) => {
    this.store.dispatch(
      goStartAndEndDate({
        startDate: DateHelper.convertUnixTimestampToMoment(event.xAxis[0].min),
        endDate: DateHelper.convertUnixTimestampToMoment(event.xAxis[0].max),
      }),
    );

    setTimeout(() => {
      this.store.dispatch(loadAllChartData());
    }, 0);

    return false;
  };

  subscribeToEvents(): void {
    if (this.chartOptions.chart && this.chartOptions.chart.events !== null) {
      if (!this.chartOptions.chart.events['selection']) {
        this.chartOptions.chart.events['selection'] = this.selection;
      }
    }
  }
```

### Setup used
    "@angular/core": "^11.2.0",
    "highcharts": "9.0.1",
    "highcharts-angular": "^2.10.0",.

**Comment by lwensveen** [comment]
If you add a ngIf like so:

```
  <highcharts-chart
    *ngIf="this.chartOptions.chart.events !== null"
    ```
it seems to work but it doesn't pick up the styledMode anymore which causes the chart to lose all it's custom styling.

**Comment by karolkolodziej** [comment]
Could you please recreate your example in [online code editor](https://stackblitz.com/edit/highcharts-angular-basic-line) that I could better understand the issue?

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
