### ISSUE TITLE
Uncaught Error: Type HighchartsChartModule does not have 'ɵmod' property (question)

### ISSUE THREAD

**Issue by hkcity1111** [highcharts/highcharts-angular#273]
Hi,

I tried to clone this repo and run highchart angular demo inside by npm start after npm install package on working directory. I go the following error in my chrome browser.
Do any professional have idea for my problem?
Thanks.

nodejs : 10.14.16
highchart: 9.0.1

Best Regards,
   hkcity1111

```
Uncaught Error: Type HighchartsChartModule does not have 'ɵmod' property.
    at getNgModuleDef (core.js:1022)
    at recurse (core.js:24966)
    at recurse (core.js:24977)
    at registerNgModuleType (core.js:24962)
    at new NgModuleFactory$1 (core.js:25076)
    at compileNgModuleFactory__POST_R3__ (core.js:28679)
    at PlatformRef.bootstrapModule (core.js:28922)
    at Module.zUnb (main.ts:12)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.js:11)
```

**Comment by karolkolodziej** [comment]
Did you try with the slightly newer versions of node?

**Comment by thakee** [comment]
Same error here. Node version v12.13.0

**Comment by NarayanPKulkarni** [comment]
Hi,
Did anyone solve this problem?

**Comment by subhabrata2017** [comment]
Same issue Node version v14.17.0, Angular version 11.1, Highcharts 10.1.0

**Comment by karolkolodziej** [comment]
I have just cloned the repo and by running `npm install` and `npm start` I was able to easily build the repo.

Node `v16.14.2`
npm `8.5.0`

**Comment by karolkolodziej** [comment]
Closing as unable to recreate.
