### ISSUE TITLE
Timeline chart?

### ISSUE THREAD

**Issue by aislingvasey** [highcharts/highcharts-angular#275]
Hi 
I get error 17 when attempting to use a timeline chart. 

chart: {
            type: 'timeline'
        },

Does this library not support the timeline module? How Is there a way to enable it?

Thanks

**Comment by karolkolodziej** [comment]
You can use that series, but first, you have to import the module with that series.
More on that here: https://github.com/highcharts/highcharts-angular#to-load-a-module
And here: https://www.highcharts.com/docs/chart-and-series-types/timeline-series

For future reference, with general support questions use available [support chanels](https://www.highcharts.com/blog/support/)

**Comment by aislingvasey** [comment]
I know how to use highcharts and import the modules - thank you.
There is no such module though even though there probably should be one for timeline?
Error is: 
Cannot find module 'highcharts/modules/timeline' or its corresponding type declarations.

**Comment by aislingvasey** [comment]
As per the highcharts docs:
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/timeline.js"></script>
