### ISSUE TITLE
Add Highcharts plugins using this wrapper

### ISSUE THREAD

**Issue by j4inam** [highcharts/highcharts-angular#28]
Hi,
I'm using this wrapper in my angular 5 app and would like to use a LTTB downsampling plugin while drawing the chart.
How do I integrate the plugin using this wrapper ?

Here's a fiddle of the plugin:
http://jsfiddle.net/sveinn_st/FMJAL/

I included the js file of the plugin in index.html but I got the error:
'Highcharts' is not defined

**Comment by KacperMadej** [comment]
Adding plugins is covered in documentation - https://github.com/highcharts/highcharts-angular#to-load-a-plugin
