### ISSUE TITLE
lineColor doesn't exist in PlotCandlestickOptions

### ISSUE THREAD

**Issue by SanchitStake** [highcharts/highcharts-angular#281]
### Describe the bug
When using candlestick charts there is no option to change the lineColor (other than upLineColor) from black to a custom color. Please see the screenshot of the red outlined by black.

![image](https://user-images.githubusercontent.com/71248334/113982040-a5889580-988b-11eb-96a0-51e35d46ab6e.png)

![image](https://user-images.githubusercontent.com/71248334/113982083-af11fd80-988b-11eb-93e6-4f7f83599d9e.png)

This is particularly an issue in dark mode:
![image](https://user-images.githubusercontent.com/71248334/113983903-d7026080-988d-11eb-9aba-1e85d7d655d4.png)

### Expected behavior
A way to change the lineColor of candlestick charts would be amazing. This is currently possible in the javascript library of high charts. Please see attached screenshot of this.

![image](https://user-images.githubusercontent.com/71248334/113982069-aae5e000-988b-11eb-82f6-fbc4778ac159.png)

### Demo
Please see attached screenshots. 

### Setup used
 - NodeJS version v14.15.4
 - Angular version v11.2.5
 - TypeScript version v4.1.5
etc.

**Comment by karolkolodziej** [comment]
I don't understand why you can't change that colour. In the demo below I managed to apply that property to the `candlestick`.
Could you please tell me if you get any errors? Or please describe what in your project is different from the demo.

Demo: https://stackblitz.com/edit/highcharts-angular-stock-qpixtq

**Comment by SanchitStake** [comment]
Hello, thank you for your response.

I was using highcharts v2.10.0 as opposed to your v2.9.0. After reverting back, lineColor worked as required. 

Thank you.
