### ISSUE TITLE
Width not the same

### ISSUE THREAD

**Issue by rozzs74** [highcharts/highcharts-angular#282]
I am reporting an issue about the width alignment of the component

**highcharts-angular** https://jepto.link/tUuYQy
**div** https://jepto.link/2r6kL6

package version:
**highcharts@9.0.1**
**highcharts-angular@2.10.0**

How to solve the issue?

**Comment by mateuszkornecki** [comment]
@rozzs74 Thanks for reporting the issue.

It is hard to tell you the exact reason for such behavior without taking a look at the code/chart configuration. It sounds familiar to #217 and #149 so you might try the solution posted in these issues (calling `chart.reflow()` to resize correctly.

**Comment by rozzs74** [comment]
Thanks, @mateuszkornecki   I have tried the solution

component: https://jepto.link/qmbiQw
layout: https://jepto.link/OX2NVB
output:
 **highcharts-chart** https://jepto.link/a26hok
**container** https://jepto.link/EdLXSi
**SVG** https://jepto.link/EdLXSi

I got stuck in here.

**Comment by mateuszkornecki** [comment]
Could you reproduce the issue in an online editor that I can work on? It is hard to tell you what is not working or what could be done without taking look at your code.

You can start from this template:
https://stackblitz.com/edit/highcharts-angular-basic-line

**Comment by rozzs74** [comment]
Hi @mateuszkornecki  I have fixed the issue by adding the **reflow** under highcharts native event. Thanks!
