### ISSUE TITLE
Not able to do AOT build

### ISSUE THREAD

**Issue by kalandher** [highcharts/highcharts-angular#283]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
Getting below error during AOT build

ERROR in node_modules/highcharts-angular/node_modules/tslib/tslib.d.ts(49,82): error TS2304: Cannot find name 'unknown'.
node_modules/highcharts-angular/node_modules/tslib/tslib.d.ts(67,82): error TS2304: Cannot find name 'unknown'.
node_modules/highcharts-angular/node_modules/tslib/tslib.d.ts(76,96): error TS2304: Cannot find name 'unknown'.
node_modules/highcharts-angular/node_modules/tslib/tslib.d.ts(85,82): error TS2304: Cannot find name 'unknown'.

### Expected behavior
AOT build should be successfull

### Setup used
 - NodeJS version : 8.11
 - Angular version : 6.0
 - TypeScript version : 2.7.2
- Highcharts-angular: 2.10.0
- Highcharts: 9.0.0

**Comment by mateuszkornecki** [comment]
Hi @kalandher , thanks for your report!

Could you reproduce in a simple demo and write the steps needed to recreate the issue? I was trying to build a project using AOT compilation and it was working correctly for me.

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
