### ISSUE TITLE
Chart isn't responsive inside a flex container 

### ISSUE THREAD

**Issue by dota2Pro** [highcharts/highcharts-angular#285]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
A clear and concise description of what is wrong.
Chart created with `highcharts-angular` doesn't fit inside its container, instead it overflows out of the container.
### Expected behavior
It should be responsive just like the JavaScript highcharts library
highcharts -> https://jsfiddle.net/dota2pro/bdjtf8n1/ ( responsive)
`highcharts-angular` -> https://stackblitz.com/edit/highcharts-angular-basic-line-48qvhv?file=src%2Fapp%2Fapp.component.css (unresponsive)
I expect the `highcharts-angular` demo to look exactly like `highcharts` as I am using the same css on both.
### Demo
Please provide live demo of the problem or provide any other way to recreate the problem.
Please see the unresponsive behavior in this Demo
https://stackblitz.com/edit/highcharts-angular-basic-line-48qvhv?file=package.json

#### Steps required to recreate the problem in the demo:
1. ...

### Setup used
 - NodeJS version ...v14.15.5
 - Angular version ... 11.0.5
 - TypeScript version ...~3.1.1
 -  highcharts: "^8.2.2",
 -  highcharts-angular: "^2.9.0",

etc.

**Comment by mateuszkornecki** [comment]
@dota2Pro Thanks for reporting the issue!

It seems that the `chart` container created by angular is missing the `display: block` style. To fix the problem you could just apply `display:block` to the `highcharts-chart` component.

```html
<highcharts-chart 
   [Highcharts]="Highcharts" 
   [options]="chartOptions" 
   style="display: block;">
</highcharts-chart>
```

https://stackblitz.com/edit/highcharts-angular-basic-line-usth6t?file=src%2Fapp%2Fapp.component.html
