### ISSUE TITLE
Missing type definition for 'processedYData' in class 'Series'.

### ISSUE THREAD

**Issue by dota2Pro** [highcharts/highcharts-angular#287]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Requested feature description
In [this Stackblitz example](https://stackblitz.com/edit/highcharts-angular-basic-line-9qpzew?file=src%2Fapp%2Fapp.component.ts) I am using tickPositioner on Y-axis, and I noticed that series is missing definition for 'processedYData' line number 46 in `app.component.ts`
But It works if you type cast series object as "any"

**Comment by mateuszkornecki** [comment]
It looks like one of the commonly reported problems, you can find more information and more elegant solution (than `as any`)  in our FAQ section:

https://github.com/highcharts/highcharts-angular#property-xxx-does-not-exist-on-type-yyy

Feel free to reopen the issue if the link above won't help.
