### ISSUE TITLE
Conditional opacity change for boxplot

### ISSUE THREAD

**Issue by ajinkyabapat1** [highcharts/highcharts-angular#288]
Hi ,

is there any way to change the opacity of the box plot color based on value. eg. From lower value to higher value, opacity should also change from low to high.

any help will be highly appreciated

**Comment by karolkolodziej** [comment]
As a reminder:
 ```
For general tech support, please see www.highcharts.com/support.
```

Yes, you can change the opacity, colour or any other property based on some value.
I created the `chartRef` in the `chartCallback` then I used the chart update method to change the color.

Demo: https://stackblitz.com/edit/highcharts-angular-color-slider

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
