### ISSUE TITLE
Console error TypeError: Cannot read property 'series' of undefined

### ISSUE THREAD

**Issue by rozzs74** [highcharts/highcharts-angular#289]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
On load the page, this is happening https://jepto.link/LVXhCL
Pointing to https://jepto.link/RE8BV9 **updateOrCreateChart**

### Expected behavior
What to do?

#### Steps required to recreate the problem in the demo:
1. ...

### Setup used
- node v14.14.0
-  angular 11
-  typescript 4
- highcharts - 9.0.1
- highcharts-angular 2.10.0
etc.

**Comment by karolkolodziej** [comment]
Could you please share how are you creating that chart? 
It looks like something is missing. 

Also please remember: 
_For general tech support, please see www.highcharts.com/support.
Please report only issues about highcharts-angular wrapper or content of this repository.
For general issues with Highcharts and TypeScript the correct repository to report such issues is main Highcharts repository._

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
