### ISSUE TITLE
HighCharts 9.1.0 upgrade

### ISSUE THREAD

**Issue by Huertix** [highcharts/highcharts-angular#291]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Requested feature description
Hi guys,

Sorry for bothering with this question. Maybe is somewhere I did not find. 

Do you have a time estimation on when you will be supporting Highcharts 9.1.0.

Many thanks in advance,
David

**Comment by karolkolodziej** [comment]
The wrapper works correctly with Highcharts v.9.1.0.
Demo: https://stackblitz.com/edit/highcharts-angular-basic-line-mxn4zg
