### ISSUE TITLE
Update to Angular 12

### ISSUE THREAD

**Issue by fgoulet** [highcharts/highcharts-angular#292]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Requested feature description
Is it known if this library works well with Angular 12 ?

**Comment by mateuszkornecki** [comment]
Yes, I can confirm that the `highcharts-angular` wrapper is working correctly with Angular 12.

**Live demo:**
https://stackblitz.com/edit/highcharts-angular-optimal-way-to-update-1konp2

Our wrapper is just a simple component, and it should work correctly regardless of the Angular or Highcharts version. Regardless of that, we will update the angular CLI that built the package in the future - there shouldn't be any problems with the current version.

**Comment by shravansofts** [comment]
Any ETA?

**Comment by Maximaximum** [comment]
How about Angular 13? :)

**Comment by karolkolodziej** [comment]
Resolved by #305
