### ISSUE TITLE
highcharts-angular does not gracefully degrades if a route/component is destroyed

### ISSUE THREAD

**Issue by nunoarruda** [highcharts/highcharts-angular#293]
### Describe the bug
It looks like highcharts-angular does not gracefully degrade if a route/component holding a reference to the chart is already destroyed. This could happen when there is a slow response from a backend and/or if a user quickly navigates through routes.

### Expected behavior
highcharts-angular should gracefully degrade if a route/component no longer exists. Maybe highcharts-angular needs to have extra safety checks to make sure this situation does not happen.

### Demo
https://stackblitz.com/edit/highcharts-angular-undefined

#### Steps required to recreate the problem in the demo:
1. Go to the /chart route
2. Click the "Add Series" button. This will mimic/emulate a slow response from a backend
3. Before the chart series is added (before the counter reaches 0) go to the /home route
4. Notice that highcharts will throw the error `ERROR TypeError: Cannot read property 'chart' of undefined`

https://user-images.githubusercontent.com/1189149/121047502-c85cfa80-c7a5-11eb-9020-27065798be29.mov

### Setup used
 - NodeJS 14.17.0
 - Angular 11.2.14
 - TypeScript 4.0.2
 - Highcharts 9.1.1
 - highcharts-angular 2.10.0

**Comment by karolkolodziej** [comment]
It looks rather like an Angular/JS issue in this case.

When changing from `Chart route` to `Home` please remove that interval. Otherwise, you are trying to add something to a chart that doesn't exist anymore. I don't know how you fetch that data (because that `setInterval` was obviously a simulation) but the safety check should be placed there.

Demo: https://stackblitz.com/edit/highcharts-angular-undefined-mmfven

**Comment by nunoarruda** [comment]
@karolkolodziej Thanks for the feedback.

Yeah, the `setInterval` was used just to mimic/emulate a slow backend or slow frontend. Here's another demo with a realistic use case: https://stackblitz.com/edit/highcharts-angular-undefined-5fmhzy

https://user-images.githubusercontent.com/1189149/125472186-bc6705fb-1f69-4114-adaa-ec5538c480e4.mov

This might be a side effect of having a slow backend, having a slow frontend, or doing heavy processing to the data points but I would still expect highcharts to gracefully degrade or be more fail-proof in this situation. I'm still guessing that highcharts needs to have extra safety checks to make sure that the chart reference or the Angular component still exists.

**Comment by karolkolodziej** [comment]
I'm not quite sure if that's an actual bug because adding a simple check when you update the data solves that issue.

``` TS
   // update chart data
   if (this.chartReference.series) {
        ....
   }
```


Demo: https://stackblitz.com/edit/highcharts-angular-undefined-4btxsm

**Comment by nunoarruda** [comment]
Hi @karolkolodziej thanks for taking the time to look into this but even with a series check the issue is still there: https://stackblitz.com/edit/highcharts-angular-undefined-nwwkjq?file=src%2Fapp%2Fchart.component.ts

Taking advantage of the Dev Tools and emulating a slow connection might help you to reproduce the problem: 

https://user-images.githubusercontent.com/1189149/125630590-b2f3c422-e0cb-43d6-8954-76c05b3d5658.mov

You also need to be very quick to switch routes.

**Comment by nunoarruda** [comment]
I think I found the problem, using Promises instead of Observables to request data. Observables are cancelable, Promises are not.

For anyone having this problem, use Observables instead of Promises and unsubscribe your subscriptions on the `ngOnDestroy` hook.

Thanks anyway @karolkolodziej 👍
