### ISSUE TITLE
Cannot find name 'Fullscreen'

### ISSUE THREAD

**Issue by danieldavidraj** [highcharts/highcharts-angular#294]
Error: node_modules/highcharts/modules/full-screen.d.ts:17:21 - error TS2304: Cannot find name 'Fullscreen'.

17         fullscreen: Fullscreen;
                       ~~~~~~~~~~

**Comment by karolkolodziej** [comment]
Could you please share more details?
The most important one is how to reproduce that issue.

**Comment by KacperMadej** [comment]
Duplicate -> https://github.com/highcharts/highcharts/issues/15275#issuecomment-882092816
