### ISSUE TITLE
Improved dependency wheel data label visualisation

### ISSUE THREAD

**Issue by andhe27** [highcharts/highcharts-angular#296]
My Dependency wheel has about 100 nodes. I want to show all related labels. Is there a way to show them in an useful way?
My main goal would be a chart like this:
[Chart](https://www.highcharts.com/forum/viewtopic.php?p=151318#p151318)

I'm also open for any other useful visualization. Thanks.

**Comment by karolkolodziej** [comment]
Could you please use the [available support chanels](https://www.highcharts.com/blog/support/)?
GH is a place for us to track the bugs and ideas for improvements.
