### ISSUE TITLE
3D highcharts not working in Mi 4i Mobile

### ISSUE THREAD

**Issue by kennedymca** [highcharts/highcharts-angular#3]
Highcharts integrated with our hybrid mobile app which we developed using ionic Framework with Angular. We  have used  standalone Highcharts( Piechart and Column chart).  The problem here is there are some design issues when we load the highcharts. This issue occurs only in MI 4i mobile in both Chrome browser and hybrid app. Could you please check and let us know the issue?

Chrome version: 61
Android version:5.0

**Comment by KacperMadej** [comment]
Hi,

How can I check that? Do you have more info about the problem? Do you have a live demo?

**Comment by kennedymca** [comment]
open this link: " http://run.plnkr.co/preview/cjb2929e700053b5s9mfeuxkh/ " in your Chrome Browser in Mi4i Android Mobile

**Comment by KacperMadej** [comment]
Hi, you are using angular2-highcharts. Please file a bug report on the wrapper repository. This is not our product, we cannot fix issues in that software.

**Comment by kennedymca** [comment]
this same issue happening angular-highcharts also

**Comment by KacperMadej** [comment]
Please create a live demo or provide us a way to test the problem.

The device shouldn't be relevant unless it has some special options and bugs/features to make it act differently than other devices. The important for us is OS version and browser used. We do not have all devices, but can try to check all OS + browser version combinations that are supported.
