### ISSUE TITLE
Property 'yAxis' does not exist on type 'ExportingButtonsOptionsObject'

### ISSUE THREAD

**Issue by danieldavidraj** [highcharts/highcharts-angular#300]
```
exporting: {
      buttons: {
        contextButton: {
          enabled: false,
          align: 'left',
        },
        customButton: {
          text: 'Linear',
          onclick: function () {
            this.yAxis[0].update({
              type: 'linear'
            })
          }
        },
        customButton2: {
          text: 'Logarithmic',
          onclick: function () {
            this.yAxis[0].update({
              type: 'logarithmic'
            })
          }
        }
      }
    },
```
Getting error "Property 'yAxis' does not exist on type 'ExportingButtonsOptionsObject'"

**Comment by karolkolodziej** [comment]
Which version of Highchats are you using?
I don't see that error in the latest one.

In order to solve this:
- update to the latest version of Highcharts
- follow the answer in the [FAQ](https://github.com/highcharts/highcharts-angular#help-and-faq)

**Comment by danieldavidraj** [comment]
I am using 
@angular/cli@12.1.1,
npm - 6.14.13
"highcharts": "^9.2.2",
"highcharts-angular": "^2.10.0",

**Comment by karolkolodziej** [comment]
At the bottom of [this documentation ](https://github.com/highcharts/highcharts-angular#help-and-faq) you might find an explanation of how it should be solved.

> Property XXX does not exist on type YYY
> It is happening when you are trying to use non-existing property or one of our internal properties that are not publicly available for example axis.dataMin. To fix that you need to create your own type that will extend the default Highcharts one with the new properties. Then all you need to do is to cast the selected option / to the extended type - demo.

Demo: https://stackblitz.com/edit/highcharts-angular-property-xxx-doesnt-exist-on-type-yyy

**Comment by danieldavidraj** [comment]
```
interface ExtendedExportingButtons extends Highcharts.ExportingButtonsOptionsObject {
  yAxis: Highcharts.YAxisOptions[];
}
```
yAxis: [
      {
        type: 'linear',
        labels: {
            align: 'left'
        },
        height: '80%',
        resize: {
            enabled: true
        }
      }, 
      {
        labels: {
            align: 'left'
        },
        top: '80%',
        height: '20%',
        offset: 0
      }
    ],
    exporting: {
      buttons: {
        contextButton: {
          enabled: false,
          align: 'left',
        },
        customButton: {
          text: 'Linear',
          onclick: function (this: ExtendedExportingButtons) {
            this.yAxis[0].update({
              type: 'linear'
            })
          }
        },
        customButton2: {
          text: 'Logarithmic',
          onclick: function (this: ExtendedExportingButtons) {
            this.yAxis[0].update({
              type: 'logarithmic'
            })
          }
        }
      }
    },
```
I want to access the yAxis of 'chartOptions' from inside 'customButton'

**Comment by karolkolodziej** [comment]
Could you please describe your issue on the demo?
I don't fully get where the problem is.
Demo: https://stackblitz.com/edit/highcharts-angular-basic-line-mucavp

**Comment by danieldavidraj** [comment]
Yes that solved it, Thank you.
