### ISSUE TITLE
Cannot remove colorAxis from chart

### ISSUE THREAD

**Issue by oleksandr-kovalenko** [highcharts/highcharts-angular#301]
### Describe the bug
I need a way to enable/disable colorAxis dynamically. But unfortunately all the options I tried didn't help.

### Expected behavior
colorAxis together with points coloring disappears after I remove it from options

### Demo
https://stackblitz.com/edit/highcharts-angular-optimal-way-to-update-4nqksg

#### Steps required to recreate the problem in the demo:
I have provided 4 buttons with 4 different options that I suppose should remove the colorAxis

### Note
In other angular application I have the same functionality written without using highcharts-angular and it works as expected.

**Comment by karolkolodziej** [comment]
You have to do it the same way as you did with the title.
```TS
  option1() {
    this.chartOptions.colorAxis = {
      visible: false
    };
    this.forceUpdate();
  }
```

Demo: https://stackblitz.com/edit/highcharts-angular-optimal-way-to-update-yk5ebu

**Comment by oleksandr-kovalenko** [comment]
Your version removes colorAxis from the legend but coloring still remains. And I would like to completely remove the feature so as a result I have a regular chart as colorAxis was never used.

**Comment by karolkolodziej** [comment]
In this case, you also have to update the series with the `colorAxis` and `color` property
Demo: https://stackblitz.com/edit/highcharts-angular-optimal-way-to-update-uosbch

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
