### ISSUE TITLE
"Encourage the library authors to publish an Ivy distribution."

### ISSUE THREAD

**Issue by EnricoVogt** [highcharts/highcharts-angular#304]
During the build of a project, angular issues the following message:

`- highcharts-angular [es2015/esm2015] (git+https://github.com/highcharts/highcharts-angular.git)
Encourage the library authors to publish an Ivy distribution.`

**Comment by santosdanilo** [comment]
I could help with this. Is there any guideline on how to contribute?

**Comment by hakimio** [comment]
It was done in #305, but `"compilationMode": "partial"` also means dropping support for Angular v11 and older since [partial compilation is only compatible with Angular v12+](https://angular.io/guide/creating-libraries#publishing-libraries).

**Comment by karolkolodziej** [comment]
Resolved by #305
