### ISSUE TITLE
Property 'fullscreen' does not exist on type 'Chart'.

### ISSUE THREAD

**Issue by psanmesh** [highcharts/highcharts-angular#308]
I'm trying to add full screen option programitcally on button click. Getting an error 

ERROR in node_modules/highcharts/modules/full-screen.d.ts:17:21 - error TS2304: Cannot find name 'Fullscreen'.

17         fullscreen: Fullscreen;

recreated same at https://stackblitz.com/edit/angular-ivy-jfgwuc?file=package.json

**Comment by karolkolodziej** [comment]
You might create a separate interface that extends the existing `Chart` one as shown in the code snippet below.
```
interface ExtendedChart extends Highcharts.Chart {
  fullscreen: {
    chart: Highcharts.Chart;
    close(): void;
    open(): void;
    toggle(): void;
  };
...
  expandGraph() {
    (this.chartRef as ExtendedChart).fullscreen.toggle();
    }
  }
```
Demo: https://stackblitz.com/edit/angular-ivy-ffz6sa
