### ISSUE TITLE
colorByPoint property in PlotSunburstLevelsOptions is missing

### ISSUE THREAD

**Issue by VINCI-ALCOU** [highcharts/highcharts-angular#309]
### Describe the bug
The property "colorByPoint" is not accessible for Sunburst chart > series > levels, because the property is missing in PlotSunburstLevelsOptions of hicharts.d.ts.

### Expected behavior
Just have access to the property. 

### Demo
https://uonfu.com/q/highcharts/highcharts/16399/926502392

### Setup used
 - NodeJS version v14.17.1
 - Angular version 7.17.0
 - TypeScript version 4.2.3
 - highcharts 9.3.2
 - highcharts-angular 3.0.0

**Comment by karolkolodziej** [comment]
A similar question was asked on the main repo: https://github.com/highcharts/highcharts/issues/16399

For now, you might cast that level to `any` or [follow this example](https://github.com/highcharts/highcharts-angular#property-xxx-does-not-exist-on-type-yyy) on how you might prepare a correct interface.
