### ISSUE TITLE
Demo app does not start on IE 11

### ISSUE THREAD

**Issue by Btruckses** [highcharts/highcharts-angular#31]
I know, it's a dull browser but unfortunately we're forced to run our apps on it...
I've downloaded the demo-app, did a _npm install_ and _npm start_ as described and everything works fine on Chrome and Edge, but in **IE11** I see the "loading..." screen and the console says "**Exception thrown and not caught**" with no callstack and a reference to **_for-of.js**
(see screenshots)

![grafik](https://user-images.githubusercontent.com/29402177/40430083-8e8e5e42-5ea4-11e8-9bc3-0a1bf0b1715f.png)

![grafik](https://user-images.githubusercontent.com/29402177/40430134-b8174b3e-5ea4-11e8-8226-296805e4220b.png)

**Comment by KacperMadej** [comment]
Hi @Btruckses 

IE needs polyfills to work in Angular - it's a general problem with IE and Angular and source is not in Highcharts wrapper nor Highcharts JS library.

Please check with https://blog.angularindepth.com/angular-and-internet-explorer-5e59bb6fb4e9

**Comment by Btruckses** [comment]
Grmpf - I love this "browser"...

Thanks for your fast reply, it helped me out and following the instructions of the blogpost solved the issue.

Best regards,
Bernd

**Comment by kylebradshaw** [comment]
https://blog.angularindepth.com/angular-and-internet-explorer-5e59bb6fb4e9 link is dead :-/

**Comment by mateuszkornecki** [comment]
@kylebradshaw Thanks for providing a working link!
