### ISSUE TITLE
Supertrend indicator on line chart not working 

### ISSUE THREAD

**Issue by danieldavidraj** [highcharts/highcharts-angular#310]
For Stock charts, I am using a line chart - and passing Close Price and Date in the chart, but the technical indicator Supertrend is not working on this line chart.

**Technology used are:**

Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

**Comment by karolkolodziej** [comment]
Could you please recreate the issue in some online code editor that I can work on it and understand it better?
