### ISSUE TITLE
Indicators opening on multiple charts

### ISSUE THREAD

**Issue by danieldavidraj** [highcharts/highcharts-angular#311]
I am using highcharts-angular@2.10.0 and have two stock charts in my angular project.

1. Candlestick chart
2. Line chart

I have enabled GUI in both charts but when I click on indicators in one chart, the indicators window opens on both the charts.

How can I make them independent?

**Comment by karolkolodziej** [comment]
It looks like a standard support question. 
Could you please recreate that issue in some of the available support channels?
Please keep this GH as a platform for bug tracking.

Support: https://www.highcharts.com/blog/support/
