### ISSUE TITLE
Click event on datalabel for Line Chart does not return the point value or does not trigger chart click event

### ISSUE THREAD

**Issue by tanmaya-git** [highcharts/highcharts-angular#312]
Hi , 

I've tried the click event with data labels enabled for all charts. On clicking the data label for charts it return the point object with the series and data labels information. Only for line chart however on clicking the data label it does not fire the highchart point event instead just a mouse pointerclick event without any series details or point object . It just returns the xaxis an yaxis value. 

sample html code:

<highcharts-chart 
  [Highcharts]="Highcharts"
  [constructorType]="chartConstructor"
  [options]="chartOptions"
 (click)= "onChartClick($event)"
  [(update)]="updateFlag"
>
</highcharts-chart>

**Comment by karolkolodziej** [comment]
Could you please modify the demo (if necessary) and explain steps on how to recreate that issue?

Demo: https://stackblitz.com/edit/highcharts-angular-basic-line-adfcfu

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
