### ISSUE TITLE
Cannot load Stock as a module: ERROR TypeError: this.Highcharts[(this.constructorType || "chart")] is not a function

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts-angular#316]
Is it related to this? https://github.com/highcharts/highcharts-angular/issues/216

### Describe the bug
As in the title.

### Demo
https://stackblitz.com/edit/highcharts-angular-stock-bmcsle?file=src/app/app.component.ts

### Workaround
Override Highcharts by Highcharts by `Highcharts._modules['masters/highcharts.src.js']`
```
export class AppComponent {
  Highcharts: typeof Highcharts = (Highcharts as any)._modules['masters/highcharts.src.js'];
```
or... load Stock directly, not as a module.

### Version
Tested also with Highcharts v10.0.0 and highcharts-angular 3.0.0

**Comment by karolkolodziej** [comment]
It looks like some error specific to the `stackblitz` code editor.
I don't that that in [codesandbox](https://codesandbox.io/s/peaceful-chaum-r5fcbs?file=/src/app/app.component.ts) nor locally ([demo app](https://github.com/highcharts/highcharts-angular#demo-app)).

Adding the Stock module after importing the core of Highcharts is the correct way of doing it.
```
import * as Highcharts from 'highcharts';
import HC_Stock from 'highcharts/modules/stock';

HC_Stock(Highcharts);
```

PS. Please note that the `isHighcharts` flag should be only used on the server-side, not in the browser.

**Comment by karolkolodziej** [comment]
However, if you are using it on the server-side instead of importing the whole Highcharts module like this
`import * as Highcharts from 'highcharts';` 
please use 
`import Highcharts from 'highcharts';`

Demo: https://stackblitz.com/edit/highcharts-angular-stock-9yx4iv

**Comment by karolkolodziej** [comment]
Closed due to inactivity.

**Comment by borisdaev** [comment]
> > However, if you are using it on the server-side instead of importing the whole Highcharts module like this `import * as Highcharts from 'highcharts';` please use `import Highcharts from 'highcharts';`
> > Demo: https://stackblitz.com/edit/highcharts-angular-stock-9yx4iv
> 
> Can confirm on the latest Angular v17!

I am facing this issue,

ERROR TypeError: Cannot read properties of undefined (reading 'Core/Globals.js')
    at HC_Stock (c:/Users/User/source/jackpots-guru/frontend/node_modules/highcharts/modules/stock.js:9:539)
    at eval (c:/Users/User/source/jackpots-guru/frontend/projects/jackpots-landing-page/src/app/components/line-chart/line-chart.component.ts:7:1)
    at async instantiateModule (file:///C:/Users/User/source/jackpots-guru/frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50861:9)

 can you please provide an example code that implements SSR in Angular version 17 using standalone components?

**Comment by karolkolodziej** [comment]
see: https://github.com/highcharts/highcharts-angular/issues/372
