### ISSUE TITLE
Can't update view-by-price using highcharts-angular

### ISSUE THREAD

**Issue by NavePnow** [highcharts/highcharts-angular#317]
Hi dev,

I create app-historical component for highcharts
![image](https://user-images.githubusercontent.com/39482599/158332622-46d7ac27-8ae6-4042-a134-9d3102203d30.png)

Whenever the input changes, I want to update the series.
Here is my html config defined in app-historical component.
![image](https://user-images.githubusercontent.com/39482599/158332434-68c6836f-6951-43a4-9f12-3a84ec06cbea.png)

And the most important ts file defined in app-historical component.
[https://gist.github.com/NavePnow/815bcb ... be97643f29](https://gist.github.com/NavePnow/815bcbbe165d08015c0e37be97643f29)

When loading the component for the first time, everything is fine. But when I want to navigate to other route link, which will fetch the data from the Server and refresh the historical component . I got error:
![image](https://user-images.githubusercontent.com/39482599/158332767-9191244b-d810-4ec7-977c-dc9381681bf8.png)
I think this problem is caused by volume-by-price so I comment and everything is fine. But I need to make it work. Could you please help me out.

**Comment by karolkolodziej** [comment]
Indeed the VBP indicator is a bit special because it calculates itself after the main series and extremes are ready.
However, I was not able to recreate that error. Could you please modify the demo below that I get the same error?

Demo: https://stackblitz.com/edit/highcharts-angular-stock-indicators-lvp11v

**Comment by NavePnow** [comment]
Ohhhh bro, I just follow the first demo on [https://www.highcharts.com/forum/viewtopic.php?f=12&t=48326&p=174802#p174802](url), which I also post the question there and I make it work!
I used series.destroy() and addSeries to handle the volume-by-price, which kinda brute force and it really works!!!!!!!!
