### ISSUE TITLE
Synchronized chart example out of date

### ISSUE THREAD

**Issue by StojanovicMilos** [highcharts/highcharts-angular#319]
Hi,

I'm posting for the first time, so pardon if I made any mistakes. I really like the highcharts wrapper for angular, but I suggest to update the example to be compatible with most recent versions.

### Describe the bug
Synchronized chart example uses highcharts 7 and highcharts-angular 2.3.1, but when it's updated to highcharts 10 and highcharts-angular 3.0.0, the example does not compile anymore.

### Expected behavior
Example should work as it does in the older version.

### Demo
https://codesandbox.io/s/angular-forked-8kpc8m?file=/package.json
in case that link doesn't work for whatever reason, please use the link from the readme (https://codesandbox.io/s/5wwz8qy1l4) and change highcharts and highcharts-angular versions in package.json.

**Comment by karolkolodziej** [comment]
That is actually a very good point! 
Thank you for pointing that out.

In the next week, I'm going to update each and every demo.

**Comment by StojanovicMilos** [comment]
Hey, thanks for the quick reply. I'm looking forward to the update.

**Comment by karolkolodziej** [comment]
Resolved by https://github.com/highcharts/highcharts-angular/pull/320
