### ISSUE TITLE
Some Charts not working ?

### ISSUE THREAD

**Issue by codemonkeyneo** [highcharts/highcharts-angular#32]
Just wondering if this wrapper is limited or I am doing something wrong. I would like to use the WindRose chart within my Angular 5 application.

I have copied the example and have setOptions to the same as shown on the website for example

https://www.highcharts.com/maps-demo/polar-wind-rose

my angular componenet ts is as follows

```
import { Component, OnInit } from '@angular/core';
import * as Highcharts from 'highcharts';

@Component({
  selector: 'app-wind-rose',
  templateUrl: './wind-rose.component.html',
  styleUrls: ['./wind-rose.component.scss']
})
export class WindRoseComponent implements OnInit {

  Highcharts = Highcharts;
 
  chartOptions = {
    data: {
      table: 'freq',
      startRow: 1,
      endRow: 17,
      endColumn: 7
    },
      chart: {
        polar: true,
        type: 'column'
    },

    title: {
      text: 'Wind rose for South Shore Met Station, Oregon'
    },

    subtitle: {
      text: 'Source: or.water.usgs.gov'
    },

    pane: {
      size: '85%'
    },

    legend: {
      align: 'right',
      verticalAlign: 'top',
      y: 100,
      layout: 'vertical'
    },

    xAxis: {
      tickmarkPlacement: 'on'
    },

    yAxis: {
      min: 0,
      endOnTick: false,
      showLastLabel: true,
      title: {
        text: 'Frequency (%)'
      },
      labels: {
        formatter: function () {
          return this.value + '%';
        }
      },
      reversedStacks: false
    },

    tooltip: {
      valueSuffix: '%'
    },

    plotOptions: {
      series: {
        stacking: 'normal',
        shadow: false,
        groupPadding: 0,
        pointPlacement: 'on'
      }
    },
  }

  constructor() { }

  ngOnInit() {
    
  }

}
```

And then in the HTML

```
<highcharts-chart [Highcharts]="Highcharts"
                  [options]="chartOptions"
                  style="width: 100%; height: 400px; display: block;"></highcharts-chart>
```

Is the chart type supported ? 

I can get hte basic example working for a line graph using series data.

Any help would be appreciated , thank you.

**Comment by codemonkeyneo** [comment]
Spend a good hour this morning and can see that its the highcharts-more feature and data that is required.

So basically adding the following to the top of my componet fixes the issue.

```
require('highcharts/modules/data')(Highcharts);
require('highcharts/modules/exporting')(Highcharts);
require('highcharts/modules/windbarb')(Highcharts);
require('highcharts/highcharts-more')(Highcharts);
```
Now to hopefully carry on and not tackle any other issues :)

**Comment by KacperMadej** [comment]
Thank you for sharing the solution.

**Additionally:**
When trying to recreate a demo please check available live demos (e.g. inJSFiddle) to check required modules. See HTML section here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/polar-wind-rose/

**Comment by codemonkeyneo** [comment]
no worries ,  it was the fiddles that prompted me to think about the other modules... because of creating the app in angular I was unsure about the way to do it correctly but when I get chance will definitely be posting an article and link back to my Angular 5 and Highcharts adventure :)

Cheers
