### ISSUE TITLE
Firefox height problem

### ISSUE THREAD

**Issue by geel97** [highcharts/highcharts-angular#321]
### Describe the bug
On Firefox the graph is not displayed correctly. The div is squashed and you can only glimpse the title of the graph.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/8235122/163987643-8b4bbe00-aec4-446b-b7af-730d0ad3f741.png">

### Expected behavior
The graph should be visible correctly.

### Demo
See the demo in the [README.md](https://github.com/highcharts/highcharts-angular/blob/master/README.md#online-examples) file.
For example this one: https://highcharts-angular-line.stackblitz.io/

#### Steps required to recreate the problem in the demo:
1. Just open the demo.

### Setup used
 - NodeJS 16.14.2
 - Angular 13.3.3
 - TypeScript 4.6.3
 - Firefox 98.0.2

**Comment by karolkolodziej** [comment]
Hi!
Thank you for contacting us!

As You can see in the [documentation](https://github.com/highcharts/highcharts-angular#installing):
```
Style at the bottom of the selector is optional, but browsers do not know how to display <highcharts-chart>, 
so you should set some styles.
```

So if you add `style="width: 100%; height: 400px; display: block;"` to `app.component.html` file, everything works as expected.

See that in [the working demo.](https://stackblitz.com/edit/highcharts-angular-line-te3ejn?file=src%2Fapp%2Fapp.component.html)
