### ISSUE TITLE
Error: node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts:4:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by finitekaren** [highcharts/highcharts-angular#322]
The error: This likely means that the library (highcharts-angular) which declares HighchartsChartComponent has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

I am using these versions:
Node: 16.13.2
Npm: 8.4.1
Ng: 13.1.4 

Please advise, thank you

**Comment by finitekaren** [comment]
Nvm I fixed by importing HighchartsChartModule instead of HighchartsChartComponent. May want to update the readme!

**Comment by karolkolodziej** [comment]
In the documentation, there is `HighchartsChartModule`.
Also, we use that in each of our demos. Or am I missing something here?

Readme: https://github.com/highcharts/highcharts-angular#getting-started
Demo: https://stackblitz.com/edit/highcharts-angular-line?file=src%2Fapp%2Fapp.module.ts
