### ISSUE TITLE
./node_modules/highcharts-angular/fesm2015/highcharts-angular.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):

### ISSUE THREAD

**Issue by fensefernando** [highcharts/highcharts-angular#325]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
I create new angular project with angular 13.2: My package.json is:

{
  "name": "testh",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "highcharts-angular": "^3.0.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.4",
    "@angular/cli": "~13.2.4",
    "@angular/compiler-cli": "~13.2.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.5.2"
  }
}

And when I start project with ng serve, it generate error:

./node_modules/highcharts-angular/fesm2015/highcharts-angular.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)

### Expected behavior
Not present bug

### Demo
Please provide live demo of the problem or provide any other way to recreate the problem.

#### Steps required to recreate the problem in the demo:
1. ...

### Setup used
 - NodeJS version ... 16.14.0
 - Angular version ...  13.2.7
 - TypeScript version ...
etc.

**Comment by karolkolodziej** [comment]
Unfortunately but I was not able to recreate that issue.

I created a fresh Angular project, then I added `highcharts ` and `highcharts-angular`.
And I was able to compile it with `ng serve`.
Please try removing the `node_modules` folder and reinstalling them once again.

**Comment by karolkolodziej** [comment]
Closed due to inactivity.
