### ISSUE TITLE
Drilldown line chart into multiple series

### ISSUE THREAD

**Issue by sergiotome** [highcharts/highcharts-angular#326]
Enable drilldown in Line charts into multiple series. Line charts by default only drilldown into one serie. However, with the js version of Highcharts you can use the drilldown event to manipulate that and add additional series using the addSingleSeriesAsDrilldown and applyDrilldown functions. None of those functions are available on the typescript/angular version of the chart object though, so it seems impossible to implement something like what is implemented here: http://jsfiddle.net/49q18Lp3/4/ 

Here is a sample use case:
  - A line chart shows only one line with the total sales for the year, month by month.
  - When clicking in one of the points, the chart drills down displaying multiple lines with the sales for each different product

If there is a simple way to implement this in an angular app using highcharts angular I'd appreciate your help, since I've been struggling with it for a couple of days already.

Thanks,
Sergio

**Comment by karolkolodziej** [comment]
These methods are not publicly available thus you have to add them to the existing interface.

Demo: https://stackblitz.com/edit/highcharts-angular-line-w7o8wb

For the future reverence, with questions like this please contact us [through available support channels.](https://www.highcharts.com/blog/support/). 
We mainly use GH to track bugs/features.
