### ISSUE TITLE
Angular Server-side rendering (SSR) - issue

### ISSUE THREAD

**Issue by dineshmaths1** [highcharts/highcharts-angular#327]
while npm run dev:serve-ssr

Am getting this error.
how to fix?

Compiled successfully.
C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:56687
b=b?b._modules:{};g(b,"Series/HollowCandlestick/HollowCandlestickPoint.js",[b["Core/Series/SeriesRegistry.js"]],function(b){var c=this&&this.__extends||function(){var b=function(a,e){b=Object.setPrototypeOf||{proto:[]}instanceof Array&&function(b,a){b.proto=a}||function(b,a){for(var e in a)a.hasOwnProperty(e)&&(b[e]=a[e])};return b(a,e)};return function(a,e){function c(){this.constructor=a}b(a,e);a.prototype=null===e?Object.create(e):(c.prototype=e.prototype,new c)}}();return function(b){function a(){var a=
^

TypeError: Cannot read properties of undefined (reading 'Core/Series/SeriesRegistry.js')
at C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:56687:78
at Module.5758 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:6175:76)
at webpack_require (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:247176:42)
at Module.90158 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:1610:80)
at webpack_require (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:247176:42)
at Module.36747 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:1731:77)
at webpack_require (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:247176:42)
at Module.28061 (C:\Users\Nirali\Documents\marketsmojo\technical-repo-gui\mojotechnicals\dist\mojotechnicals\server\main.js:1868:69)

**Comment by karolkolodziej** [comment]
Can you please provide more details about your environment?

In the meantime please try to reinstall the `node_modules`.

**Comment by dineshmaths1** [comment]
> Can you please provide more details about your environment?
> 
> In the meantime please try to reinstall the `node_modules`.

{
  "name": "mojotechnicals",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "dev:ssr": "ng run mojotechnicals:serve-ssr",
    "serve:ssr": "node dist/mojotechnicals/server/main.js",
    "build:ssr": "ng build && ng run mojotechnicals:server",
    "prerender": "ng run mojotechnicals:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/localize": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/platform-server": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@ng-bootstrap/ng-bootstrap": "^12.1.1",
    "@nguniversal/express-engine": "^13.1.1",
    "@popperjs/core": "^2.10.2",
    "autoprefixer": "10.4.5",
    "bootstrap": "^5.1.3",
    "bootstrap-icons": "^1.8.3",
    "express": "^4.15.2",
    "highcharts": "^10.1.0",
    "highcharts-angular": "^3.0.0",
    "ngx-cookie-service": "^14.0.0",
    "ngx-marquee": "^13.2.1",
    "rxjs": "~7.5.0",
    "swiper": "^8.1.4",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.4",
    "@angular/cli": "~13.3.4",
    "@angular/compiler-cli": "~13.3.0",
    "@nguniversal/builders": "^13.1.1",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.10.0",
    "@types/lodash": "^4.14.182",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.6.2"
  }
}

environment dev

**Comment by karolkolodziej** [comment]
Closing as unable to recreate.
