### ISSUE TITLE
Cursor update only works on first series

### ISSUE THREAD

**Issue by Noppey** [highcharts/highcharts-angular#331]
"highcharts": "^10.2.1",
"highcharts-angular": "^3.0.0",

When updating my Highstock column chart using [updateFlag]="true", I'm changing the cursor with:
`this.chartOptions.plotOptions.series.cursor = 'default';`

When having multiple series, this only works on the first series in the chart.

**Comment by karolkolodziej** [comment]
Hi @Noppey.

Unfortunately, I was not able to recreate that- [demo](https://stackblitz.com/edit/highcharts-angular-update-optimal-way-kc41p6).

Could you please update the demo so that the issue is visible?

**Comment by Noppey** [comment]
Set the cursor to 'default' instead of undefined, then the behavior occurs.

**Comment by karolkolodziej** [comment]
From what I can see this issue is replicable without the Angular - [demo](https://github.com/highcharts/highcharts/issues/17878).

As a workaround, I can recommend updating each series separately or doing what I did in the demo above.

**Comment by karolkolodziej** [comment]
I reported that issue on the main repo: https://github.com/highcharts/highcharts/issues/17878
