### ISSUE TITLE
 CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by technbuzz** [highcharts/highcharts-angular#334]
### Describe the bug
Angular CLI throws this warning. I don't want to disable this warning by going the angular.json or project.json

### Expected behavior
I shouldn't see these warning because the angular wrapper package should only use the minimum of highcharts library.

#### Steps required to recreate the problem in the demo:
1. Follow this article https://www.highcharts.com/blog/tutorials/highcharts-with-angular-v14/

### Setup used
 - "highcharts": "^10.3.1",
    "highcharts-angular": "^3.0.0",
 - Angular version 14

**Comment by karolkolodziej** [comment]
Hi @technbuzz!

The warning that you are having is actually not connected to the wrapper itself but rather to how the `highcharts` module is imported.
It is a part of a bigger discussion that we are having internally on which we are working right now.

The warning is correct and should be resolved but if you would like to get rid of it you can add:
```JSON
            "allowedCommonJsDependencies": [
              "highcharts"
            ],
```

**Comment by technbuzz** [comment]
Thanks for addressing. Can you make this information visible somewhere in readme, **that this is a known issue and team is working on it**?

**Comment by karolkolodziej** [comment]
Sure! I will add this information later this week ;)

**Comment by Blackscr33n** [comment]
Hello @karolkolodziej is this now fixed with version 10.3.2?
Asking because we still get the warnings for modules like:
`highcharts/highstock`
`highcharts/indicators/indicators-all`
`highcharts/modules/annotations-advanced`
`highcharts/modules/drag-panes`
and a bunch of other modules.

Thanks

**Comment by nunoarruda** [comment]
You can now get rid of this warning by using the latest version of `highcharts` (10.3.3 as of writing this) and using its ECMAScript modules.

Basically, replace:
```TS
import * as Highcharts from 'highcharts;
```
with:
```TS
import Highcharts from 'highcharts/es-modules/masters/highcharts.src.js';
```

**Comment by karolkolodziej** [comment]
I feel like this issue was addressed by your PR and there is no need for putting that in the readme.
