### ISSUE TITLE
Solid gauge doesn't update properly

### ISSUE THREAD

**Issue by BojanKogoj** [highcharts/highcharts-angular#335]
### Describe the bug
When adding solid gauge series later (from API call or setTimeout) it doesn't display it. When we were using [angular-highcharts](https://www.npmjs.com/package/angular-highcharts) this wasn't the issue (we're migrating to this library). If added without delay, it works as expected.

### Expected behavior
Second solid gauge to be visible

### Demo
[Stackblitz example](https://stackblitz.com/edit/highcharts-angular-runoutsideangular-q4tcnl?file=src/app/app.component.ts)

### Setup used
 - Angular 14.2.2
 - highcharts 10.3.1
 - highcharts-angular 3.0.0

**Comment by karolkolodziej** [comment]
Please add `oneToOne` flag- [demo](https://stackblitz.com/edit/highcharts-angular-runoutsideangular-9ex58q).

Read more about that option- [docs](https://github.com/highcharts/highcharts-angular#options-details).

**Comment by BojanKogoj** [comment]
That worked, thanks.
