### ISSUE TITLE
highcharts-angular + highcharts/es-modules/masters/highstock breaks Angular compilation

### ISSUE THREAD

**Issue by nunoarruda** [highcharts/highcharts-angular#337]
### Describe the bug
Using this highcharts-angular wrapper with the default highcharts es-module works fine but if you use highstock es-module instead it will break the Angular compilation. It throws a bunch of type errors:

```
Type 'typeof import("/Users/nunoarruda/Desktop/hcw-test/node_modules/highcharts/highcharts.src")' is not assignable to type 'typeof import("/Users/nunoarruda/Desktop/hcw-test/node_modules/highcharts/highcharts")'.
  Types of property 'chart' are incompatible.
  etc...
```
<img width="790" alt="Screenshot 2023-01-23 at 16 44 27" src="https://user-images.githubusercontent.com/1189149/214098765-f0e5f9ab-d262-4aec-b59b-7e546acf186c.png">
<img width="809" alt="Screenshot 2023-01-23 at 16 47 20" src="https://user-images.githubusercontent.com/1189149/214098900-a713c308-62a1-4d81-9764-c2e9ddd2cb33.png">

### Expected behavior
Successful compilation.

### Demo
I could not reproduce this issue with a StackBlitz demo so I'm attaching an Angular project instead: [hcw-test.zip](https://github.com/highcharts/highcharts-angular/files/10481904/hcw-test.zip)

#### Steps required to recreate the problem in the demo:
1. Open the hcw-test folder on a terminal/command line
2. Run `npm install`
3. Run `npx ng serve -o`

### Setup used
 - NodeJS version v18.13.0
 - Angular version v15.1.0
 - TypeScript version v4.9.4
 - highcharts version v10.3.3
 - highcharts-angular version v3.0.0

**Comment by hihajdus** [comment]
Hi @nunoarruda , thanks for reaching out to us!

I prepared corrected [demo](https://stackblitz.com/edit/highcharts-angular-line-9w8bnk?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts), according to the [documentation](https://github.com/highcharts/highcharts-angular#hello-world-demo).

At HTML template, constructor type need to be around braces and double quotation marks for the specified string constructor:
```
<highcharts-chart
  [Highcharts]="Highcharts"
  [constructorType]="'stockChart'"
  [options]="chartOptions"
></highcharts-chart>
```



Inside `app.component.ts` import and Highcharts property declaration should look like:

```
import * as Highcharts from 'highcharts/highstock';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  Highcharts: typeof Highcharts = Highcharts;
```

**Comment by nunoarruda** [comment]
@hihajdus thanks for the feedback but maybe I was not clear enough.

I know how to use `highcharts-angular` in the standard/documented way. I'm just trying to use `highcharts-angular` with the Highstock ESM (`highcharts/es-modules/masters/highstock.src.js`) but it looks like there are issues with the type definitions like I've shown above.

I have actually pinpointed 2 possible sources of this issue:
1. https://github.com/highcharts/highcharts-dist/blob/master/modules/stock.d.ts#L15 (manually removing the `declare module` block fixes the issue)
2. https://github.com/highcharts/highcharts-angular/blob/master/highcharts-angular/src/lib/highcharts-chart.component.ts#L2 (manually replacing `import type * as Highcharts from 'highcharts';` with `import type Highcharts from 'highcharts/es-modules/masters/highcharts.src.js';` also fixes the issue)

I'm not a TypeScript/type definition expert but my wild guesses are that there's some sort of issue with the types when using `highcharts/es-modules/masters/*` or perhaps this `highcharts-angular` wrapper needs to add type support for `highcharts/es-modules/masters/*`.

@karolkolodziej @bre1470 any ideas?

Thanks in advance.

**Comment by nunoarruda** [comment]
Oh, I think I found the exact issue.

The standard/default `highcharts` uses the "non-src" types:

```TS
declare module "../highcharts"
```

while `highcharts/es-modules/masters/*` uses the `.src.` types:
 
 ```TS
declare module "../highcharts.src"
```

Since this `highcharts-angular` wrapper uses the standard/default `highcharts` types then there is a type mismatch. So my second guess from the my previous comment was correct. This `highcharts-angular` wrapper needs type support for `highcharts/es-modules/masters/*.`.

I'll make a PR tomorrow.

**Comment by karolkolodziej** [comment]
I'm sorry for not getting back to you sooner.

You are right, that is the exact source of this issue.
There should be no difference in types between ESM and a regular one, but they come from two different bundles, making them two different TS instances.

Your fix seems to be valid but I'm going to fully test it and if it's ok I will release it later this week.
Thank you for your research and your contribution!
