### ISSUE TITLE
Not able to run inside ngfor

### ISSUE THREAD

**Issue by samir-kamble** [highcharts/highcharts-angular#34]
Hello all,

I am trying to run highcharts within ngfor loop. An array consisting of multiple input objects. Please help.

Regards,
Sam

**Comment by samir-kamble** [comment]
Resolved by passing options dynamically inside loop. Somehow it was not passing. It works like charm now.

**Comment by guilhermefarto** [comment]
@samir-kamble , could you provide an example about this application of HighCharts using ngFor? I'll need to do something like this. All the best,
