### ISSUE TITLE
Getting Issue with Angular 14 and Angular Highcharts - 3.0.0 and Highcharts -10.3.1

### ISSUE THREAD

**Issue by ravirajyaguru1** [highcharts/highcharts-angular#346]
Getting error while ng serve and ng build 

Error: node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts:24:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

`24     static ɵcmp: i0.ɵɵComponentDeclaration<HighchartsChartComponent, "highcharts-chart", never, { "Highcharts": "Highcharts"; "constructorType": "constructorType"; "callbackFunction": "callbackFunction"; "oneToOne": "oneToOne"; "runOutsideAngular": "runOutsideAngular"; "options": "options"; "update": "update"; }, { "updateChange": "updateChange"; "chartInstance": "chartInstance"; }, never, never, false, never>;`

it was working week before but now getting error

Angular :  14.0.5
highcharts: "10.3.3",
highcharts-angular: "3.1.2",

**Comment by karolkolodziej** [comment]
For Angular 14 and earlier, please use the `3.0.0` version or older.
More on that in the thread https://github.com/highcharts/highcharts-angular/issues/345
