### ISSUE TITLE
Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments

### ISSUE THREAD

**Issue by Nitesh7085** [highcharts/highcharts-angular#348]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
export declare class HighchartsChartComponent implements OnDestroy, OnChanges {
    private el;
    private _zone;
    Highcharts: typeof Highcharts | typeof HighchartsESM;
    constructorType: string;
    callbackFunction: Highcharts.ChartCallbackFunction;
    oneToOne: boolean;
    runOutsideAngular: boolean;
    options: Highcharts.Options;
    update: boolean;
    updateChange: EventEmitter<boolean>;
    chartInstance: EventEmitter<Highcharts.Chart>;
    private chart;
    constructor(el: ElementRef, _zone: NgZone);
    ngOnChanges(changes: SimpleChanges): void;
    wrappedUpdateOrCreateChart(): void;
    updateOrCreateChart(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<HighchartsChartComponent, never>;
    static ɵcmp: **i0.ɵɵComponentDeclaration<HighchartsChartComponent, "highcharts-chart", never, { "Highcharts": "Highcharts"; "constructorType": "constructorType"; "callbackFunction": "callbackFunction"; "oneToOne": "oneToOne"; "runOutsideAngular": "runOutsideAngular"; "options": "options"; "update": "update"; }, { "updateChange": "updateChange"; "chartInstance": "chartInstance"; }, never, never, false, never>;**       _Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments._
}

**Comment by karolkolodziej** [comment]
Hi @Nitesh7085.

It looks like you are not using the lates Angular version, please update angular or downgrade the `highcharts-angular` package.
See more: https://github.com/highcharts/highcharts-angular/issues/345
