### ISSUE TITLE
Upgrade the package to support to Highcharts v11

### ISSUE THREAD

**Issue by BeejeeDS** [highcharts/highcharts-angular#354]
The latest version of highcharts isn't supported yet.
When upgrading in my project I get the following error.
![image](https://user-images.githubusercontent.com/6287682/236467283-74973c49-5d01-4841-adb0-a15df073b4c2.png)

**Comment by Vazonik** [comment]
Hello @BeejeeDS, thanks for reporting the issue.

Highcharts v11 should also work with the current version of the angular wrapper, see [the simple demo](https://stackblitz.com/edit/highcharts-angular-line-v2nz7x?file=package.json,src%2Findex.html). Could you provide more information, preferably a demo created e.g. in codesandbox based on the above, so I can reproduce the problem and find its source if it still occurs?

Thanks!

**Comment by BeejeeDS** [comment]
Sorry seems like the issue is not related to Highcharts v11 at all. I'm able to use v11 together with highcharts-angular v3.0.0.
This problem seems to be caused by  highcharts-angular 3.1.0 and greater. Once i upgrade to that version the error starts to occur. Doesn't matter if Iuse highcharts v10 or v11.

My project is using Angular 14 (14.2.12) and I use ng-packgr to create a custom library which has a dependency on highcharts-angular. The error shows up when I try to generate my package.

Hope this helps.

**Comment by karolkolodziej** [comment]
@BeejeeDS You are right, in `highcharts-angular` v3.1.0 we introduced an issue for older versions of Angular.
In order to properly use `highcharts-angular` with Angular 14 you have to use the older version of that wrapper.
See more in the readme: https://github.com/highcharts/highcharts-angular#getting-started
