### ISSUE TITLE
Error with Highcharts Angular wrapper in Angular 14

### ISSUE THREAD

**Issue by kintela** [highcharts/highcharts-angular#356]
Hi
I have this in my package.json

` "@angular/core": "^14.2.0",
"highcharts": "^11.0.1",
"highcharts-angular": "^3.1.2"
`
I have this in app.module.ts

`import { HighchartsChartModule } from 'highcharts-angular';
imports: [
    HighchartsChartModule,
`

And this in my component

`<highcharts-chart 
  [Highcharts]="Highcharts"
  [options]="chartOptions"

  style="width: 100%; height: 400px; display: block;"
></highcharts-chart>

import * as Highcharts from 'highcharts';
Highcharts: typeof Highcharts = Highcharts;
  chartOptions: Highcharts.Options = {
    series: [{
      data: [1, 2, 3],
      type: 'line'
    }]
  };
`
But whe I execute ng serve -o

Error: node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts:24:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.       

24     static ɵcmp: i0.ɵɵComponentDeclaration<HighchartsChartComponent, "highcharts-chart", never, { "Highcharts": "Highcharts"; "constructorType": "constructorType"; "callbackFunction": "callbackFunction"; "oneToOne": "oneToOne"; "runOutsideAngular": "runOutsideAngular"; "options": "options"; "update": "update"; }, { "updateChange": "updateChange"; "chartInstance": "chartInstance"; }, never, never, false, never>;

Any idea, please?
Thanks

**Comment by karolkolodziej** [comment]
In `highcharts-angular` v3.1.0 we accidentally introduced an issue for older versions of Angular (14 and lower).

In your case please use version 3.0.0- more on that https://github.com/highcharts/highcharts-angular/issues/345

Also please find more information in the [readme](https://github.com/highcharts/highcharts-angular#general-prerequisites).
