### ISSUE TITLE
Highchart-Angular Navigator and Scroll not showing.

### ISSUE THREAD

**Issue by atulgupt** [highcharts/highcharts-angular#358]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
I have add the spline chart in my component. There I need xAxis navigator and scroll like below screenshot
![image](https://github.com/highcharts/highcharts-angular/assets/14821180/3927f004-8c48-4e39-811c-c86c8a54186e)

I have added the property. Please check my options below:
{"time":{"useUTC":false},"chart":{"type":"spline","marginTop":100,"zoomType":"","resetZoomButton":{"series":{"turboThreshold":0,"cropThreshold":10000},"position":{"x":-60,"y":30}}},"colors":["#f7a35c"],"credits":{"enabled":false},"title":{"text":""},"subtitle":{},"xAxis":{"lineWidth":1,"minorTickLength":0,"tickInterval":3600000,"tickLength":0,"type":"datetime","dateTimeLabelFormats":{"day":"%e %b","hour":"%H:%M","minute":"%H:%M","month":"%b %y","second":"%H:%M","week":"%e %b","year":" %b %y"},"labels":{"format":"{value:%d %b %H:%M:%S}"}},"yAxis":{},"tooltip":{"shared":true,"crosshairs":true,"xDateFormat":"%b %e, %H:%M:%S"},"legend":{"itemStyle":{"color":"#000000","fontWeight":"bold"},"enabled":true},"plotOptions":{"series":{"turboThreshold":0,"cropThreshold":10000},"spline":{"marker":{"enabled":true}},"showInNavigator":true},"exporting":{"width":600,"filename":"chart_2023-05-19T10:55:34+00:00","chartOptions":{"plotOptions":{"series":{"dataLabels":{"enabled":true}}}},"buttons":{"contextButton":{"menuItems":[{"text":"Export to PDF"},{"text":"Export to CSV","separator":false}]}}},"series":[],"lang":{"noData":"No Data Available"},"noData":{"style":{"fontWeight":"bold","fontSize":"15px","color":"#303030"}},"navigation":{"buttonOptions":{"enabled":false}},"scrollbar":{"enabled":true},"**rangeSelector":{"allButtonsEnabled":true,"selected":2}**,**"navigator":{"height":20,"margin":40,"enabled":true,"**adaptToUpdatedData":false,"maskInside":true,"series":{"color":"#4572A7","type":"line","step":"2","includeInCSVExport":false}}}

My chart look like below:
![image](https://github.com/highcharts/highcharts-angular/assets/14821180/497cea07-e38e-4c6f-90c5-aaebd9387c67)
 
### Expected behavior
![image](https://github.com/highcharts/highcharts-angular/assets/14821180/839d07b8-da6f-4d11-959a-f9451e6cc656)

### Setup used
 - NodeJS version: 14
 - Angular version: 14
 - TypeScript version: ~4.7.0
etc.

**Comment by karolkolodziej** [comment]
Hi @atulgupt! I don't see how you import the Highcarts library but most likely there is an issue.
Please make sure you properly import the Stock module. [More in the readme](https://github.com/highcharts/highcharts-angular#core)
