### ISSUE TITLE
Provide documentation of Highcharts Angular URL

### ISSUE THREAD

**Issue by nagarajbiradar18** [highcharts/highcharts-angular#359]
Hi Team,

Please provide the link or documentation URL of Highcharts-Angular...

I'm getting difficulties in importing modules... for ex: map, gauge, stock, Gantt

**Comment by Vazonik** [comment]
Hello,

All the most important information about the specificity of the `highcharts-angular` wrapper can be found in [the readme](https://github.com/highcharts/highcharts-angular). You can also find information about importing modules [there](https://github.com/highcharts/highcharts-angular#to-load-a-map-for-Highcharts-Maps).

In case of problems related to any specific use, do not hesitate to write to the Highcharts support channels, e.g. [our forum](https://www.highcharts.com/forum/).

Best regards
