### ISSUE TITLE
Stacked Area Chart Bug

### ISSUE THREAD

**Issue by ogabz12345** [highcharts/highcharts-angular#362]
### Describe the bug
Using Angular-Highchart, with series of type 'area', when stacking is 'normal', the chart shows correctly on load but on update of the data points the YAxis shoots up(say total of point is 10, the Yaxis draws something else say 120 and the totalpoint from the stacked is correct). 

Now the weird part is when I remove the stacking from the plotOptions, everything works fine and it updates fine, but I need it to be stacked. An Image is added so you can see what I mean by same data point but different drawing of the Yaxis

### Expected behavior
When stacking is normal, it should work same way when stacking is off, because all other charts updates aside from 'area' when stacking is added.

### Demo
Please provide live demo of the problem or provide any other way to recreate the problem.

#### Steps required to recreate the problem in the demo:
1. ...

### Setup used
 - NodeJS version  - v18.5.0
 - Angular version - v15.2
 - TypeScript version -  ~4.9.4
etc.
![Capture-2](https://github.com/highcharts/highcharts-angular/assets/30001222/da02fb16-e2ff-4a53-90f3-b29227427dce)
![Capture](https://github.com/highcharts/highcharts-angular/assets/30001222/307476c0-2ea6-4906-9247-d543af558c19)

**Comment by karolkolodziej** [comment]
Hi @ogabz12345!
As far as I know, [this should be the simplified version of your demo.](https://stackblitz.com/edit/highcharts-angular-update-optimal-way-yayb9q

Can you please elaborate on how to recreate the issue you are showing?

Also, what do you mean by:
> When stacking is normal, it should work same way when stacking is off,

**Comment by ogabz12345** [comment]
So it's somewhat related to the stackblitz, so I have an area chart with series that has 4 objects e.g. [{}, {}, {}, {}], if the total of a data point is 5, it means we would have the Y axis at point 5 because it's stacked on one another. If I remove the first data and append a new one at the end using a push and say the total is now 15, the Yaxis(height of the point) should be at 15 but it ends up being at say 40/50 and if I append again it goes to say 100/200 and it just keeps getting taller.


What I mean by that statement '_When stacking is normal, it should work same way when stacking is off_' is that when I set plotOptions to `   plotOptions: {
                        area: {
                            stacking: 'normal',
                        }
                    },`
                    
                    That's when we have this issue, If I don't set this it means we have charts overlapping each other which makes it not stacked, the charts updates fine without any issue.
                    
                    Let me know if there's anything else you need.

**Comment by karolkolodziej** [comment]
@ogabz12345 are you sure that you properly updated the points in the series?
When I simplify the demo and change the way you update points it behaves as intended. 
Could you please verify that- [demo](https://stackblitz.com/edit/highcharts-angular-update-optimal-way-xgmx1t?file=src%2Fapp%2Fapp.component.ts)?
Please check the `this.tempValue += 1;`

**Comment by karolkolodziej** [comment]
If everything updates properly I don't understand where the issue is. 
What do you mean by saying `in a funny way`?

**Comment by karolkolodziej** [comment]
You are right, I've noticed something suspicious here but could you please create a minimal demo with your example?
There is a chance that the data is not updated properly.  I also suspect that it might not be related to the wrapper.

**Comment by ogabz12345** [comment]
Okay, let me try and see how I can replicate our exact use case.

**Comment by karolkolodziej** [comment]
Thank you for explaining how it works it looks legit but right now I don't see any issue with it.

**Comment by ogabz12345** [comment]
Let me think of a way to replicate it and revert. @karolkolodziej

**Comment by karolkolodziej** [comment]
@ogabz12345 if you think it might not be related to Angular and the wrapper, feel free to prepare it in the JS 😉

**Comment by ogabz12345** [comment]
Hi @karolkolodziej I finally figured out the issue, so sometime the updates comes with same time(X-axis) and same value(Y-axis), so when it comes at a repeated time we have them stacked on each other coz they are on the same X-axis and the values add up which is why we have the spike. I just did a check to check the old-time and new-time if its same don't plot.

 Do you guys have a way to make it plot only unique values on both axis? else I think the ticket can be closed.
 
 Thanks again.

**Comment by karolkolodziej** [comment]
Please check how the `oneToOne` property works- [docs](https://github.com/highcharts/highcharts-angular#options-details). 
This might require you to declare a unique ID for each point but if the update method finds the same points, it will not be duplicated and stacked multiple times.

**Comment by ogabz12345** [comment]
@karolkolodziej how do you declare a unique ID for each point? didn't find any example in the docs.

**Comment by karolkolodziej** [comment]
It can be declared in the data as shown in the[ API documentation.](https://api.highcharts.com/highcharts/series.line.data.id)

**Comment by ogabz12345** [comment]
@karolkolodziej Won't this affect the performance? considering thousands of data points being rendered?
