### ISSUE TITLE
Disappearing breadcrumbs after setting the update flag to true

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts-angular#364]
### Describe the bug
Breadcrumbs disappear after setting the update flag to true.

### Demo
https://stackblitz.com/edit/highcharts-angular-basic-sunburst-au7con-ekyb34?file=src%2Fapp%2Fapp.component.html

#### Steps required to recreate the problem in the demo:
1. Click on the `Level 2.2` node.
2. Hover over the `Hover me` span above the chart.
3. Watch how breadcrumbs disappear.

**Comment by karolkolodziej** [comment]
It looks like a Highcharts issue- [a simplified demo to JS.](https://jsfiddle.net/BlackLabel/zjro83Lt/)

**Comment by kamil-musialowski** [comment]
Issue moved to general Highcharts repo: https://github.com/highcharts/highcharts/issues/19616
