### ISSUE TITLE
oneToOne latest change is not reflected on installed package

### ISSUE THREAD

**Issue by renatoly** [highcharts/highcharts-angular#37]
I tried installing the package even with the latests dev branch, and still the oneToOne change added because of issue 20 (Update series dynamically #20) is not there.  It says it will be added for next release. Couldn't there be a patch release for that minor change. I edited the HighchartsChartComponent class myself, but my application would brake, when other devs update/install highchats-angular. Thank you

**Comment by pawelfus** [comment]
Hi @renatoly 

Thank you for reporting this issue. You are right, it looks like fix for #20 is not included in v1.0.2. We will  bump version to v1.0.3 and release it soon.

**Comment by PatrickTLK** [comment]
+1 would really appreciate that release

**Comment by KacperMadej** [comment]
Done with version 2.0.0
