### ISSUE TITLE
unable to update series via ChartOptions

### ISSUE THREAD

**Issue by DNDevCode** [highcharts/highcharts-angular#375]
### Describe the bug
I have two buttons. When we click to the first button i send data to display one line serie on chart. it work correctly.
When we click the second button i send data to display two series. we try to juste update the current Options tu changes only series, by remove the one old one (first button) and add the two new one (generated by the second button) . the purpose is to keep the same actual options like zooming for exemple. But unfortunatly this not working  still display only one series. 

If we click first on second button , highchart display correctly 2 series, but when we click on the first button (only one serie) hichchart steel display two chart instead of of

### Expected behavior
When display one serie and then try to update the data to show two series (by removing the old one and replacing it the two one) should display the two one series and keep the actual options like zooming 

### Demo

https://stackblitz.com/~/github.com/DNDevCode/highChartTests

### Setup used

see stackblitz demo for more detail

**Comment by karolkolodziej** [comment]
Hi @DNDevCode! 

Thank you for preparing the demo and explaining everything in such detail.
Please add the `oneToOne` flag to the `highcharts-chart` component and set it to true -this resolves your issue.
[Read more about it in the docs.](https://github.com/highcharts/highcharts-angular?tab=readme-ov-file#options-details)

**Comment by DNDevCode** [comment]
Great, thank you very for you reply, it works better with your solution
