### ISSUE TITLE
Unable to override overflow css value for context menu

### ISSUE THREAD

**Issue by Tlac** [highcharts/highcharts-angular#379]
### Describe the bug
My chart is in a div with a height that is too small for the context menu. When I open the menu, the bottom part of it is cut off. I have tried various solution to make the context menu overflow with `overflow: visible!important;` but when I check on the css property of the container, it has the property `overflow: hidden;`. Even when I try to manually change it to visible in the html viewer in the browser, it the overflow changes back to hidden when I open and close the menu. If there is another of way solving this, that would be fantastic also. Thank you in advance!

### Expected behavior
I would like to be able to override the overflow css for the container.

### Demo

https://github.com/highcharts/highcharts-angular/assets/17193168/265a1659-09b3-4443-81fc-fb7ccf44c597

#### Steps required to recreate the problem in the demo:
1. Create a chart in a div
2. Resize the height of the div so that the context menu has a larger height
3. Open the context menu

### Setup used
 - NodeJS version v18
 - Angular version v16
 - TypeScript version v4.9.5
 -  highcharts-angular v3

**Comment by karolkolodziej** [comment]
Hi @Tlac! 
Could you please update[ the demo ](https://stackblitz.com/edit/highcharts-angular-line-65ef1z?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css)so the issue is visible?
I was not able to recreate it.

**Comment by Tlac** [comment]
I'm sorry, this is my bad. When I was trying to recreate it in the demo, I found that one of the parent divs housing the chart was also applying the overflow hidden, I unchecked it on the browser and it overflowed. I believe that's the issue. Thank you again for your time and help!

![image](https://github.com/highcharts/highcharts-angular/assets/17193168/83667201-a64f-4d38-9e53-6f4d9b4c7c93)
