### ISSUE TITLE
Fix type of chartInstance emitter

### ISSUE THREAD

**Issue by Nosfistis** [highcharts/highcharts-angular#380]
### Describe the bug
The `(chartInstance)` EventEmitter does not mention that it might emit a `null` value. This happens on component destroy, where the emitter emits a `null` value.

### Expected behavior
Either the emitter should not emit a `null` value, or the `(chartInstance)` emitter should include it in its type declaration.

**Comment by karolkolodziej** [comment]
Hi @Nosfistis! 
You are right! Thank you for reporting this!

**Comment by ivankokan** [comment]
@karolkolodziej, please update the docs as well; it mentions only the creation, not the destruction.

https://github.com/highcharts/highcharts-angular/blob/65ff141ee8c11b94d8b86abeba24ff315c920186/README.md?plain=1#L234

**Comment by PowerKiKi** [comment]
Documentation is updated in #402
