### ISSUE TITLE
Support latest angular versions

### ISSUE THREAD

**Issue by SteffiKn** [highcharts/highcharts-angular#382]
Hello :)

It would great if highcharts-angular would be updated to support angular 17 and 18.
Since in angular 17 signal inputs where introduced I guess most of the users are keen to be able to update angular, which is not possible with the current version 4.0.0.

Thanks,
Steffi

**Comment by karolkolodziej** [comment]
Hi @SteffiKn! 

The `highcharts-angular` works with the Angular 17 and there is no need to update the package for that.
Could you please elaborate on how we can leverage signals in the integration?

**Comment by lmorelato** [comment]
Support to angular v18 is coming anytime soon?

**Comment by karolkolodziej** [comment]
@lmorelato The current version of `highcharts-angular` works with the Angular 18.
However, we plan to make some changes to make it more flexible in the near future.
