### ISSUE TITLE
License MIT

### ISSUE THREAD

**Issue by aidosmen** [highcharts/highcharts-angular#389]
Hello can you please update your license in npm package angular-highcharts ?
as for know it shows SEE LICENSE IN 'LICENSE' . Are you planning to get MIT license as you did for react-highcharts ?

**Comment by karolkolodziej** [comment]
Hi @aidosmen! The licence is MIT- [see the licence file.](https://github.com/highcharts/highcharts-angular?tab=License-1-ov-file#readme)
Anyway, we will take care of that in the next release and also change it in the npm.
