### ISSUE TITLE
Programatically adding multiple y-axes to highstock with navigator

### ISSUE THREAD

**Issue by SirZdanius** [highcharts/highcharts-angular#39]
Hi,

I have an issue, but I might simply be doing something wrong. My requirement is for a trend where the user can add or remove custom y-axes during runtime.

What I've been doing is constructing the axis configuration objects and pushing them into the yAxis array in the configuration. I also set the update option before adding each object, and the objects themselves are assembled and added correctly.

The problem is that the first axis I add is displayed as if it applies to the navigator instead of the main plot, and any subsequent ones are ignored (though they correctly appear in the configuration object).

![y axis navigator](https://user-images.githubusercontent.com/37931360/42163309-477a831e-7e02-11e8-90a0-be36221a6263.png)

When I add the same axis manually into the initial configuration object, it displays correctly. However, any dynamically added ones follow the same pattern from that point onward (first one added is displayed in the navigator and the others are not displayed at all),

![y axis navigator 2](https://user-images.githubusercontent.com/37931360/42163437-dbe0ebc4-7e02-11e8-932d-3638543d8f0c.png)\

Am I doing something wrong? Should I somehow fetch the chart object and call addAxis? Seems like there must be a more straightforward angulary way to do it. Is this functionality supported with this wrapper in the first place?

Thanks in advance!

**Comment by sebastianbochan** [comment]
Hi @SirZdanius,
The github is our bugtracker. Please use our forum / stackoverflow or email for general [support](http://www.highcharts.com/support) questions.

**Comment by SirZdanius** [comment]
Thanks, will do.
