### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by pevans360** [highcharts/highcharts-angular#44]
Tried incorporating this control into several pages of an existing Angular app and noticed that memory usage kept creeping up (Chrome developer tools) while navigating around the app.  Took a snapshot of the heap ... and there were lots of Highcharts objects each around 50K in size.  It seems that when navigating off a page, the Highcharts objects were not getting picked up by GC even after clicking the 'Collect Garbage' button.  

In order to try and isolate the problem, created a variation of your sample that has 2 pages, to test the behavior when navigating.  Each page has a link to the other, so you can click back and forth and watch the memory usage continue to increase.  

Put this up on Stackblitz ([https://stackblitz.com/edit/angular-s6qpav?file=src%2Fapp%2FhcChartStd%2FhcChartStd.component.ts]).   

To duplicate the issue: 
 - go to the link above in Chrome
 - open Chrome developer tools and click on the Memory tab
 - click the garbage can icon to run GC
 - note the amount of memory on the line labelled angular-s6qpav.stackblitz.io ... (that's the project)
 - click the Toggle to Page 1/2 buttons about 10 times.  
 - click the garbage can icon again
 - note that the memory used is higher than before
 - repeat and you'll see the memory keep climbing

Since the original post, I added a couple of new pages the Stackblitz.  These are based on a slightly different version of the wrapper (hcChartStd.component.ts).  It has an ngOnDestroy event that sets the chart reference to null.  The charts are similar to those in my system.  

To access these pages, click on the Go to Users Tests link.  There are 2 pages and buttons on the pages to toggle back and forth.  

The `this.chart = null;` in `ngOnDestroy` seems to have no effect.  

EDIT: 
Adding `this.chart.destroy();` in `ngOnDestroy` seems to solve the problem.

**Comment by gregjacobs** [comment]
+1 on the `this.chart.destroy()` fix. Can you create a PR for this @pevans360?

**Comment by pevans360** [comment]
Ummm ... what's a PR?

**Comment by pevans360** [comment]
Haven't been through this process before ... I just clicked on Pull Request ... and it looks like I have to choose a branch? ... Don't really know how to proceed with it.  

In case it's not obvious, I'm a pretty unsophisticated github user.

**Comment by sebastianbochan** [comment]
@KacperMadej will you commit it?

**Comment by KacperMadej** [comment]
I'll take care of this today.
