### ISSUE TITLE
Export module implementation

### ISSUE THREAD

**Issue by kistora** [highcharts/highcharts-angular#48]
Hi,

I'm in trouble with the Hichchart export module implementation in my Angular6 app.

When I add the following line in my `index.html`:
```
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/offline-exporting.js"></script>
```

I've this error: `Highcharts is not defined`

![image](https://user-images.githubusercontent.com/29222996/42693177-8d16853a-86ae-11e8-9841-f2500015478d.png)

Can someone how to do it ?

Thanks,

Btw: everything works as expected in the module 👍

**Comment by pawelfus** [comment]
Hi @kistora 

This looks like `highcharts.js` is not included. Should be more like this:

```
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/offline-exporting.js"></script>
```

Please, create issue as a standalone demo. Without it we can only guess what is wrong.

**Comment by KacperMadej** [comment]
Modules loading for the wrapper is explained in the documentation: https://github.com/highcharts/highcharts-angular#to-load-a-module

Please provide a live demo or code that will help us recreate the problem and see demo that is stored in this repository - https://github.com/highcharts/highcharts-angular#demo-app

**Comment by attilacsanyi** [comment]
BTW to load exporting module this is working in Stackblitz which is not as written in the readme doc.
```
import Exporting from 'highcharts/modules/exporting.src';
Exporting(Highcharts);
```

**Comment by KacperMadej** [comment]
If this works then great - another way to do it. If the method suggested in documentation doesn't we have an issue to resolve. In case of the latter please provide a demo or more info and we could reopen the issue.
