### ISSUE TITLE
Load event

### ISSUE THREAD

**Issue by hunguyen75** [highcharts/highcharts-angular#55]
Hi,
I am trying to build a real-time Highchart using your library, so how do I incorporate Highchart's load event into your library?

**Comment by KacperMadej** [comment]
Hi @hunguyen75 

Highcharts API is available through options / chartOptions as explained in documentation here: https://github.com/highcharts/highcharts-angular#options-details

Chart's load event is part of the official API, so it's accessible there.

For technical support use - https://www.highcharts.com/support
For bugs in highcharts-angular report as an issue here.
