### ISSUE TITLE
Angular 6: build SRR error with highcharts-more and solid-gauge

### ISSUE THREAD

**Issue by KaJasB** [highcharts/highcharts-angular#59]
Hi Highcharts team!

I try to add Highcharts to my Angular 6 project.

```
import * as Highcharts from 'highcharts';
import * as HighchartsMore from 'highcharts/highcharts-more.src';
HighchartsMore(Highcharts);
import * as HC_solid_gauge from 'highcharts/modules/solid-gauge.src';
HC_solid_gauge(Highcharts);
```

The import seem fine and it's work well on development, but after I run build ssr I got error

`TypeError: extend is not a function`

**Comment by ps3331333** [comment]
@KaJasB How did you use `HighchartsMore` variable to render the chart?

**Comment by KacperMadej** [comment]
Hi @KaJasB 

Please add more code, because the code you provided is not causing the errors you described.
How are charts created? Where's the source of the error?

**Comment by KaJasB** [comment]
@KacperMadej @ps3331333 Sorry I'm did go to work today I will update the issue tomorrow.

**Comment by KaJasB** [comment]
@KacperMadej @ps3331333 Below is the code I implement the solid gauge.

```
//gauge.component.ts
import * as Highcharts from 'highcharts';
import * as HighchartsMore from 'highcharts/highcharts-more.src';
HighchartsMore(Highcharts);
import * as HC_solid_gauge from 'highcharts/modules/solid-gauge.src';
HC_solid_gauge(Highcharts);

.................

colors = Utils.colors;
Highcharts = Highcharts;
```

```
// gauge.component.html
<highcharts-chart [Highcharts]="Highcharts" [options]="{
    chart: {
      type: 'solidgauge',
      margin: [0, 0, 0, 0],
      backgroundColor: 'transparent',
      width: 55
    },
    title: null,
    pane: {
      size: '100%',
      center: ['50%', '50%'],
      startAngle: -130,
      endAngle: 130,
      background: {
        backgroundColor: '#efefef',
        borderColor: '#efefef',
        outerRadius: '100%',
        innerRadius: '80%',
        shape: 'arc'
      }
    },
    tooltip: {
      enabled: false
    },
    yAxis: {
      min: 0,
      max: 10000,
      stops: [
        [0, this.colors.green],
        [701 / 10000, this.colors.yellow],
        [1001 / 10000, this.colors.orange],
        [1501 / 10000, this.colors.red],
        [2501 / 10000, this.colors.purple],
        [5001 / 10000, this.colors.maroon]
      ],
      lineWidth: 0,
      tickWidth: 0,
      tickPositions: []
    },
    plotOptions: {
      solidgauge: {
        rounded: true,
        innerRadius:'80%',
        label:false,
        dataLabels: {
            enabled:false,
            borderWidth: 0,
            useHTML: true,
            y: -15
        }
      }
    },
    credits: {
      enabled: false
    },
    series: [
      {
        data: [value]
      }
    ]
  }" style="width: 100%; height: 40px; display: block;"></highcharts-chart>
```

Options was in **TS** file, since it's no need to update I pass it to **HTML** file instead.

**Comment by KacperMadej** [comment]
I have used `require` to load files and changed colors and value variables slightly, but it shouldn't influence the demo, and I'm unable to recreate the problem.

Here's a live demo: https://codesandbox.io/s/vm0q93y4p0
I have done similar in the demo of this repository with the same effects.

Please check if you could recreate the problem in the live demo or please provide Angular project to run (e.g. in codesanbox you could download a project as a zipped archive, so if you could share a similar files - that could allow recreating the problem - then please do that)

**Comment by KaJasB** [comment]
It might take me quite some time to recreate the problem. Close issue for now.
