### ISSUE TITLE
Get chart object instance of current chart

### ISSUE THREAD

**Issue by SergejSa** [highcharts/highcharts-angular#65]
Hello,

is there a possibility to get the chart object instance like in ng2-highcharts?
i have to call some methods on it for example reflow().

the global "Highcharts" object has only a array with all charts.
There should be a possibility to bind a chart object like with the options for easy api access.

**Comment by roxxid** [comment]
+1

**Comment by SergejSa** [comment]
I tried it via chartCallbackFunction but after i set the chart instance on my component property it becomes undefined for example in ngAfterViewInit.

**Comment by KacperMadej** [comment]
Hi @SergejSa 

Thank you for reporting.
Looks like a duplicate of #26
