### ISSUE TITLE
How to use solid gauge chart

### ISSUE THREAD

**Issue by tstreamDOTh** [highcharts/highcharts-angular#67]
I am getting error#17 for chart type: 'solidgauge',

**Comment by sebastianbochan** [comment]
Hi @tstreamDOTh,
Thank you for reporting. It looks like duplicate of https://github.com/highcharts/highcharts-angular/issues/59.

If problem is different, please supply us a code and reopen the case.

**Comment by tstreamDOTh** [comment]
@sebastianbochan  Thanks. It helped.
