### ISSUE TITLE
How to load 3D charts?

### ISSUE THREAD

**Issue by utkarshpanwar** [highcharts/highcharts-angular#70]
Please provide the instructions to load the 3D charts.

Thanks!

**Comment by KacperMadej** [comment]
Hi @utkarshpanwar 

Load it as any other module - https://github.com/highcharts/highcharts-angular#to-load-a-module

In case of a problem please create a live demo.

**Comment by utkarshpanwar** [comment]
Thanks, it worked by adding the line below in app.component

import * as Highcharts from 'highcharts';
require('highcharts/highcharts-3d')(Highcharts);
