### ISSUE TITLE
use of Highmap on different view

### ISSUE THREAD

**Issue by Ghanahshyam** [highcharts/highcharts-angular#74]
Hi, I am new to angular, I was following your Github link so added all dependencies of app.component.ts to my components it worked for me but when I tried to go with another component with doing same import it's not working. Can someone have any advice.

**Comment by KacperMadej** [comment]
Hi @Ghanahshyam 

For technical support about Highcharts please use available support channels: https://www.highcharts.com/support

You'll need to provide more info and code same when contacting support to get help.
