### ISSUE TITLE
Access Chart/Series Instance in legendItemClick function

### ISSUE THREAD

**Issue by domwoe** [highcharts/highcharts-angular#77]
I'd like to switch the visibility of two series at once. Thus I'd like to implement the
legendItemClick function of one of the two series to switch the visibility of the other as well.

However, I don't know how to access the series instance and call the show/hide methods.
I tried setting the visibility of the series 
`this.chart.series[1].visibility = false`
and set the updateFlag to true, but this does not change anything.

**Comment by pawelfus** [comment]
Hi @domwoe 

This way you will change a Highcharts property of Series class, not your config. If you use `this.chart.series[index]`, then you can use official API:

- [`Series.hide()`](https://api.highcharts.com/class-reference/Highcharts.Series#hide)
- [`Series.show()`](https://api.highcharts.com/class-reference/Highcharts.Series#show)
- or [`Series.setVisible(true|false|undefined)`](https://api.highcharts.com/class-reference/Highcharts.Series#setVisible)

**Comment by KacperMadej** [comment]
Hi @domwoe 

To update a chart change `options` (`[options]="chartOptions"`) and to ensure that the change will be detected set `update` (`[(update)]="updateFlag"`) to `true`. After update will be done the `update` variable will be set back to `false` by the chart component.

The chart component runs `chart.update()` that resolves all changes to single elements updates and detects what needs to be updated through that function call. However, if you need or want to update chart manually, then after getting chart instance you could call [`chart.udpate()`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) or more dedicated update like [`series.update()`](https://api.highcharts.com/class-reference/Highcharts.Series#update).

For technical questions please contact technical support - https://www.highcharts.com/support

**Comment by domwoe** [comment]
@pawelfus 
Thanks! I was so close :)
