### ISSUE TITLE
import with  npm i highcharts-angular

### ISSUE THREAD

**Issue by arekik** [highcharts/highcharts-angular#8]
What is the difference between import with : 
 **npm i highcharts-angular** and  **npm install highcharts/highcharts-angular**
When i use npm i highcharts-angular i have an error :

core.js:1427 ERROR Error: Uncaught (in promise): Error: Unexpected value 'HighchartsChartComponent' declared by the module 'XXXXXX'. Please add a @Pipe/@Directive/@Component annotation.
Error: Unexpected value 'HighchartsChartComponent' declared by the module 'BoardModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (compiler.js:485)
    at eval (compiler.js:15254)
    at Array.forEach (<anonymous>)

And whn i use npm install highcharts/highcharts-angular i dont have this error.

**Comment by narsaym** [comment]
The difference is where angular-highcharts package gets imported from
In your ``package.json`` file, **npm i highcharts-angular --save** results in:
```
"dependencies": {
    "highcharts-angular": "^0.1.0",
  }
```

While **npm i highcharts/highcharts-angular --save** results in:
  ```
"dependencies": {
      "highcharts-angular": "github:highcharts/highcharts-angular",
  }
```

In you ``app.module.ts``, make sure you are adding ``HighchartsChartComponent`` to declarations array and not the imports array inside ``@NgModule``

**Comment by arekik** [comment]
Thank you,
Ii think the probleme is  because i use in my project angular 5 so when i import with  "github:highcharts/highcharts-angular" the lib is using angular 5 so there is no probleme but when i use github:highcharts/highcharts-angular" the lib use angular 4
