### ISSUE TITLE
import PatternFill module using highcharts-angular

### ISSUE THREAD

**Issue by lramansolstie** [highcharts/highcharts-angular#80]
Using stackblitz and highcharts-angular npm module, 
I'm unable to load the PatternFills module using the documentation. 

`import * as Pattern from 'highcharts/modules/pattern-fill'
Pattern(Highcharts);`  

`Pattern is not a function` is the error displayed. 

Link to stackblitz 
[https://stackblitz.com/edit/angular-fu18ze?file=src%2Fapp%2Fhighcharts-example%2Fhighcharts-example.component.ts](url)

**Comment by KacperMadej** [comment]
Hi @lramansolstie 

Thank you for reporting about the problem.

Please load modules using `require`.
Demo: https://stackblitz.com/edit/angular-rdrrpm?file=src%2Fapp%2Fhighcharts-example%2Fhighcharts-example.component.ts

More info: https://github.com/highcharts/highcharts-angular/issues/54#issuecomment-415446662

**Comment by lramansolstie** [comment]
Thank you!
