### ISSUE TITLE
Highcharts not rendering with angular 6

### ISSUE THREAD

**Issue by vinayakbhat87** [highcharts/highcharts-angular#81]
I wanted to create a highchart.. the I took the demo app.. The demo app works fine..
i created a json variable in app.component.ts called chartOptions.. The content of the variable is from 
https://cloud.highcharts.com/create?q=4_cmG2WMT

the chart is not rendering.. Is there anything i am missing
With the same json, I can render using javascript.. ie $('#wind-rose').highcharts(chartoption_json)

**Comment by KacperMadej** [comment]
Hi @vinayakbhat87 

From the look of the JSON it seems like data module is required, so be sure to [add it](https://github.com/highcharts/highcharts-angular#to-load-a-module).
If this doesn't resolve the problem please create a live demo of the problem - you could edit this demo: https://stackblitz.com/edit/angular-rdrrpm?file=src%2Fapp%2Fhighcharts-example%2Fhighcharts-example.component.ts or this one: https://codesandbox.io/s/k24qxvzlk7
