### ISSUE TITLE
polar = true doesn't work

### ISSUE THREAD

**Issue by shdehnavi** [highcharts/highcharts-angular#82]
hi, i wanna draw polar charts and i have a problem with highcharts.
in angular and chart section of chart options, `polar = true` doesn't work and chart displays like a bar and column chart, when i want to draw any charts that used `polar = true` i have this issue.

what's the solution ?

**Comment by KacperMadej** [comment]
Hi @shdehnavi 

The polar option requires highcharts-more module. Have you loaded and initialized it [as any other module](https://github.com/highcharts/highcharts-angular#to-load-a-module)?

**Comment by KacperMadej** [comment]
Hi @shdehnavi 

The polar option requires highcharts-more module. Have you loaded and initialized it [as any other module](https://github.com/highcharts/highcharts-angular#to-load-a-module)?

**Comment by shdehnavi** [comment]
thanks for reply.

i'm using `import * as Highcharts from 'highcharts';` to import highcharts, how import highcharts-more ?

**Comment by KacperMadej** [comment]
As explained in linked documentation in my previous comment.
E.g.
`require('highcharts/highcharts-more')(Highcharts);`

**Comment by shdehnavi** [comment]
`require` is deprecated in ionic 3.9 and angular 5 using typescript.
solved:
`import * as Highcharts from 'highcharts';`
`import * as HighchartsMore from 'highcharts/highcharts-more';`
initialize:
`HighchartsMore(Highcharts);`

thank you so much <3
