### ISSUE TITLE
Multiple isolated components interference

### ISSUE THREAD

**Issue by Wandang** [highcharts/highcharts-angular#84]
Consider having 2 components for a highcharts chart.
Each component imports highchart and the extra modules needed for each chart.

What happens:

Chart configurations and status get mixed up. For example if I import the module exporting in component B, Component A does have the same extra module enabled. Is this intended? If so I should import what I need somewhere in a parent component once instead?

What should happen:

Each component should be isolated.

Maybe I am missing something?

**Comment by KacperMadej** [comment]
Hi @Wandang 
Chart components may be isolated by Highcharts instance is shared, so it's better to set it up one in a parent component and only load and use in a child components.

For Highcharts technical support please contact https://www.highcharts.com/support

**Comment by Wandang** [comment]
Before I used the angular wrapper this was not a problem :-P. If it is not specifically a wrapper behavior this can be closed

**Comment by KacperMadej** [comment]
If you have a live demo that we could check then please share a link. In general there should be a single instance of Highcharts loaded for a given page or iframe.

**Comment by Wandang** [comment]
Here is a live demo: https://stackblitz.com/edit/angular-6sjaa9

As you can see your highcharts component has no export module loaded and therefore has no export options next to its chart. When you comment out the require statements in highcharts2/highcharts2.component.ts you will get the export module loaded on your chart.

This is not intuitive to me. Since this only happens with the angular wrapper (beforehand I used pure highcharts with the imports and both components were seperate instances) I would appreciate a note in the readme clarifying that imports will be applied across all highchart instances.

And it's not only imports. Not sure if I can recreate it but yesterday I had a chartconfiguration from component B being applied to the chart of component A (with x and yaxis entries, the whole chebang).

Thanks for your time in this issue and your work in general!

**Comment by KacperMadej** [comment]
@Wandang 

Thank you for detailed comment.

The issue to-do list:
- [ ] The info about Highcharts instance being shared, so loaded modules will affect all charts should be added to avoid any confusion.

If there's anything else that could be fixed or improved please let me know.

**Comment by rinckd** [comment]
Do you have a good example of creating a public highcharts object?

This is what I did in Angular 6. I used the providedIn: 'root' to declare that the service is a singleton. Not production tested yet, but it seems to be working. I'd be open to suggestions and improvements:

```typescript
import { Injectable } from '@angular/core';
import * as Highcharts from 'highcharts';
import * as exporting from 'highcharts/modules/exporting.src';
import * as CustomEvents from 'highcharts-custom-events';
exporting(Highcharts);
CustomEvents(Highcharts);
Highcharts.setOptions({
  lang: {
    thousandsSep: ','
  }
});

@Injectable({
  providedIn: 'root'
})
export class HChartService {
  Highcharts = Highcharts;
  constructor() {}

  getHCharts() {
    return Highcharts;
  }
}
```

then in a component:

```typescript
  Highcharts: any;
  ngOnInit() {
    this.Highcharts = this.hChartService.getHCharts();
```

**Comment by KacperMadej** [comment]
Hi @rinckd 

For Highcharts technical support please contact us through available support channels: https://www.highcharts.com/support

This is a general question about Highcharts and not really a highcharts-angular issue.
When using highcharts-angular the requested feature works by default - see https://github.com/highcharts/highcharts-angular/issues/84#issuecomment-432750822
