### ISSUE TITLE
Complete documentation for all Charts

### ISSUE THREAD

**Issue by lasya-sivalenka** [highcharts/highcharts-angular#88]
Hi,

I'm wondering if I can find a proper documentation for all the available charts to be implemented in Angular

A quick help would be highly appreciated.

Thanks.

**Comment by KacperMadej** [comment]
Hi @lasya-sivalenka 

**Short answer**: all of them: https://www.highcharts.com/docs/chart-and-series-types/chart-types

(Seems like your question is about all charts in Angular, but since you have asked in Highcharts related repository then I'll assume that you are asking about Highcharts charts.)
