### ISSUE TITLE
Provide a way of changing the theme without the need of explicit injection of the entire theme

### ISSUE THREAD

**Issue by gatapia** [highcharts/highcharts-angular#89]
I think it would be great to be able to change the chart themes using highcharts-angular without requiring copy/paste of the entire theme file from the node_modules folder.

Something like adding the theme js file in the scripts array of the angular.json file would be great. This currently does not work.

**Comment by KacperMadej** [comment]
Themes should be possible to load the same way as a module based on the file structure - https://unpkg.com/highcharts@6.2.0/themes/dark-unica.js (here's how a theme looks when loaded from NPM/NodeJS), so use this docs: https://github.com/highcharts/highcharts-angular#to-load-a-module

You need entire theme to set it, half of it will only apply half of the changes - I probably missed something in your comment, please provide more info for the issue.

**Comment by gatapia** [comment]
Just tried this and it works as expected.  Thanks, and apologies for redundant issue, perhaps add to documentation.  Asked on stackoverflow and no one seemed to know either.

**Comment by KacperMadej** [comment]
Ok, thank's for the suggestion.

Marking the issue as an enhancement suggestion.

To-do list:
- [ ] required: add docs for adding themes - FAQ sections
- [ ] _optional: ?styled mode info in docs - FAQ section?_

**Comment by sebastianbochan** [comment]
Regarding to the second point of check list.
In the next release, we will publish themes as scss files in the npm.

Related topic:
- https://github.com/highcharts/highcharts/issues/9214

**Comment by TitaneBoy** [comment]
Hi everyone..I'm trying to apply an existing theme in Highcharts but I just don't understand How to do this...For example, in "node_modules/highcharts/js/es-modules/themes/", there is multiple themes. If I want to use one of them (for example, dark-unica.js) in my custom component, How can I do it ?

Thank you in advance for you answer

**Comment by gatapia** [comment]
Instructions given above by @KacperMadej is the way.  I also updated my question [stackoverflow](https://stackoverflow.com/questions/52958769/changing-themes-using-highcharts-angular/52965472#52965472) with instructions
