### ISSUE TITLE
parallel coordinates update flag not working

### ISSUE THREAD

**Issue by Wandang** [highcharts/highcharts-angular#90]
As you might know parallel coordinates cannot be updated like other charts (because of performance) and updateflag therefore does not work.

To update parallel coordinates the recommended workflow is to destroy the old and create a new chart.

How would I force a recreation/trigger (chartInstance) output with this angular wrapper?

Example blitz: https://stackblitz.com/edit/angular-bmpm8f

If you comment in the initial values of the chartOptions you can see what the result should look like. This is not happening with updateflag alone.

**Comment by Wandang** [comment]
The workaround is to just overwrite the chart object with a manually created chart: https://stackblitz.com/edit/angular-tkjn8u

`this.chart = this.Highcharts.chart(this.chart.container, this.chartOptions)`

But this is against the design of the wrapper right?

**Comment by KacperMadej** [comment]
Hi @Wandang 

Yes, this is against the design. The highcharts-angular code expect Highcharts to work correctly. Adding workaround for existing bugs in core Highcharts to the angular component code is not going to happen unless the Highcharts bug will be definitely not possible to resolve.

If you need to access chart instance you could do it like [that](https://github.com/highcharts/highcharts-angular#chart-instance).

The parallel update issue should be reported on Highcharts main repo and closed here as a duplicate.
@Wandang Do you have a link for the issue or maybe it's not reported yet? (I was not able to find it reported)

**As a workaround:**
You could destroy the chart component to destroy the chart and create a new component with new chart.

**Comment by Wandang** [comment]
@KacperMadej sry for the late reply. The issue was reported by me in the forum a year ago: https://forum.highcharts.com/viewtopic.php?p=138197&sid=2ec76e5bd78447b679faf0be7f3b83b0#p138197

It seems to be unadressed/won't resolve. 

I tried destroying the chart instance before which would not work in my favor. Destroying the chart component requires me to destroy the current component holding the chart right (ngOnDestroy)? I might create a new subcomponent with only the chart in it then.

**Comment by KacperMadej** [comment]
I must have missed that you have not set up `oneToOne` flag to update all series and axes - adding new one and removing old one. I was assuming that there was a bug in Highcharts, but it works fine.

Please add `oneToOne` - should look something like `<highcharts-chart [oneToOne]="true" `.
Here's more docs: https://github.com/highcharts/highcharts-angular#options-details

I have tested your demo and the change seems to be fixing the problem.

**Comment by Wandang** [comment]
Oh wow, let me test that. It seems I completely misunderstood the doc on that flag. I thought it might cause data inconsistencies while in reality it just overwrites the minimum amount of series to satisfy the new incoming data and removes the remaining series as needed.

> For example, if the chart has two series and we call chart.update (and this is called on each chart's data change or if updateFlag is set to true) with a configuration containing three series, one will be added

I read this as a pessimist assuming of those 3 new series only 1 will be added and the other 2 are kept with the old data resulting in inconsistent results... :laughing: 

Ok I tested it. Using the oneToOne flag in combination with the update flag and removing the new creation of a chart instance resulted in the desired updated parallel coordinate chart :)

Thanks so much @KacperMadej . Seems I had tunnelvision because of my forum post a year ago + misunderstanding reading the docs.

**Comment by KacperMadej** [comment]
Good to see the problem resolved.
Closing as resolved.
