### ISSUE TITLE
How to use addpoint() ?

### ISSUE THREAD

**Issue by tthau2010** [highcharts/highcharts-angular#92]
I want to dynamically append data into the series. How can i do it with this library?

I call an API and when the API return me the response, i will need to append the data into the series.

I have tried with e.g
`this.chartOptions.series.push('my-data');` 
it doesn't reflect in the graph.

**Comment by KacperMadej** [comment]
Hi @tthau2010 

Thank you for contacting us.

Series is not a string, so this will not work. You could change chartOptions object and set update flag (No. 5 in here: https://github.com/highcharts/highcharts-angular#options-details) to `true`. See demo app https://github.com/highcharts/highcharts-angular#demo-app

If this doesn't help please create a live demo. For technical support and live demo example see https://github.com/highcharts/highcharts-angular#help-and-faq

**Comment by wchmiel** [comment]
**@tthau2010**,

Check also this demo that might be helpful for you: [https://codesandbox.io/s/r4o90w1wxp](https://codesandbox.io/s/r4o90w1wxp).

**Comment by tthau2010** [comment]
@KacperMadej @wchmiel Thanks for the sample. I manage to do it now.
