### ISSUE TITLE
Request for Synchronized Charts Angular demo

### ISSUE THREAD

**Issue by GeorgeKnap** [highcharts/highcharts-angular#93]
Would it be possible to add a demo or documentation how to create synchronized charts with this library?
Thanks

**Comment by KacperMadej** [comment]
Hi @GeorgeKnap 

Thank you for the suggestion.
Just to be sure - you are referring to this demo https://www.highcharts.com/demo/synchronized-charts , right?

**Comment by GeorgeKnap** [comment]
@KacperMadej  Hi, yes, that demo.  I'm tring to do something similar with multiple series in each chart.

**Comment by KacperMadej** [comment]
That demo is showing one way of handling synchronized charts and events binding should be rewritten to run them Angular way. This could be done - just go through the code of the pure JS demo of Highcharts and move events related code into Angular directives or any other preferred Angular way of handling this.

I have moved events and tried to keep all previous features + added class based sync between charts, and added check in case any chart would be removed.

I have not added multiple series support - this could be done through editing of the code related to custom highlight function added to Point's prototype and code responsible for finding points that currently run hard coded for first series only.

Demo: https://codesandbox.io/s/5wwz8qy1l4

**Comment by KacperMadej** [comment]
Well, the TS definitions are not wrong - the `highlight` options is custom, so it's not included in official d.ts file. A workaround could be to use existing functions and [wrap](https://www.highcharts.com/docs/extending-highcharts/extending-highcharts) them or override them.

For a proper solution and possible options:
@bre1470 Is there an easy way to add TS definitions for custom code? Do we have or planning to have an article about extending TS definitions when creating code wrappers, custom code, plugins, etc. ?

**Comment by GeorgeKnap** [comment]
In my opinion fixing missing types from vendor libraries by adding definitions in _client_ code is really not the correct way to go. 

@KacperMadej 
If the prototype object expects to have additional properties it should contain at least something like this:
```
[key: string]: any
```
I guess the owner who provides `highlight` method should also provide extended `d.ts` as well

**Comment by KacperMadej** [comment]
@GeorgeKnap Please specify which option is missing, so we could add it. You could check the Highcharts files to ensure that an option is defined and/or check [public API](https://api.highcharts.com/highcharts/).

Synchronized charts demo is showing how extending Highcharts could allow custom features through custom code.

The `highlight` method is a part of a demo that is not a part of any Highcharts module or core code. If the synchronized charts demo were to be a module then we would have provided d.ts (and a lack of it would be an issues we would like to resolve), but it's not. We have many similar demos, that are not modules or distributed as a part of Highcharts library, and the approach explained by @bre1470 is the way to go for any of such demos and for any custom code.

Based on what you have written before I guess you will want to edit the demo I have provided to allow multiple series support, so after editing it you will be able to extend d.ts as explained in above comment - and IMHO you will be the owner of such code - meaning that you will be responsible for extending d.ts.

If extending Highcharts was not your plan in the first place please suggest an enhancement idea on Highcharts UserVoice for the demo to become a module or to include it fully in all official documentations. The most popular ideas are getting implemented. https://highcharts.uservoice.com/forums/55896-general

**Comment by GeorgeKnap** [comment]
@KacperMadej 
right, I did not realized we are not overriding existing function but creating a new one.

**Comment by KacperMadej** [comment]
@GeorgeKnap It's not used, is not defined in the demo - I forgot to remove it after trying few thing to resolve the issue. It should be gone now - https://codesandbox.io/s/5wwz8qy1l4 Thank you for catching this.

**Comment by KacperMadej** [comment]
Hi @misguided-developer-singh 

What have you tried?
It should work just fine as the synchronization is based on position in a chart and not on a axis values as you could see in code.
Please contact technical support for help: https://www.highcharts.com/blog/support/

**Comment by misguided-developer-singh** [comment]
http://jsfiddle.net/ZArZM/20/

Hi @KacperMadej,
I'm unable synchronize zoom here. Could you please help me out?

Thanks,
Amar

**Comment by KacperMadej** [comment]
Zooming works fine in the original demo if you will enable the zoom.
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/synchronized-charts/

The same applies to the Angular demo for synchronized charts that you could find in [here](https://github.com/highcharts/highcharts-angular#synchronized-charts-angular-demo).
https://codesandbox.io/s/5wwz8qy1l4
