### ISSUE TITLE
ERROR in node_modules/highcharts/highstock.d.ts(6,25): error TS2307: Cannot find module './highcharts/modules/stock'.

### ISSUE THREAD

**Issue by TitaneBoy** [highcharts/highcharts-angular#94]
Hi...When using the last version of highcharts (7.0.0) in my angular project, I got the error described in the title

![image](https://user-images.githubusercontent.com/15614466/49813989-b74ae400-fd36-11e8-8be3-b026d538335b.png)

NodeJS: v10.10.0
OS: Windows Pro 7
Highcharts: 7.0.0
Highcharts-angular: 2.3.1

Here is my package.json file:
```
"dependencies": {
    "@angular/animations": "7.1.2",
    "@angular/cdk": "7.1.1",
    "@angular/common": "7.1.2",
    "@angular/compiler": "7.1.2",
    "@angular/core": "7.1.2",
    "@angular/flex-layout": "7.0.0-beta.19",
    "@angular/forms": "7.1.2",
    "@angular/http": "7.1.2",
    "@angular/material": "7.1.1",
    "@angular/platform-browser": "7.1.2",
    "@angular/platform-browser-dynamic": "7.1.2",
    "@angular/router": "7.1.2",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "bootstrap": "4.1.3",
    "chart.js": "2.7.3",
    "chartjs-plugin-zoom": "0.6.6",
    "core-js": "2.6.0",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "highcharts": "7.0.0",
    "highcharts-angular": "2.3.1",
    "material-design-icons": "3.0.1",
    "ng-event-source": "1.0.14",
    "rxjs": "6.3.3",
    "typescript": "3.1.6",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.11.2",
    "@angular/cli": "7.1.2",
    "@angular/compiler-cli": "7.1.2",
    "@angular/language-service": "7.1.2",
    "@types/chart.js": "2.7.41",
    "@types/highcharts": "5.0.34",
    "@types/jasmine": "3.3.1",
    "@types/jasminewd2": "2.0.6",
    "@types/node": "10.12.12",
    "codelyzer": "4.5.0",
    "jasmine-core": "3.3.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "3.1.3",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "2.0.0",
    "karma-coverage": "1.1.2",
    "karma-coverage-istanbul-reporter": "2.0.4",
    "karma-firefox-launcher": "1.1.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.0",
    "karma-json-reporter": "1.2.1",
    "karma-junit-reporter": "1.2.0",
    "ngx-i18nsupport": "0.17.1",
    "protractor": "5.4.1",
    "ts-node": "7.0.1",
    "tslint": "5.11.0",
    "typedoc": "0.13.0"
  }
```

Also, when doing this in my component:

![image](https://user-images.githubusercontent.com/15614466/49814117-f711cb80-fd36-11e8-948a-4934acd6809a.png)

I have a ts error message saying this: 
`[ts] Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("c:/Personal_Data/Web-Client/node_modules/highcharts/modules/exporting")' has no compatible call signatures. [2349]`

![image](https://user-images.githubusercontent.com/15614466/49814187-1b6da800-fd37-11e8-90e6-8f93d3a58666.png)

Also, when adding series to charts like this:
`this.Highcharts.charts[0].addSeries({`
We could previously inject data in the SeriesOption with the 'data' attribute. But now, it seems that this attribute does not exist anymore (Is it true ?)

This is what I'm trying to do:
![image](https://user-images.githubusercontent.com/15614466/49814351-74d5d700-fd37-11e8-9f0d-5e3ed0948254.png)

And this is the ts error I got:
![image](https://user-images.githubusercontent.com/15614466/49814394-86b77a00-fd37-11e8-80f8-ca6155245032.png)

In Highcharts@6.2.0 version, everything was working great with my code. But when updating it to 7.0.0 (without changing anything in my code), I have the errors described before.  Can you help me please to figure out what I'm doing wrong ? I suspect that highcharts-angular didn't follow the upgrade of highcharts package but I guess you are more expert than me to know why I'm having theses issues..

Thank you in advance for your answer and your help

**Comment by KacperMadej** [comment]
Hi @TitaneBoy 

Thank you for reporting about the problem.
It's not related to this Angular component stored in this repository, but let's keep this issue here for now.

For modules loading problem: please try using `require` like in this demo - https://codesandbox.io/s/lpn3yvv3zl

Could you comment on and check the TS issues @bre1470 ?

**Comment by bre1470** [comment]
Hi @TitaneBoy!

I see in you package configuration, that you use `@types/highcharts`. This creates a possible conflict with Highcharts v7, which brings its own type declaration. So I recommend uninstalling them `npm uninstall @types/highcharts`. The new type declaration introduce several incompatibilities with the third party types, that result in your problems. Let me address them step by step.

**Comment by bre1470** [comment]
> ![image](https://user-images.githubusercontent.com/15614466/49814117-f711cb80-fd36-11e8-948a-4934acd6809a.png)
> 
> I have a ts error message saying this:
> `[ts] Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("c:/Personal_Data/Web-Client/node_modules/highcharts/modules/exporting")' has no compatible call signatures. [2349]`
> 
> ![image](https://user-images.githubusercontent.com/15614466/49814187-1b6da800-fd37-11e8-90e6-8f93d3a58666.png)

The new declarations are linked with our source code. So in this case for example the declarations know, that our modules export a factory function instead of an object. The correct statement therefore is:
```js
import * as Highcharts from 'highcharts';
import ExportingModule from 'highcharts/modules/exporting';
ExportingModule(Highcharts);
```

**Comment by bre1470** [comment]
> Also, when adding series to charts like this:
> `this.Highcharts.charts[0].addSeries({`
> We could previously inject data in the SeriesOption with the 'data' attribute. But now, it seems that this attribute does not exist anymore (Is it true ?)
> 
> This is what I'm trying to do:
> ![image](https://user-images.githubusercontent.com/15614466/49814351-74d5d700-fd37-11e8-9f0d-5e3ed0948254.png)
> 
> And this is the ts error I got:
> ![image](https://user-images.githubusercontent.com/15614466/49814394-86b77a00-fd37-11e8-80f8-ca6155245032.png)
> 
> In Highcharts@6.2.0 version, everything was working great with my code. But when updating it to 7.0.0 (without changing anything in my code), I have the errors described before.

With the new declarations we introduced type pinning, which requires to set for each data series the `series.type` option, even when there is technically a default type or the `chart.type` already set. For example:
```ts
import * as Highcharts from `highcharts`;

Highcharts.chart('container', {
    chart: {
        type: 'line'
    },
    series: [{
        type: 'line', // <- type pinning required (cast to Highcharts.SeriesLineOptions)
        data: [[1, 2], [3, 4], [5, 6]]
    }]
});
```

**Comment by bre1470** [comment]
> In Highcharts@6.2.0 version, everything was working great with my code. But when updating it to 7.0.0 (without changing anything in my code), I have the errors described before.

I am sorry for the trouble. This is a temporary conflict, because the integrated TypeScript support is still in the beta phase and has a different API set than `@types/highcharts`. For helpful information in handling with the new declarations you can take a look at: https://www.highcharts.com/docs/advanced-chart-features/typescript. The document will gradually be updated with more information.

**Comment by TitaneBoy** [comment]
Hi @bre1470  and @KacperMadej .. Thank you for your quick answer... :-)

@bre1470 :  With your help, I've been able to fix previous ts error I was facing. For now, the only issue I'm facing is with the "addSeries" function.

When you say:

> With the new declarations we introduced type pinning, which requires to set for each data series the `series.type` option, even when there is technically a default type or the `chart.type` already set. For example:
> 
> ```ts
> import * as Highcharts from `highcharts`;
> 
> Highcharts.chart('container', {
>     chart: {
>         type: 'line'
>     },
>     series: [{
>         type: 'line', // <- type pinning required (cast to Highcharts.SeriesLineOptions)
>         data: [[1, 2], [3, 4], [5, 6]]
>     }]
> });
> ```

The problem for me, it's I don't know in advance how many series I will have in my charts. It will depends on the asynchroneous function response I use before. But in your example, you set in advance in the chart options the "series" attribute but in my case, as I said, I can't know in advance how many series I will have in my chart. This is why I'm using the 'addSeries' function. But in the 6.2.0 version of highcharts, we could set the 'data' attribute of the seriesOptions type parameter of the 'addSeries' function. But with the 7.0.0 version, It looks that we can't do that anymore. So How can we add dynamically series in our chart and set their data at the same time ? Is there any solution I can use to resolve my case ?

Thank you in advance for your answer

**Comment by TitaneBoy** [comment]
@bre1470 : Finally, a workaround I found to resolve my addSeries issue is to create the series without data in the seriesOptions type parameter, and then add a point, like this:

![image](https://user-images.githubusercontent.com/15614466/49888060-fdbe4280-fe0b-11e8-9caf-480a08513a17.png)

It looks to work like before. Do you think it's the normal way to add series dynamically with data ?

@KacperMadej : Using "require" seems to work now with the 7.0.0 version. Do you think that the module loading problem is just temporary and we could use in the future the "import" statement to import highcharts, highstock, etc. , instead of require ?

Thank you all for your help and answers... :-)  It's very appreciated

**Comment by TitaneBoy** [comment]
Just in case, here is my tsconfig.json configuration:

![image](https://user-images.githubusercontent.com/15614466/49888639-7e317300-fe0d-11e8-9a59-4222e79b7270.png)

**Comment by KacperMadej** [comment]
@TitaneBoy 

As far as I know adding `require` without `decalre var require: any;` should be possible to resolve through Angular or TS options, but it might depend on used versions of Angular or TS, so safest option would be to check docs of the software.

Using `require` is an alternative way of loading modules. The solution should be as provided by **bre1470** in her comment as:

```js
import * as Highcharts from 'highcharts';
import ExportingModule from 'highcharts/modules/exporting';
ExportingModule(Highcharts);
```

**Comment by TitaneBoy** [comment]
@KacperMadej I understand your answer and it's true that using "import" to import highcharts works great...But it doesn't seem to work for importing highstock

`import * as Highcharts from 'highcharts/highstock'`   <---- Doesn't work

For me, to load highstock, I must use "require" instead of import.

![image](https://user-images.githubusercontent.com/15614466/49894980-4c280d00-fe1d-11e8-927a-0af1ea0d3063.png)

Anyway...Thank you very much everyone... :-)

**Comment by bre1470** [comment]
@TitaneBoy 
I like to answer your question about dynamic series with data property. The problem is, that not every type of series options has a data property, so the base interface for all is 'Highcharts.SeriesOptions'. But you can specify a more advanced type the same way:
```ts
this.Highcharts.charts[0].addSeries({
    type: 'column', // type pinning to Highcharts.SeriesColumnOptions
    data: [1, 2, 3, 4, 5]
} as Highcharts.SeriesColumnOptions)
```

But this actually a bug, because autocomplete should work here the same way like in initial options (see https://github.com/highcharts/highcharts/issues/9659). Thank you for the report and pointing your problem out.

Regarding you workaround: The solution with `addPoint` is a good workaround, but not so performant, especially when each 'add' results in a redraw. So you should do `series.addPoint([1, 2], false);`, to disable the redraw and when you are done with addding points, you can do a final `chart.redraw();`.

**Comment by TitaneBoy** [comment]
@bre1470 Thank you for your great advices.. I will apply your recommandations in my code :-) and will wait for the resolution of the issue #9659 to apply data to my dynamic series with the SeriesColumnOptions type...

Again, thank you very much and great job with this awesome library... :-)

**Comment by bre1470** [comment]
@TitaneBoy 
Thank you! :-)

**Comment by KacperMadej** [comment]
@TitaneBoy 

> import * as Highcharts from 'highcharts/highstock' <---- Doesn't work

Thank you for pointing this one. Source is now known and we're working on a solution.
**Workaround**: load stock as a module, so like:

```ts
import * as Highcharts from 'highcharts';
import StockModule from 'highcharts/modules/stock';
StockModule(Highcharts);
```

**Comment by TitaneBoy** [comment]
@KacperMadej 
Thank you for this great workaround.. :-)

**Comment by josh-channin** [comment]
@KacperMadej 
Thank you!
