### ISSUE TITLE
How to programmatically reset to the toplevel from a function after using drilldown button for three levels?

### ISSUE THREAD

**Issue by subrahmanyaKadiyala** [highcharts/highcharts-angular#95]
When we drilldown a barchart to three levels and try to reset to the top level by setting Options = new Options, the data in the graph is resetting, but we still have drillup button visible.  Clicking on the button mixes up new and old data in chart.  Our requirement is by external button (outside chart), we should be able to reset chart to a new series, drill down level should at top level and no-drill up button should be visible.  It should be a clean refresh of the chart.

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

P.S.
Try calling [`chart.drillUp`](https://api.highcharts.com/class-reference/Highcharts.Chart#drillUp) until this is `true`: `!this.drilldownLevels || this.drilldownLevels.length === 0`.
Based on drilldown module code:

```js
		 /**
		 * When the chart is drilled down to a child series, calling `chart.drillUp()`
		 * will drill up to the parent series. Requires the drilldown module.
		 *
		 * @function Highcharts.Chart#drillUp
		 */
		Chart.prototype.drillUp = function () {
		    if (!this.drilldownLevels || this.drilldownLevels.length === 0) {
		        return;
		    }

**Comment by subrahmanyaKadiyala** [comment]
Thanks,  I will post it to the high charts support.  The issue is with the access of the  chart from Angular wrapper, to do what’s recommended below.

Thanks again,

subra
