### ISSUE TITLE
Update to v7

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-angular#96]
Update to include .d.ts and all code from version 7.0.0 of Highcharts
Update demo to Angular 7+

Current status:
- waiting for TS problem to be resolved to avoid workaround (the problem about wrong path for Highstock definitions, while loading as a module (stock) works fine)
- waiting for decision about changes in chart.udpate - more here: https://github.com/highcharts/highcharts/issues/6943#issuecomment-447144577

**Comment by loveywjung** [comment]
hi @KacperMadej 
Can I use highcharts 7 with version 2.3.1 or should I wait a little longer?
thanks :-)

**Comment by KacperMadej** [comment]
Highcharts version 7.0.1 should be better for the wrapper than 7.0.0. Both problems listed in my above comment are now resolved.

I'll update the wrapper during next few days - hopefully today or tomorrow.

**Comment by KacperMadej** [comment]
Updated the demo app, docs, TypeScript definitions from Highcharts 7, and more.
Pushed and published.
All related issues with Highcharts are avoidable through API usage and have open issues that should be resolved in the near future.

Closing as resolved.
