### ISSUE TITLE
3D Pies not working in the Angular wrapper

### ISSUE THREAD

**Issue by ps3331333** [highcharts/highcharts-angular#97]
[This 3D pie demo](https://www.highcharts.com/demo/3d-pie) in native Highcharts is not working with the wrapper, as you can see [here](https://codesandbox.io/s/lpq5yx3lq9). Chart options are identical in both cases.

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

You need to add highcharts-3d module. See files in the pure JS demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/3d-pie/

Modify code as:

```ts
import * as Highcharts from "highcharts";
import * as hc3d from "highcharts/highcharts-3d";
hc3d(Highcharts);
```

and the demo will work.

If you have any questions or require any help with Highcharts please contact us through [support channels](www.highcharts.com/support) and please let's keep GitHub issues for bug reports.

Closing as resolved.
